/** PASS-034 — Delegate personalization to mentor-engine (rule-based foundation; LLM later) */

export {
  generateMentorInsights,
  pickPrimaryMentorInsight,
  discoverCrossWorldPaths,
  discoverSecretPaths,
  getAdaptiveRecommendations,
  generateDailyHooks,
  generateMentorChallenges,
  buildMentorMemory,
  getSomeoneLikeMePatterns,
  getWorldCrossovers,
  getWorldObsession,
  getRabbitHoles,
  rabbitHolesForTerm,
  rabbitHolesForProducer,
  getLegendaryObject,
  legendaryObjectsForWorld,
  AMBITION_IDENTITIES,
  DREAM_WANTS,
  type LivingJourneySnapshot,
  type IdentityContext,
  type MentorInsight,
  type MentorMemoryLine,
  type MentorChallenge,
  type SecretPath,
  type CrossWorldDiscovery,
  type AdaptiveRecommendation,
  type DailyObsessionHook,
  type SomeoneLikeMePattern,
  type UnlockedLegendaryObject,
} from '@foundry/mentor-engine';
