const { app } = require('./_helpers');

module.exports = {
  id: 'film-cinema',
  slug: 'film-cinema',
  name: 'Film & Cinema',
  icon: '🎬',
  apps: [
    app('film-cinema', 'Film & Cinema Guide', ['movie-memorabilia', 'director-auteurs'], 'P1'),
    app('director-auteurs', 'Director Auteurs', ['film-cinema', 'film-criterion'], 'P2'),
    app('film-criterion', 'Criterion Collection', ['director-auteurs', 'film-cinema']),
    app('film-noir', 'Film Noir Authority', ['fiction-crime', 'classic-cinema']),
    app('classic-cinema', 'Classic Cinema Golden Age', ['film-noir', 'director-auteurs']),
    app('film-scifi', 'Science Fiction Cinema', ['fiction-scifi', 'film-cinema']),
    app('film-horror', 'Horror Cinema Authority', ['fiction-horror', 'film-cinema']),
    app('film-comedy', 'Comedy Cinema Guide', ['film-cinema', 'comedy-film']),
    app('comedy-film', 'Comedy Film Classics', ['film-comedy', 'classic-cinema']),
    app('film-drama', 'Drama Cinema Authority', ['film-cinema', 'director-auteurs']),
    app('film-action', 'Action Cinema Guide', ['film-cinema', 'film-thriller']),
    app('film-thriller', 'Thriller Cinema', ['film-noir', 'fiction-mystery']),
    app('film-romance', 'Romance Cinema', ['film-drama', 'fiction-romance']),
    app('film-documentary', 'Documentary Cinema', ['film-cinema', 'nonfiction-history']),
    app('film-animation', 'Animation Cinema', ['film-cinema', 'children-books']),
    app('film-anime', 'Anime Cinema Guide', ['film-animation', 'manga-collection']),
    app('film-indie', 'Independent Cinema', ['film-cinema', 'film-festivals']),
    app('film-festivals', 'Film Festival Guide', ['film-indie', 'director-auteurs']),
    app('film-foreign', 'Foreign Language Cinema', ['film-cinema', 'world-travel']),
    app('french-cinema', 'French Cinema Authority', ['film-foreign', 'director-auteurs']),
    app('italian-cinema', 'Italian Cinema Guide', ['film-foreign', 'classic-cinema']),
    app('japanese-cinema', 'Japanese Cinema', ['film-foreign', 'film-anime']),
    app('korean-cinema', 'Korean Cinema Authority', ['film-foreign', 'kpop-music']),
    app('indian-cinema', 'Indian Cinema & Bollywood', ['film-foreign', 'bollywood-music']),
    app('british-cinema', 'British Cinema Guide', ['film-foreign', 'classic-cinema']),
    app('german-cinema', 'German Cinema', ['film-foreign', 'film-noir']),
    app('latin-cinema', 'Latin American Cinema', ['film-foreign', 'latin-music']),
    app('african-cinema', 'African Cinema', ['film-foreign', 'world-travel']),
    app('nordic-cinema', 'Nordic Cinema', ['film-foreign', 'film-noir']),
    app('hong-kong-cinema', 'Hong Kong Cinema', ['film-action', 'film-foreign']),
    app('silent-film', 'Silent Film Era', ['classic-cinema', 'film-history']),
    app('film-history', 'Film History Archive', ['classic-cinema', 'director-auteurs']),
    app('western-films', 'Western Films Guide', ['fiction-western', 'classic-cinema']),
    app('war-films', 'War Films Authority', ['fiction-war', 'film-drama']),
    app('musical-films', 'Movie Musicals', ['film-cinema', 'classical-music']),
    app('film-noir-neo', 'Neo-Noir Cinema', ['film-noir', 'film-thriller']),
    app('superhero-films', 'Superhero Cinema', ['film-action', 'comic-books']),
    app('franchise-films', 'Film Franchises Hub', ['superhero-films', 'film-action']),
    app('marvel-cinema', 'Marvel Cinematic Universe', ['superhero-films', 'franchise-films']),
    app('dc-cinema', 'DC Films Universe', ['superhero-films', 'franchise-films']),
    app('star-wars-cinema', 'Star Wars Universe', ['film-scifi', 'franchise-films']),
    app('star-trek-cinema', 'Star Trek Universe', ['film-scifi', 'franchise-films']),
    app('james-bond-cinema', 'James Bond Collection', ['film-action', 'film-thriller']),
    app('horror-franchises', 'Horror Franchise Guide', ['film-horror', 'franchise-films']),
    app('slasher-films', 'Slasher Films', ['film-horror', 'horror-franchises']),
    app('psychological-horror', 'Psychological Horror', ['film-horror', 'film-thriller']),
    app('creature-features', 'Creature Features', ['film-horror', 'film-scifi']),
    app('cult-films', 'Cult Films Authority', ['film-indie', 'midnight-movies']),
    app('midnight-movies', 'Midnight Movies', ['cult-films', 'film-horror']),
    app('b-movies', 'B-Movies & Exploitation', ['cult-films', 'film-history']),
    app('film-techniques', 'Cinematography & Techniques', ['director-auteurs', 'film-history']),
    app('film-editing', 'Film Editing Mastery', ['film-techniques', 'director-auteurs']),
    app('film-screenwriting', 'Screenwriting Authority', ['writing-craft', 'film-cinema']),
    app('film-acting', 'Acting & Performance', ['film-drama', 'theater-stage']),
    app('film-costume', 'Costume & Production Design', ['film-cinema', 'fashion-vintage']),
    app('film-vfx', 'Visual Effects Cinema', ['film-scifi', 'film-action']),
    app('film-sound-design', 'Film Sound Design', ['film-scores', 'film-techniques']),
    app('imax-cinema', 'IMAX & Large Format', ['film-cinema', 'film-techniques']),
    app('drive-in-cinema', 'Drive-In Theater Guide', ['classic-cinema', 'film-cinema']),
    app('arthouse-cinema', 'Arthouse Theater Guide', ['film-indie', 'film-criterion']),
    app('movie-memorabilia', 'Movie Memorabilia', ['film-cinema', 'autograph-collection']),
    app('movie-posters', 'Movie Poster Collecting', ['movie-memorabilia', 'art-auctions']),
    app('film-awards', 'Film Awards Tracker', ['oscars-guide', 'film-cinema']),
    app('oscars-guide', 'Academy Awards Authority', ['film-awards', 'film-cinema']),
    app('cannes-films', 'Cannes Film Festival', ['film-festivals', 'film-foreign']),
    app('sundance-films', 'Sundance Film Festival', ['film-festivals', 'film-indie']),
    app('venice-films', 'Venice Film Festival', ['film-festivals', 'film-foreign']),
    app('film-reviews-network', 'Film Reviews Network', ['film-cinema', 'film-awards']),
    app('movie-watchlist', 'Movie Watchlist Tracker', ['film-reviews-network', 'streaming-films']),
    app('streaming-films', 'Streaming Film Guide', ['movie-watchlist', 'tv-streaming-hub']),
    app('film-4k-uhd', '4K UHD Film Collection', ['film-criterion', 'home-theater']),
    app('film-bluray', 'Blu-ray Collecting', ['film-4k-uhd', 'film-criterion']),
    app('film-restoration', 'Film Restoration & Archives', ['classic-cinema', 'film-history']),
    app('film-theory', 'Film Theory & Criticism', ['film-history', 'director-auteurs']),
    app('film-movements', 'Film Movements Guide', ['film-history', 'french-cinema']),
    app('new-wave-cinema', 'French New Wave', ['french-cinema', 'film-movements']),
    app('german-expressionism', 'German Expressionism', ['german-cinema', 'film-horror']),
    app('italian-neorealism', 'Italian Neorealism', ['italian-cinema', 'film-movements']),
    app('mumblecore-films', 'Mumblecore & Microbudget', ['film-indie', 'film-festivals']),
    app('short-films', 'Short Film Collection', ['film-festivals', 'film-indie']),
    app('student-films', 'Student & Emerging Filmmakers', ['film-festivals', 'short-films']),
    app('film-clubs', 'Film Club Organizer', ['film-reviews-network', 'arthouse-cinema'], 'P2'),
    app('movie-trivia', 'Movie Trivia Authority', ['film-cinema', 'franchise-films']),
    app('film-locations', 'Film Location Tours', ['film-cinema', 'world-travel']),
    app('book-to-film-hub', 'Book to Film Hub', ['book-to-film', 'film-cinema']),
    app('film-pairing-dining', 'Dinner & Movie Pairing', ['meals-pairing', 'film-cinema']),
    app('date-night-films', 'Date Night Film Guide', ['film-romance', 'film-pairing-dining']),
    app('family-films', 'Family Film Night', ['film-animation', 'children-books']),
    app('film-noir-streaming', 'Noir Streaming Picks', ['film-noir', 'streaming-films']),
    app('director-spielberg', 'Spielberg Filmography', ['director-auteurs', 'film-action']),
    app('director-kubrick', 'Kubrick Filmography', ['director-auteurs', 'film-scifi']),
    app('director-hitchcock', 'Hitchcock Filmography', ['director-auteurs', 'film-thriller']),
    app('director-tarantino', 'Tarantino Filmography', ['director-auteurs', 'film-action']),
    app('director-nolan', 'Nolan Filmography', ['director-auteurs', 'film-scifi']),
    app('director-scorsese', 'Scorsese Filmography', ['director-auteurs', 'film-drama']),
    app('director-miyazaki', 'Miyazaki & Ghibli Films', ['film-animation', 'japanese-cinema']),
    app('director-anderson', 'Wes Anderson Films', ['director-auteurs', 'film-comedy']),
    app('director-lynch', 'David Lynch Films', ['director-auteurs', 'psychological-horror']),
    app('film-ai-analysis', 'AI Film Analysis', ['film-cinema', 'ai-tools-guide']),
    app('film-podcasts', 'Film Podcast Guide', ['film-reviews-network', 'podcast-creator']),
    app('cinema-architecture', 'Cinema Architecture', ['arthouse-cinema', 'architecture-design']),
    app('film-preservation', 'Film Preservation Society', ['film-restoration', 'classic-cinema']),
    app('movie-quotes', 'Iconic Movie Quotes', ['film-cinema', 'film-trivia']),
    app('film-stunts', 'Stunt & Action Cinema', ['film-action', 'film-techniques']),
    app('martial-arts-films', 'Martial Arts Cinema', ['film-action', 'hong-kong-cinema']),
    app('spy-films', 'Spy & Espionage Films', ['james-bond-cinema', 'film-thriller']),
    app('heist-films', 'Heist Films Authority', ['film-thriller', 'film-action']),
    app('road-trip-films', 'Road Trip Cinema', ['film-drama', 'road-trip-america']),
    app('coming-of-age-films', 'Coming of Age Films', ['film-drama', 'fiction-ya']),
    app('sports-films', 'Sports Films Guide', ['college-baseball', 'film-drama']),
    app('courtroom-films', 'Courtroom Drama Films', ['film-drama', 'legal-professional']),
    app('prison-films', 'Prison Films Guide', ['film-drama', 'film-thriller']),
    app('zombie-films', 'Zombie Cinema', ['film-horror', 'horror-franchises']),
    app('vampire-films', 'Vampire Cinema', ['film-horror', 'fiction-gothic']),
    app('kaiju-films', 'Kaiju & Monster Films', ['creature-features', 'japanese-cinema']),
    app('film-collector-clubs', 'Film Collector Clubs', ['film-clubs', 'film-bluray'], 'P2'),
  ],
};
