const { app } = require('./_helpers');

module.exports = {
  id: 'music-audio',
  slug: 'music-audio',
  name: 'Music & Audio',
  icon: '🎵',
  apps: [
    app('vinyl-records', 'Vinyl Record Collection', ['music-production', 'concert-guide'], 'P1'),
    app('jazz-masters', 'Jazz Masters Guide', ['vinyl-records', 'blues-authority'], 'P2'),
    app('blues-authority', 'Blues Authority', ['jazz-masters', 'rock-legends']),
    app('rock-legends', 'Rock Legends Collection', ['blues-authority', 'vinyl-records']),
    app('classical-music', 'Classical Music Guide', ['jazz-masters', 'opera-collection'], 'P2'),
    app('hip-hop-culture', 'Hip-Hop Culture Guide', ['music-production', 'vinyl-records']),
    app('country-music', 'Country Music Guide', ['bluegrass-tradition', 'rock-legends']),
    app('bluegrass-tradition', 'Bluegrass Tradition', ['country-music', 'folk-americana']),
    app('electronic-music', 'Electronic Music Guide', ['music-production', 'concert-guide']),
    app('music-production', 'Music Production Studio', ['electronic-music', 'guitar-mastery']),
    app('guitar-mastery', 'Guitar Mastery', ['music-production', 'rock-legends']),
    app('piano-repertoire', 'Piano Repertoire', ['classical-music', 'music-production']),
    app('drum-percussion', 'Drum & Percussion', ['music-production', 'jazz-masters']),
    app('concert-guide', 'Concert & Live Music Guide', ['vinyl-records', 'music-festivals']),
    app('music-festivals', 'Music Festival Guide', ['concert-guide', 'electronic-music']),
    app('opera-collection', 'Opera Collection', ['classical-music', 'concert-guide']),
    app('folk-americana', 'Folk & Americana', ['bluegrass-tradition', 'country-music']),
    app('world-music', 'World Music Explorer', ['jazz-masters', 'vinyl-records']),
    app('audio-equipment', 'Audio Equipment Guide', ['vinyl-records', 'music-production']),
    app('podcast-creator', 'Podcast Creator Studio', ['music-production', 'audio-equipment']),
    app('r-and-b-soul', 'R&B & Soul Authority', ['hip-hop-culture', 'jazz-masters']),
    app('funk-music', 'Funk Music Guide', ['r-and-b-soul', 'jazz-masters']),
    app('reggae-music', 'Reggae & Dub Guide', ['world-music', 'vinyl-records']),
    app('latin-music', 'Latin Music Authority', ['world-music', 'salsa-music']),
    app('salsa-music', 'Salsa & Tropical', ['latin-music', 'dance-music']),
    app('afrobeat-music', 'Afrobeat & African Pop', ['world-music', 'funk-music']),
    app('kpop-music', 'K-Pop Collection', ['world-music', 'dance-music']),
    app('jpop-music', 'J-Pop & City Pop', ['world-music', 'kpop-music']),
    app('bollywood-music', 'Bollywood & Indian Film Music', ['world-music', 'indian-cinema']),
    app('celtic-music', 'Celtic & Irish Music', ['folk-americana', 'world-music']),
    app('metal-music', 'Heavy Metal Authority', ['rock-legends', 'punk-music']),
    app('punk-music', 'Punk & Hardcore', ['rock-legends', 'metal-music']),
    app('indie-music', 'Indie & Alternative', ['rock-legends', 'vinyl-records']),
    app('grunge-music', 'Grunge & 90s Rock', ['indie-music', 'rock-legends']),
    app('prog-rock', 'Progressive Rock', ['rock-legends', 'classical-music']),
    app('psychedelic-music', 'Psychedelic Music', ['rock-legends', 'prog-rock']),
    app('synthwave-music', 'Synthwave & Retrowave', ['electronic-music', 'vinyl-records']),
    app('ambient-music', 'Ambient & Drone', ['electronic-music', 'classical-music']),
    app('techno-music', 'Techno Authority', ['electronic-music', 'dance-music']),
    app('house-music', 'House Music Guide', ['electronic-music', 'dance-music']),
    app('dance-music', 'Dance & Club Music', ['electronic-music', 'music-festivals']),
    app('trance-music', 'Trance & EDM', ['electronic-music', 'music-festivals']),
    app('dubstep-music', 'Dubstep & Bass', ['electronic-music', 'drum-percussion']),
    app('lofi-music', 'Lo-Fi & Chillhop', ['electronic-music', 'ambient-music']),
    app('soundtrack-music', 'Film & Game Soundtracks', ['film-scores', 'gaming-soundtracks']),
    app('film-scores', 'Film Score Authority', ['soundtrack-music', 'classical-music']),
    app('gaming-soundtracks', 'Gaming Soundtracks', ['soundtrack-music', 'gaming-collectibles']),
    app('bass-guitar', 'Bass Guitar Mastery', ['guitar-mastery', 'jazz-masters']),
    app('violin-strings', 'Violin & Strings', ['classical-music', 'celtic-music']),
    app('saxophone-jazz', 'Saxophone & Jazz Horns', ['jazz-masters', 'blues-authority']),
    app('trumpet-brass', 'Trumpet & Brass', ['jazz-masters', 'classical-music']),
    app('vocals-singing', 'Vocals & Singing', ['opera-collection', 'music-production']),
    app('songwriting', 'Songwriting Craft', ['music-production', 'guitar-mastery']),
    app('music-theory', 'Music Theory Authority', ['classical-music', 'piano-repertoire']),
    app('ear-training', 'Ear Training & Aural Skills', ['music-theory', 'vocals-singing']),
    app('music-notation', 'Music Notation & Composition', ['music-theory', 'classical-music']),
    app('orchestration', 'Orchestration & Arrangement', ['classical-music', 'film-scores']),
    app('recording-studio', 'Recording Studio Guide', ['music-production', 'audio-equipment']),
    app('mixing-mastering', 'Mixing & Mastering', ['recording-studio', 'music-production']),
    app('live-sound', 'Live Sound Engineering', ['concert-guide', 'recording-studio']),
    app('dj-culture', 'DJ Culture & Mixing', ['dance-music', 'vinyl-records']),
    app('turntablism', 'Turntablism & Scratch', ['dj-culture', 'hip-hop-culture']),
    app('music-1980s', '1980s Music Decade', ['vinyl-records', 'synthwave-music']),
    app('music-1990s', '1990s Music Decade', ['grunge-music', 'hip-hop-culture']),
    app('music-2000s', '2000s Music Decade', ['indie-music', 'kpop-music']),
    app('music-2010s', '2010s Music Decade', ['streaming-music', 'indie-music']),
    app('music-2020s', '2020s Music Decade', ['streaming-music', 'lofi-music']),
    app('music-1960s', '1960s Music Revolution', ['rock-legends', 'psychedelic-music']),
    app('music-1970s', '1970s Music Golden Era', ['rock-legends', 'disco-music']),
    app('disco-music', 'Disco & Funk Era', ['funk-music', 'dance-music']),
    app('motown-music', 'Motown & Soul Classics', ['r-and-b-soul', 'vinyl-records']),
    app('british-invasion', 'British Invasion Rock', ['rock-legends', 'vinyl-records']),
    app('american-primitives', 'American Primitive Guitar', ['folk-americana', 'guitar-mastery']),
    app('delta-blues', 'Delta Blues Heritage', ['blues-authority', 'guitar-mastery']),
    app('chicago-blues', 'Chicago Blues', ['blues-authority', 'jazz-masters']),
    app('bebop-jazz', 'Bebop & Hard Bop', ['jazz-masters', 'saxophone-jazz']),
    app('cool-jazz', 'Cool Jazz & West Coast', ['jazz-masters', 'classical-music']),
    app('free-jazz', 'Free Jazz & Avant-Garde', ['jazz-masters', 'ambient-music']),
    app('baroque-music', 'Baroque Music', ['classical-music', 'opera-collection']),
    app('romantic-music', 'Romantic Era Music', ['classical-music', 'piano-repertoire']),
    app('modern-classical', 'Modern Classical', ['classical-music', 'ambient-music']),
    app('choral-music', 'Choral & Sacred Music', ['classical-music', 'opera-collection']),
    app('chamber-music', 'Chamber Music', ['classical-music', 'violin-strings']),
    app('symphony-orchestra', 'Symphony & Orchestra', ['classical-music', 'concert-guide']),
    app('music-box-sets', 'Box Sets & Deluxe Editions', ['vinyl-records', 'rare-records']),
    app('rare-records', 'Rare & Collectible Records', ['vinyl-records', 'music-box-sets']),
    app('cassette-tapes', 'Cassette Tape Culture', ['vinyl-records', 'indie-music']),
    app('cd-collection', 'CD Collection Guide', ['vinyl-records', 'music-box-sets']),
    app('streaming-music', 'Streaming Platform Guide', ['playlist-curation', 'vinyl-records']),
    app('playlist-curation', 'Playlist Curation Art', ['streaming-music', 'dj-culture']),
    app('music-awards', 'Music Awards Tracker', ['grammy-guide', 'vinyl-records']),
    app('grammy-guide', 'Grammy Awards Authority', ['music-awards', 'concert-guide']),
    app('music-biographies', 'Musician Biographies', ['rock-legends', 'nonfiction-music']),
    app('band-tributes', 'Tribute Bands & Covers', ['concert-guide', 'rock-legends']),
    app('open-mic', 'Open Mic & Local Scene', ['concert-guide', 'songwriting']),
    app('music-venues', 'Legendary Music Venues', ['concert-guide', 'music-festivals']),
    app('record-stores', 'Record Store Guide', ['vinyl-records', 'rare-records']),
    app('music-gear-reviews', 'Music Gear Reviews', ['audio-equipment', 'guitar-mastery']),
    app('pedalboards', 'Pedalboards & Effects', ['guitar-mastery', 'music-gear-reviews']),
    app('synthesizers', 'Synthesizer Collection', ['electronic-music', 'synthwave-music']),
    app('drum-machines', 'Drum Machines & Sequencers', ['electronic-music', 'music-production']),
    app('sample-libraries', 'Sample Libraries & Sound Design', ['music-production', 'electronic-music']),
    app('music-licensing', 'Music Licensing & Sync', ['music-production', 'film-scores']),
    app('music-business', 'Music Business Guide', ['music-licensing', 'concert-guide']),
    app('music-education', 'Music Education & Lessons', ['music-theory', 'guitar-mastery']),
    app('music-therapy', 'Music Therapy & Wellness', ['meditation-mindful', 'classical-music']),
    app('children-music', 'Children\'s Music', ['music-education', 'folk-americana']),
    app('lullabies-music', 'Lullabies & Sleep Music', ['children-music', 'ambient-music']),
    app('worship-music', 'Worship & Gospel Music', ['choral-music', 'r-and-b-soul']),
    app('gospel-music', 'Gospel & Spirituals', ['worship-music', 'blues-authority']),
    app('marching-bands', 'Marching Bands & Drum Corps', ['drum-percussion', 'concert-guide']),
    app('mariachi-music', 'Mariachi & Regional Mexican', ['latin-music', 'world-music']),
    app('flamenco-music', 'Flamenco Authority', ['latin-music', 'guitar-mastery']),
    app('fado-music', 'Fado & Portuguese Song', ['portugal-wines', 'world-music']),
    app('klezmer-music', 'Klezmer & Jewish Music', ['world-music', 'folk-americana']),
    app('polka-music', 'Polka & Accordion', ['folk-americana', 'world-music']),
    app('music-museums', 'Music Museums & Halls of Fame', ['music-venues', 'music-biographies']),
    app('music-documentaries', 'Music Documentaries', ['music-biographies', 'film-documentary']),
    app('music-podcasts', 'Music Podcast Guide', ['podcast-creator', 'vinyl-records']),
    app('music-collector-clubs', 'Music Collector Clubs', ['vinyl-records', 'rare-records'], 'P2'),
    app('album-reviews-network', 'Album Reviews Network', ['vinyl-records', 'music-collector-clubs']),
    app('concert-photography', 'Concert Photography', ['concert-guide', 'photography-concert']),
    app('music-memorabilia', 'Music Memorabilia', ['vinyl-records', 'autograph-collection']),
    app('setlist-archive', 'Setlist Archive', ['concert-guide', 'rock-legends']),
    app('music-trivia', 'Music Trivia & Quizzes', ['rock-legends', 'music-awards']),
    app('karaoke-guide', 'Karaoke Guide', ['vocals-singing', 'concert-guide']),
    app('a-cappella', 'A Cappella & Vocal Groups', ['vocals-singing', 'choral-music']),
    app('beatboxing', 'Beatboxing & Vocal Percussion', ['hip-hop-culture', 'a-cappella']),
    app('music-ai-tools', 'AI Music Tools', ['music-production', 'ai-tools-guide']),
    app('spatial-audio', 'Spatial & Immersive Audio', ['audio-equipment', 'streaming-music']),
    app('hi-res-audio', 'Hi-Res Audio Guide', ['audio-equipment', 'vinyl-records']),
    app('music-for-cooking', 'Music for Cooking', ['meals-pairing', 'playlist-curation']),
    app('music-for-workout', 'Workout Music Playlists', ['fitness-training', 'playlist-curation']),
    app('music-for-focus', 'Focus & Study Music', ['lofi-music', 'classical-music']),
  ],
};
