const { app } = require('./_helpers');
module.exports = {
  id: 'wine-beer', slug: 'wine-beer', name: 'Wine & Beer', icon: '🍷',
  apps: [
    app('wine-cellar', 'Wine Cellar Master', ['bourbon-connoisseur', 'meals-pairing'], 'P1'),
    app('champagne-sparkling', 'Champagne & Sparkling', ['wine-cellar', 'dessert-wines']),
    app('bordeaux-wines', 'Bordeaux Wine Authority', ['wine-cellar', 'burgundy-wines']),
    app('burgundy-wines', 'Burgundy Wine Guide', ['bordeaux-wines', 'wine-cellar']),
    app('napa-valley', 'Napa Valley Wines', ['wine-cellar', 'sonoma-wines']),
    app('sonoma-wines', 'Sonoma Wine Country', ['napa-valley', 'wine-cellar']),
    app('italian-wines', 'Italian Wine Collection', ['wine-cellar', 'bordeaux-wines']),
    app('spanish-wines', 'Spanish Wine Explorer', ['wine-cellar', 'portugal-wines']),
    app('portugal-wines', 'Portuguese Wine Guide', ['spanish-wines', 'wine-cellar']),
    app('dessert-wines', 'Dessert & Fortified Wines', ['wine-cellar', 'champagne-sparkling']),
    app('natural-wines', 'Natural & Biodynamic Wines', ['wine-cellar', 'italian-wines']),
    app('craft-beer', 'Craft Beer Authority', ['bourbon-connoisseur', 'homebrew-master'], 'P1'),
    app('ipa-specialist', 'IPA Specialist', ['craft-beer', 'homebrew-master']),
    app('stout-porter', 'Stout & Porter Guide', ['craft-beer', 'ipa-specialist']),
    app('belgian-beer', 'Belgian Beer Collection', ['craft-beer', 'german-beer']),
    app('german-beer', 'German Beer Tradition', ['belgian-beer', 'craft-beer']),
    app('sour-beer', 'Sour & Wild Beer', ['craft-beer', 'belgian-beer']),
    app('homebrew-master', 'Homebrew Master', ['craft-beer', 'ipa-specialist']),
    app('brewery-tours', 'Brewery Tour Guide', ['craft-beer', 'distillery-tours']),
    app('beer-food-pairing', 'Beer & Food Pairing', ['craft-beer', 'meals-pairing']),
    app('rhone-wines', 'Rhone Valley Wines', ['burgundy-wines', 'wine-cellar']),
    app('chianti-tuscany', 'Chianti & Tuscany Wines', ['italian-wines', 'wine-cellar']),
    app('rioja-wines', 'Rioja Wine Guide', ['spanish-wines', 'wine-cellar']),
    app('new-zealand-wines', 'New Zealand Wines', ['wine-cellar', 'natural-wines']),
    app('australian-wines', 'Australian Wine Guide', ['wine-cellar', 'new-zealand-wines']),
    app('south-african-wines', 'South African Wines', ['wine-cellar', 'world-travel']),
    app('argentina-malbec', 'Argentina Malbec', ['wine-cellar', 'latin-america-travel']),
    app('chilean-wines', 'Chilean Wine Guide', ['wine-cellar', 'argentina-malbec']),
    app('greek-wines', 'Greek Wine Explorer', ['wine-cellar', 'mediterranean-food']),
    app('georgian-wines', 'Georgian Wine Tradition', ['wine-cellar', 'natural-wines']),
    app('orange-wines', 'Orange & Skin-Contact Wines', ['natural-wines', 'wine-cellar']),
    app('rose-wines', 'Rosé Wine Guide', ['wine-cellar', 'provence-travel']),
    app('wine-tasting', 'Wine Tasting Masterclass', ['wine-cellar', 'tasting-notes']),
    app('sommelier-prep', 'Sommelier Certification Prep', ['wine-cellar', 'meals-pairing']),
    app('wine-invest', 'Wine Investment Guide', ['wine-cellar', 'real-estate-invest']),
    app('wine-auctions', 'Wine Auction Tracker', ['wine-invest', 'rare-bottles-wine']),
    app('rare-bottles-wine', 'Rare & Vintage Bottles', ['wine-cellar', 'wine-auctions']),
    app('wine-clubs', 'Wine Club Organizer', ['wine-cellar', 'social-wine'], 'P2'),
    app('social-wine', 'Wine Social Network', ['wine-clubs', 'restaurant-guide']),
    app('cider-guide', 'Craft Cider Guide', ['craft-beer', 'apple-orchards']),
    app('mead-guide', 'Mead & Honey Wine', ['craft-beer', 'beekeeping-guide']),
    app('hard-seltzer', 'Hard Seltzer & RTD', ['craft-beer', 'zero-proof-spirits']),
    app('kombucha-brew', 'Kombucha Brewing', ['wellness-recovery', 'homebrew-master']),
    app('barrel-beer', 'Barrel-Aged Beer', ['craft-beer', 'sour-beer']),
    app('lager-pilsner', 'Lager & Pilsner Guide', ['german-beer', 'craft-beer']),
    app('wheat-beer', 'Wheat & Hefeweizen', ['german-beer', 'belgian-beer']),
    app('pale-ale-guide', 'Pale Ale Authority', ['craft-beer', 'ipa-specialist']),
    app('beer-festivals', 'Beer Festival Guide', ['brewery-tours', 'music-festivals']),
    app('beer-ingredients', 'Hops & Malt Encyclopedia', ['homebrew-master', 'craft-beer']),
    app('nano-brewery', 'Nano Brewery Startup', ['homebrew-master', 'craft-spirits']),
    app('wine-regions-map', 'Global Wine Regions Map', ['wine-cellar', 'wine-country-tours']),
    app('wine-and-cheese', 'Wine & Cheese Pairing', ['artisan-cheese', 'wine-cellar']),
    app('wine-chocolate', 'Wine & Chocolate Pairing', ['chocolate-connoisseur', 'wine-cellar']),
    app('wine-cellar-mgmt', 'Cellar Management Pro', ['wine-cellar', 'wine-invest']),
    app('beer-cellaring', 'Beer Cellaring Guide', ['craft-beer', 'barrel-beer']),
    app('non-alc-beer', 'Non-Alcoholic Beer', ['craft-beer', 'zero-proof-spirits']),
    app('wine-label-art', 'Wine Label Art', ['wine-cellar', 'art-auctions']),
    app('vineyard-investing', 'Vineyard Investing', ['wine-invest', 'real-estate-invest']),
    app('harvest-season', 'Harvest Season Guide', ['wine-cellar', 'farm-to-table']),
    app('wine-history', 'Wine History Archive', ['wine-cellar', 'nonfiction-history']),
    app('beer-history', 'Beer History Archive', ['craft-beer', 'german-beer']),
    app('provence-travel', 'Provence Wine Travel', ['rose-wines', 'french-cuisine']),
    app('mediterranean-food', 'Mediterranean Cuisine Wines', ['italian-wines', 'greek-wines']),
    app('apple-orchards', 'Apple Orchard & Cider Tours', ['cider-guide', 'farm-to-table']),
    app('wine-ai-sommelier', 'AI Sommelier', ['wine-cellar', 'meals-pairing']),
    app('beer-ai-pairing', 'AI Beer Pairing', ['craft-beer', 'meals-pairing']),
    app('growler-trails', 'Growler & Taproom Trails', ['craft-beer', 'brewery-tours']),
    app('wine-collector-clubs', 'Wine Collector Clubs', ['wine-clubs', 'rare-bottles-wine'], 'P2'),
    app('beer-rating-network', 'Beer Rating Network', ['craft-beer', 'beer-festivals']),
    app('wine-rating-network', 'Wine Rating Network', ['wine-cellar', 'wine-collector-clubs']),
    app('mixed-drinks-wine', 'Wine Cocktails & Spritz', ['wine-cellar', 'craft-cocktails']),
    app('sangria-guide', 'Sangria & Wine Punch', ['spanish-wines', 'mixed-drinks-wine']),
    app('mulled-wine', 'Mulled Wine & Winter Drinks', ['dessert-wines', 'holiday-cocktails']),
    app('sake-wine-bridge', 'Sake & Wine Bridge', ['sake-mastery', 'wine-cellar']),
    app('local-breweries', 'Local Brewery Finder', ['craft-beer', 'growler-trails']),
    app('local-wineries', 'Local Winery Finder', ['wine-cellar', 'wine-country-tours']),
    app('wine-gift-guide', 'Wine Gift Curator', ['gift-curator', 'wine-cellar']),
    app('beer-gift-guide', 'Craft Beer Gift Curator', ['gift-curator', 'craft-beer']),
    app('wine-service-ritual', 'Wine Service & Ritual', ['sommelier-prep', 'wine-tasting']),
    app('beer-judging', 'Beer Judging & BJCP', ['homebrew-master', 'beer-festivals']),
    app('wine-competitions', 'Wine Competition Tracker', ['wine-awards-wine', 'wine-cellar']),
    app('wine-awards-wine', 'Wine Awards Authority', ['wine-competitions', 'wine-rating-network']),
    app('craft-maltsters', 'Craft Maltsters Guide', ['beer-ingredients', 'homebrew-master']),
    app('wild-fermentation-beer', 'Wild Fermentation Beer', ['sour-beer', 'natural-wines']),
    app('session-beers', 'Session & Low-ABV Beer', ['craft-beer', 'non-alc-beer']),
    app('imperial-stouts', 'Imperial Stout Collectors', ['stout-porter', 'craft-beer']),
    app('barleywine-guide', 'Barleywine & Strong Ale', ['imperial-stouts', 'craft-beer']),
    app('farmhouse-ales', 'Farmhouse & Saison', ['belgian-beer', 'sour-beer']),
    app('english-bitter', 'English Bitter & Mild', ['craft-beer', 'british-invasion']),
    app('scottish-ales', 'Scottish Ale Guide', ['scotch-whisky', 'craft-beer']),
    app('irish-stout', 'Irish Stout Tradition', ['stout-porter', 'irish-whiskey']),
    app('czech-pilsner', 'Czech Pilsner Heritage', ['lager-pilsner', 'german-beer']),
    app('trappist-beer', 'Trappist Beer Authority', ['belgian-beer', 'monastery-spirits']),
    app('monastery-spirits', 'Monastery Spirits & Beer', ['trappist-beer', 'liqueurs-cordials']),
    app('wine-franchise', 'Wine Franchise Brands', ['wine-cellar', 'napa-valley']),
    app('beer-collaborations', 'Brewery Collaborations', ['craft-beer', 'beer-festivals']),
    app('wine-vintage-charts', 'Vintage Charts Authority', ['wine-cellar', 'wine-invest']),
    app('beer-release-calendar', 'Beer Release Calendar', ['craft-beer', 'allocated-bottles']),
    app('terroir-encyclopedia', 'Terroir Encyclopedia', ['wine-regions-map', 'wine-cellar']),
    app('glassware-guide', 'Glassware & Serveware', ['wine-cellar', 'home-bar']),
    app('decanter-guide', 'Decanter & Aeration', ['wine-cellar', 'bourbon-connoisseur']),
    app('cork-cage-craft', 'Cork & Cage Crafts', ['wine-cellar', 'maker-crafts']),
    app('beer-coaster-collect', 'Beer Coaster Collecting', ['craft-beer', 'collectibles-vintage']),
    app('wine-cork-collect', 'Wine Cork Collecting', ['wine-cellar', 'collectibles-vintage']),
    app('home-winemaking', 'Home Winemaking', ['wine-cellar', 'homebrew-master']),
    app('wine-allergies', 'Wine & Diet Guide', ['wine-cellar', 'fitness-nutrition']),
    app('gluten-free-beer', 'Gluten-Free Beer', ['craft-beer', 'non-alc-beer']),
    app('kosher-wine', 'Kosher Wine Guide', ['wine-cellar', 'nonfiction-religion']),
    app('organic-wine', 'Organic Wine Certification', ['natural-wines', 'wine-cellar']),
    app('pet-nat-wine', 'Pét-Nat & Natural Bubbles', ['natural-wines', 'champagne-sparkling']),
    app('crémant-wines', 'Crémant & Regional Bubbles', ['champagne-sparkling', 'burgundy-wines']),
    app('english-sparkling', 'English Sparkling Wine', ['champagne-sparkling', 'british-cinema']),
    app('prosecco-guide', 'Prosecco Authority', ['champagne-sparkling', 'italian-wines']),
    app('cava-wines', 'Cava & Spanish Bubbles', ['spanish-wines', 'champagne-sparkling']),
    app('lambrusco-guide', 'Lambrusco & Frizzante', ['italian-wines', 'prosecco-guide']),
    app('wine-and-spirits-bridge', 'Wine & Spirits Bridge', ['wine-cellar', 'bourbon-connoisseur']),
    app('beer-and-spirits-bridge', 'Beer & Spirits Bridge', ['craft-beer', 'bourbon-connoisseur']),
    app('taplist-design', 'Taplist Design & Management', ['local-breweries', 'bar-management']),
    app('bar-management', 'Bar Management Pro', ['home-bar', 'bartender-cert']),
    app('wine-list-curation', 'Wine List Curation', ['restaurant-guide', 'sommelier-prep']),
    app('beer-menu-curation', 'Beer Menu Curation', ['restaurant-guide', 'craft-beer']),
    app('hospitality-beverage', 'Hospitality Beverage Ops', ['bar-management', 'wine-list-curation']),
    app('beverage-cost-control', 'Beverage Cost Control', ['hospitality-beverage', 'personal-finance']),
    app('staff-training-bev', 'Beverage Staff Training', ['sommelier-prep', 'bartender-cert']),
    app('consumer-beverage-ed', 'Consumer Beverage Education', ['wine-tasting', 'beer-judging']),
    app('beverage-tourism', 'Beverage Tourism Planner', ['wine-country-tours', 'whiskey-trail-tours']),
    app('global-cocktail-wine', 'Global Wine Cocktail Culture', ['mixed-drinks-wine', 'craft-cocktails']),
    app('beer-milestones', 'Beer Milestone Celebrations', ['craft-beer', 'beer-festivals']),
    app('wine-milestones', 'Wine Milestone Celebrations', ['wine-cellar', 'champagne-sparkling']),
    app('anniversary-pairing', 'Anniversary Pairing Guide', ['wine-milestones', 'date-night-films']),
    app('corporate-wine-events', 'Corporate Wine Events', ['wine-clubs', 'hospitality-beverage']),
    app('beer-club-organizer', 'Beer Club Organizer', ['craft-beer', 'beer-collector-clubs'], 'P2'),
    app('beer-collector-clubs', 'Beer Collector Clubs', ['beer-club-organizer', 'beer-rating-network']),
    app('expert-beverage-badges', 'Expert Beverage Badges', ['wine-collector-clubs', 'beer-collector-clubs']),
    app('cross-beverage-pairing', 'Cross-Beverage Pairing AI', ['wine-ai-sommelier', 'beer-ai-pairing']),
    app('seasonal-beverage', 'Seasonal Beverage Guide', ['wine-cellar', 'craft-beer']),
    app('summer-wine-beer', 'Summer Drinks Guide', ['rose-wines', 'session-beers']),
    app('winter-wine-beer', 'Winter Drinks Guide', ['mulled-wine', 'imperial-stouts']),
    app('spring-beverage', 'Spring Release Guide', ['beer-release-calendar', 'wine-vintage-charts']),
    app('fall-beverage', 'Fall Harvest Beverage', ['harvest-season', 'pumpkin-beer']),
    app('pumpkin-beer', 'Pumpkin & Seasonal Beer', ['craft-beer', 'fall-beverage']),
    app('holiday-beer', 'Holiday Beer Guide', ['craft-beer', 'winter-wine-beer']),
    app('beverage-photography', 'Beverage Photography', ['wine-cellar', 'craft-beer']),
    app('beverage-influencer', 'Beverage Creator Hub', ['beverage-photography', 'podcast-creator']),
    app('beverage-newsletter', 'Beverage Newsletter Builder', ['beverage-influencer', 'writing-craft']),
    app('beverage-subscription-box', 'Subscription Box Curator', ['wine-gift-guide', 'beer-gift-guide']),
    app('beverage-loyalty', 'Beverage Loyalty Programs', ['local-breweries', 'local-wineries']),
    app('qr-menu-beverage', 'QR Beverage Menus', ['taplist-design', 'restaurant-guide']),
    app('inventory-beverage', 'Beverage Inventory Tracker', ['wine-cellar-mgmt', 'beer-cellaring']),
    app('pos-beverage', 'Beverage POS Integration', ['hospitality-beverage', 'inventory-beverage']),
    app('distributor-beverage', 'Beverage Distributor Guide', ['hospitality-beverage', 'nano-brewery']),
    app('regulatory-beverage', 'Beverage Regulations Guide', ['homebrew-master', 'home-winemaking']),
    app('shipping-beverage', 'Beverage Shipping Laws', ['regulatory-beverage', 'wine-invest']),
    app('drizly-alternatives', 'Beverage Delivery Guide', ['local-breweries', 'local-wineries']),
    app('beverage-sustainability', 'Sustainable Beverage', ['organic-wine', 'craft-spirits']),
    app('water-source-beer', 'Brewing Water Chemistry', ['beer-ingredients', 'homebrew-master']),
    app('yeast-lab-beer', 'Yeast Lab & Cultures', ['homebrew-master', 'wild-fermentation-beer']),
    app('wine-lab-analysis', 'Wine Lab Analysis', ['home-winemaking', 'wine-vintage-charts']),
    app('blind-tasting-club', 'Blind Tasting Clubs', ['wine-tasting', 'bourbon-connoisseur'], 'P2'),
    app('beverage-expert-network', 'Beverage Expert Network', ['expert-beverage-badges', 'blind-tasting-club']),
    app('beverage-tier3-social', 'Beverage Social Clubs', ['wine-clubs', 'beer-club-organizer']),
    app('unified-tasting-journal', 'Unified Tasting Journal', ['tasting-notes', 'reading-journal']),
    app('beverage-cross-app-hub', 'Beverage Cross-App Hub', ['cross-beverage-pairing', 'meals-pairing']),
  ],
};
