import type { WorldEventDefinition } from '../types';

type Seed = Omit<WorldEventDefinition, 'world_slug'> & { world_slug?: string };

function ev(world: string, e: Seed): WorldEventDefinition {
  return { ...e, world_slug: world };
}

export const AI_BUILDER_EVENTS: WorldEventDefinition[] = [
  ev('ai-builder', {
    event_id: 'ai-mystery-useful-vs-toy',
    event_type: 'daily_mystery',
    title: 'Why do some AI apps feel useful and others feel like toys?',
    short_hook: 'Workflow depth vs demo sparkle.',
    deep_description: 'Useful apps solve recurring pain with reliable output. Toys impress once then gather dust. The difference is product thinking, not model size.',
    why_it_matters: 'Separating tools from toys saves months of building the wrong thing.',
    primary_action: { label: 'Homework Assistant', href: '/ai-builder/missions/homework-assistant' },
    user_interaction_type: 'view',
  }),
  ev('ai-builder', {
    event_id: 'ai-rivalry-nocode-code',
    event_type: 'weekly_rivalry',
    title: 'No-code vs code',
    short_hook: 'Speed vs control — which path matches your build?',
    deep_description: 'No-code ships faster for personal automation. Code scales and composes. Most builders need both over time.',
    why_it_matters: 'Pick a lane for this week\'s challenge — not forever.',
    primary_action: { label: 'Playground', href: '/ai-builder/playground' },
    user_interaction_type: 'vote',
    rivalry_options: [
      { id: 'no-code', label: 'No-code first' },
      { id: 'code', label: 'Code first' },
    ],
  }),
  ev('ai-builder', {
    event_id: 'ai-spotlight-assistant',
    event_type: 'spotlight',
    title: 'Personal assistant workflow',
    short_hook: 'One assistant that actually runs weekly.',
    deep_description: 'Not ten prompts — one chain that produces an artifact you reuse.',
    why_it_matters: 'Spotlights turn AI from chat into infrastructure.',
    primary_action: { label: 'Portfolio', href: '/ai-builder/portfolio' },
    related_collections: ['ai-workflow-collector'],
    user_interaction_type: 'view',
  }),
  ev('ai-builder', {
    event_id: 'ai-debate-prompt-vs-product',
    event_type: 'debate',
    title: 'Prompting skill or product thinking?',
    short_hook: 'Which matters more for builders in 2026?',
    deep_description: 'Great prompts without a user problem still fail. Great product sense with mediocre prompts can still ship.',
    why_it_matters: 'Where you invest learning time changes what you build.',
    primary_action: { label: 'Prompt lab', href: '/ai-builder/experiences/prompt-lab' },
    user_interaction_type: 'respond',
    debate_options: [
      { id: 'prompting', label: 'Prompting skill' },
      { id: 'product', label: 'Product thinking' },
    ],
  }),
  ev('ai-builder', {
    event_id: 'ai-challenge-automate',
    event_type: 'challenge',
    title: 'Automate one boring task',
    short_hook: 'Something that runs without you this week.',
    deep_description: 'Pick a recurring annoyance — email triage, file rename, weekly summary — and ship a working automation.',
    why_it_matters: 'Evidence beats intention. Your portfolio should show time saved.',
    primary_action: { label: 'Start mission', href: '/ai-builder/missions/homework-assistant' },
    related_collections: ['automation-builder', 'ai-workflow-collector'],
    user_interaction_type: 'complete',
    collector_action: { action_type: 'event_challenge_completed', action_id: 'ai-challenge-automate' },
  }),
  ev('ai-builder', {
    event_id: 'ai-rabbit-wrappers',
    event_type: 'rabbit_hole',
    title: 'Why most AI wrappers fail',
    short_hook: 'Thin UI on top of ChatGPT is not a moat.',
    deep_description: 'Wrappers die when distribution, workflow lock-in, or data flywheels never appear.',
    why_it_matters: 'Learn failure patterns before you become one.',
    primary_action: { label: 'Careers path', href: '/ai-builder/careers' },
    user_interaction_type: 'save',
  }),
  ev('ai-builder', {
    event_id: 'ai-legend-first-automation',
    event_type: 'legendary_object',
    title: 'First useful automation',
    short_hook: 'The script that ran without you — proof you can ship.',
    deep_description: 'Every builder remembers the first time a machine did their work reliably.',
    why_it_matters: 'Legendary objects anchor identity — you are someone who ships.',
    primary_action: { label: 'Your portfolio', href: '/ai-builder/portfolio' },
    related_collections: ['first-product-builder'],
    user_interaction_type: 'view',
  }),
  ev('ai-builder', {
    event_id: 'ai-history-early-builders',
    event_type: 'history',
    title: 'Early software builders',
    short_hook: 'From hobbyists in garages to platforms that eat the world.',
    deep_description: 'Personal computing began with people who built tools for themselves first — same arc as AI builders today.',
    why_it_matters: 'History lowers impostor syndrome — the pattern repeats.',
    primary_action: { label: 'Academy', href: '/ai-builder/academy' },
    user_interaction_type: 'view',
  }),
];

export const FINANCIAL_INDEPENDENCE_EVENTS: WorldEventDefinition[] = [
  ev('financial-independence', {
    event_id: 'fi-mystery-budget-fail',
    event_type: 'daily_mystery',
    title: 'Why do most budgets fail?',
    short_hook: 'Not math — identity and shame.',
    deep_description: 'Budgets fail when they punish instead of assign jobs to dollars. Tracking beats wishing.',
    why_it_matters: 'Fix the emotional design and the spreadsheet finally sticks.',
    primary_action: { label: 'First budget mission', href: '/financial-independence/missions/first-budget' },
    user_interaction_type: 'view',
  }),
  ev('financial-independence', {
    event_id: 'fi-rivalry-index-pick',
    event_type: 'weekly_rivalry',
    title: 'Index funds vs stock picking',
    short_hook: 'Boring wealth vs exciting stories.',
    deep_description: 'Index funds win on average; stock picking wins in narratives. Which are you optimizing for?',
    why_it_matters: 'Clarity prevents strategy switching every news cycle.',
    primary_action: { label: 'Analyze stock mission', href: '/financial-independence/missions/analyze-stock' },
    user_interaction_type: 'vote',
    rivalry_options: [
      { id: 'index', label: 'Index funds' },
      { id: 'picking', label: 'Stock picking' },
    ],
  }),
  ev('financial-independence', {
    event_id: 'fi-spotlight-emergency',
    event_type: 'spotlight',
    title: 'Emergency fund',
    short_hook: 'The buffer that turns panic into options.',
    deep_description: 'Before optimization — survival. One month, then three, then six.',
    why_it_matters: 'Every FI path starts with breathing room.',
    primary_action: { label: 'Save $1000 mission', href: '/financial-independence/missions/save-1000' },
    related_collections: ['savings-streak'],
    user_interaction_type: 'view',
  }),
  ev('financial-independence', {
    event_id: 'fi-debate-debt-invest',
    event_type: 'debate',
    title: 'Pay debt first or invest first?',
    short_hook: 'Math vs psychology — both matter.',
    deep_description: 'High-interest debt usually wins. Employer match often wins. Personal peace matters too.',
    why_it_matters: 'Debates force explicit tradeoffs instead of vague guilt.',
    primary_action: { label: 'Playground', href: '/financial-independence/playground' },
    user_interaction_type: 'respond',
    debate_options: [
      { id: 'debt-first', label: 'Debt first' },
      { id: 'invest-first', label: 'Invest first' },
    ],
  }),
  ev('financial-independence', {
    event_id: 'fi-challenge-track-7',
    event_type: 'challenge',
    title: 'Track every dollar for 7 days',
    short_hook: 'No judgment — just observation.',
    deep_description: 'Log spending daily this week. Patterns appear faster than willpower.',
    why_it_matters: 'You cannot steer what you do not measure.',
    primary_action: { label: 'First budget', href: '/financial-independence/missions/first-budget' },
    related_collections: ['budget-builder'],
    user_interaction_type: 'complete',
    collector_action: { action_type: 'event_challenge_completed', action_id: 'fi-challenge-track-7' },
  }),
  ev('financial-independence', {
    event_id: 'fi-rabbit-compound',
    event_type: 'rabbit_hole',
    title: 'Compound interest',
    short_hook: 'The curve that feels boring until it does not.',
    deep_description: 'Time is the ingredient — early dollars matter more than late bravado.',
    why_it_matters: 'Understanding the curve changes patience.',
    primary_action: { label: 'Learn hub', href: '/financial-independence/learn' },
    user_interaction_type: 'save',
  }),
  ev('financial-independence', {
    event_id: 'fi-legend-1000',
    event_type: 'legendary_object',
    title: 'First $1,000 saved',
    short_hook: 'The number that proves the habit started.',
    deep_description: 'Not rich — started. The first thousand is identity evidence.',
    why_it_matters: 'Legendary objects mark transformation milestones.',
    primary_action: { label: 'Portfolio', href: '/financial-independence/portfolio' },
    related_collections: ['savings-streak'],
    user_interaction_type: 'view',
  }),
  ev('financial-independence', {
    event_id: 'fi-history-crash',
    event_type: 'history',
    title: 'Market crash lessons',
    short_hook: 'Panic sellers vs steady hands.',
    deep_description: 'Every crash teaches the same lesson — liquidity and temperament beat timing.',
    why_it_matters: 'History prepares you for the next headline.',
    primary_action: { label: 'Missions', href: '/financial-independence/missions' },
    user_interaction_type: 'view',
  }),
];

export const PUBLIC_SPEAKING_EVENTS: WorldEventDefinition[] = [
  ev('public-speaking', {
    event_id: 'ps-mystery-nerves',
    event_type: 'daily_mystery',
    title: 'Why do nerves feel worse before speaking than during?',
    short_hook: 'Anticipatory anxiety vs present-moment flow.',
    deep_description: 'Your body rehearses disaster before the first word. Once speaking starts, focus narrows.',
    why_it_matters: 'Naming the pattern reduces fear of fear.',
    primary_action: { label: 'Nerves coach', href: '/public-speaking/experiences/nerves-coach' },
    user_interaction_type: 'view',
  }),
  ev('public-speaking', {
    event_id: 'ps-rivalry-prep-extemp',
    event_type: 'weekly_rivalry',
    title: 'Prepared vs extemporaneous',
    short_hook: 'Structure vs spontaneity — both are skills.',
    deep_description: 'Prepared talks land clarity; extemporaneous talks land authenticity. Great speakers blend both.',
    why_it_matters: 'Pick a practice mode for this week.',
    primary_action: { label: 'Speech builder', href: '/public-speaking/experiences/speech-builder' },
    user_interaction_type: 'vote',
    rivalry_options: [
      { id: 'prepared', label: 'Prepared' },
      { id: 'extemp', label: 'Extemporaneous' },
    ],
  }),
  ev('public-speaking', {
    event_id: 'ps-spotlight-3min',
    event_type: 'spotlight',
    title: 'The 3-minute talk',
    short_hook: 'Short enough to finish; long enough to matter.',
    deep_description: 'Three minutes forces one idea, one story, one landing.',
    why_it_matters: 'Spotlights give beginners a winnable stage.',
    primary_action: { label: 'First Talk mission', href: '/public-speaking/missions/first-talk' },
    related_collections: ['first-stage'],
    user_interaction_type: 'view',
  }),
  ev('public-speaking', {
    event_id: 'ps-debate-slides',
    event_type: 'debate',
    title: 'Slides or no slides?',
    short_hook: 'Visual aid vs distraction.',
    deep_description: 'Slides help structure; they also invite reading. No slides force presence.',
    why_it_matters: 'Host choices shape audience experience.',
    primary_action: { label: 'Playground', href: '/public-speaking/playground' },
    user_interaction_type: 'respond',
    debate_options: [
      { id: 'slides', label: 'Use slides' },
      { id: 'no-slides', label: 'No slides' },
    ],
  }),
  ev('public-speaking', {
    event_id: 'ps-challenge-record',
    event_type: 'challenge',
    title: 'Record one short talk',
    short_hook: 'Phone camera counts. Two minutes minimum.',
    deep_description: 'Watch yourself once — uncomfortable and essential.',
    why_it_matters: 'Video evidence beats vague improvement hopes.',
    primary_action: { label: 'Record review mission', href: '/public-speaking/missions/record-review' },
    related_collections: ['confidence-builder'],
    user_interaction_type: 'complete',
    collector_action: { action_type: 'event_challenge_completed', action_id: 'ps-challenge-record' },
  }),
  ev('public-speaking', {
    event_id: 'ps-rabbit-stories',
    event_type: 'rabbit_hole',
    title: 'Why stories stick',
    short_hook: 'Facts fade; scenes stay.',
    deep_description: 'Narrative architecture — beginning, turn, landing — is how audiences remember you.',
    why_it_matters: 'Story craft is speakership craft.',
    primary_action: { label: 'Story arc lab', href: '/public-speaking/experiences/story-arc-lab' },
    user_interaction_type: 'save',
  }),
  ev('public-speaking', {
    event_id: 'ps-legend-first-question',
    event_type: 'legendary_object',
    title: 'First audience question',
    short_hook: 'When the room talked back.',
    deep_description: 'Q&A is where confidence becomes conversation.',
    why_it_matters: 'Legendary moments mark the shift from monologue to dialogue.',
    primary_action: { label: 'Portfolio', href: '/public-speaking/portfolio' },
    user_interaction_type: 'view',
  }),
  ev('public-speaking', {
    event_id: 'ps-history-speeches',
    event_type: 'history',
    title: 'Famous speeches',
    short_hook: 'Rhetoric that moved nations — and what to steal.',
    deep_description: 'Study structure, not imitation. Great speeches are templates, not costumes.',
    why_it_matters: 'History gives permission to aim high.',
    primary_action: { label: 'Lore', href: '/public-speaking/lore' },
    user_interaction_type: 'view',
  }),
];

export const CIVIC_ENGAGEMENT_EVENTS: WorldEventDefinition[] = [
  ev('civic-engagement', {
    event_id: 'civic-mystery-board-power',
    event_type: 'daily_mystery',
    title: 'Where does a board get its power?',
    short_hook: 'Statute, budget, and who shows up.',
    deep_description: 'School boards and commissions derive authority from state law and local appointment — but attendance shapes outcomes.',
    why_it_matters: 'Mystery demystifies power so you can participate.',
    primary_action: { label: 'Research ballot', href: '/civic-engagement/missions/research-ballot' },
    user_interaction_type: 'view',
  }),
  ev('civic-engagement', {
    event_id: 'civic-rivalry-local-state',
    event_type: 'weekly_rivalry',
    title: 'Local government vs state government',
    short_hook: 'Where does your energy move the needle?',
    deep_description: 'Local decisions hit daily life; state decisions set the frame. Both need stewards.',
    why_it_matters: 'Focus beats overwhelm.',
    primary_action: { label: 'Missions', href: '/civic-engagement/missions' },
    user_interaction_type: 'vote',
    rivalry_options: [
      { id: 'local', label: 'Local focus' },
      { id: 'state', label: 'State focus' },
    ],
  }),
  ev('civic-engagement', {
    event_id: 'civic-spotlight-school-board',
    event_type: 'spotlight',
    title: 'School board meeting',
    short_hook: 'Budgets, books, and who decides for kids.',
    deep_description: 'Often the most accessible public meeting with real stakes.',
    why_it_matters: 'Spotlights give a concrete first step.',
    primary_action: { label: 'Forum attendee path', href: '/civic-engagement/portfolio' },
    related_collections: ['forum-attendee'],
    user_interaction_type: 'view',
  }),
  ev('civic-engagement', {
    event_id: 'civic-debate-comment',
    event_type: 'debate',
    title: 'Public comment: effective or symbolic?',
    short_hook: 'Does the mic change outcomes?',
    deep_description: 'Sometimes comment shifts votes; sometimes it builds record for appeals. Both can matter.',
    why_it_matters: 'Debates clarify why you show up.',
    primary_action: { label: 'Board watcher', href: '/civic-engagement/missions' },
    user_interaction_type: 'respond',
    debate_options: [
      { id: 'effective', label: 'Effective' },
      { id: 'symbolic', label: 'Mostly symbolic' },
    ],
  }),
  ev('civic-engagement', {
    event_id: 'civic-challenge-meeting',
    event_type: 'challenge',
    title: 'Watch one public meeting',
    short_hook: 'Agenda read + live or recording.',
    deep_description: 'Log date, body, and one decision you noticed.',
    why_it_matters: 'Presence is participation\'s first evidence.',
    primary_action: { label: 'Register mission', href: '/civic-engagement/missions/register-to-vote' },
    related_collections: ['public-meeting-tracker'],
    user_interaction_type: 'complete',
    collector_action: { action_type: 'event_challenge_completed', action_id: 'civic-challenge-meeting' },
  }),
  ev('civic-engagement', {
    event_id: 'civic-rabbit-rulemaking',
    event_type: 'rabbit_hole',
    title: 'Rulemaking',
    short_hook: 'How regulations become real life.',
    deep_description: 'Notice-and-comment periods turn bureaucracy into opportunity.',
    why_it_matters: 'Rulemaking is where detail lives.',
    primary_action: { label: 'Learn', href: '/civic-engagement/learn' },
    user_interaction_type: 'save',
  }),
  ev('civic-engagement', {
    event_id: 'civic-legend-first-comment',
    event_type: 'legendary_object',
    title: 'First public comment',
    short_hook: 'Your name in the record.',
    deep_description: 'Written or spoken — the first time you entered the official story.',
    why_it_matters: 'Legendary civic objects mark courage.',
    primary_action: { label: 'Portfolio', href: '/civic-engagement/portfolio' },
    user_interaction_type: 'view',
  }),
  ev('civic-engagement', {
    event_id: 'civic-history-ballot',
    event_type: 'history',
    title: 'Citizen-led ballot measures',
    short_hook: 'When signatures become law.',
    deep_description: 'Direct democracy tools vary by state — learn yours.',
    why_it_matters: 'History shows paths beyond voting alone.',
    primary_action: { label: 'Community', href: '/community/civic-engagement' },
    user_interaction_type: 'view',
  }),
];

export const BBQ_EVENTS: WorldEventDefinition[] = [
  ev('bbq', {
    event_id: 'bbq-mystery-stall',
    event_type: 'daily_mystery',
    title: 'Why does brisket stall?',
    short_hook: 'Evaporative cooling vs patience.',
    deep_description: 'The stall is physics, not failure — moisture cools the meat until collagen breaks down.',
    why_it_matters: 'Understanding the stall prevents panic wraps and bad decisions.',
    primary_action: { label: 'Brisket mission', href: '/bbq/missions/first-brisket' },
    user_interaction_type: 'view',
  }),
  ev('bbq', {
    event_id: 'bbq-rivalry-offset-pellet',
    event_type: 'weekly_rivalry',
    title: 'Offset vs pellet',
    short_hook: 'Fire tending vs set-and-monitor.',
    deep_description: 'Offsets teach fire; pellets teach consistency. Your yard and life pick the teacher.',
    why_it_matters: 'Rivalries clarify gear philosophy.',
    primary_action: { label: 'Cook log', href: '/bbq/experiences/cook-log' },
    user_interaction_type: 'vote',
    rivalry_options: [
      { id: 'offset', label: 'Offset smoker' },
      { id: 'pellet', label: 'Pellet grill' },
    ],
  }),
  ev('bbq', {
    event_id: 'bbq-spotlight-pork-butt',
    event_type: 'spotlight',
    title: 'Pork butt',
    short_hook: 'Forgiving cut — confidence builder.',
    deep_description: 'Long cook, big reward, hard to ruin completely.',
    why_it_matters: 'Spotlights should be repeatable wins.',
    primary_action: { label: 'First pork butt', href: '/bbq/missions/first-pork-butt' },
    related_collections: ['first-smoke'],
    user_interaction_type: 'view',
  }),
  ev('bbq', {
    event_id: 'bbq-debate-sauce',
    event_type: 'debate',
    title: 'Sauce or no sauce?',
    short_hook: 'Regional identity on the plate.',
    deep_description: 'Some regions sauce; some treat it as optional. Both camps have great food.',
    why_it_matters: 'Debates are culture, not correctness.',
    primary_action: { label: 'Rub lab', href: '/bbq/experiences/rub-and-sauce-journal' },
    user_interaction_type: 'respond',
    debate_options: [
      { id: 'sauce', label: 'Sauce belongs' },
      { id: 'no-sauce', label: 'No sauce needed' },
    ],
  }),
  ev('bbq', {
    event_id: 'bbq-challenge-log-cook',
    event_type: 'challenge',
    title: 'Log one cook',
    short_hook: 'Time, temp, wood, surprise.',
    deep_description: 'One honest cook log this week — mistakes included.',
    why_it_matters: 'Pitmasters journal; amateurs guess.',
    primary_action: { label: 'Cook log', href: '/bbq/experiences/cook-log' },
    related_collections: ['pitmaster-journal'],
    user_interaction_type: 'complete',
    collector_action: { action_type: 'event_challenge_completed', action_id: 'bbq-challenge-log-cook' },
  }),
  ev('bbq', {
    event_id: 'bbq-rabbit-smoke-ring',
    event_type: 'rabbit_hole',
    title: 'Smoke ring myths',
    short_hook: 'Pink is not always smoke.',
    deep_description: 'Myoglobin and chemistry — the ring is not a quality score alone.',
    why_it_matters: 'Myth-busting improves judging and hosting.',
    primary_action: { label: 'Learn', href: '/bbq/learn' },
    user_interaction_type: 'save',
  }),
  ev('bbq', {
    event_id: 'bbq-legend-first-brisket',
    event_type: 'legendary_object',
    title: 'First successful brisket',
    short_hook: 'Twelve hours of maybe — then yes.',
    deep_description: 'The cook that taught humility and pride in the same bite.',
    why_it_matters: 'Legendary objects anchor pit identity.',
    primary_action: { label: 'Portfolio', href: '/bbq/portfolio' },
    related_collections: ['brisket-apprentice'],
    user_interaction_type: 'view',
  }),
  ev('bbq', {
    event_id: 'bbq-history-regions',
    event_type: 'history',
    title: 'Regional BBQ traditions',
    short_hook: 'Carolina vinegar, Kansas sweet, Texas salt and pepper.',
    deep_description: 'Regions encode culture in smoke and sauce choices.',
    why_it_matters: 'History explains why your cousin fights about ribs.',
    primary_action: { label: 'Lore', href: '/bbq/lore' },
    user_interaction_type: 'view',
  }),
];

export const POKER_EVENTS: WorldEventDefinition[] = [
  ev('poker', {
    event_id: 'poker-mystery-fold-winners',
    event_type: 'daily_mystery',
    title: 'Why do good players fold winning hands?',
    short_hook: 'EV beats ego.',
    deep_description: 'Sometimes the best hand is not the best play — position, stack, and villain matter.',
    why_it_matters: 'Mystery teaches long-game thinking.',
    primary_action: { label: 'Review hands', href: '/poker/missions/review-ten-hands' },
    user_interaction_type: 'view',
  }),
  ev('poker', {
    event_id: 'poker-rivalry-gto-exploit',
    event_type: 'weekly_rivalry',
    title: 'GTO vs exploitative',
    short_hook: 'Balanced baseline vs targeting leaks.',
    deep_description: 'GTO protects you from exploitation; exploitative play prints when reads are good.',
    why_it_matters: 'Study time follows philosophy.',
    primary_action: { label: 'Study session', href: '/poker/missions' },
    user_interaction_type: 'vote',
    rivalry_options: [
      { id: 'gto', label: 'GTO baseline' },
      { id: 'exploit', label: 'Exploitative' },
    ],
  }),
  ev('poker', {
    event_id: 'poker-spotlight-position',
    event_type: 'spotlight',
    title: 'Position',
    short_hook: 'Act last, act best.',
    deep_description: 'Button, cutoff, blinds — position drives profit more than hero calls.',
    why_it_matters: 'Spotlights focus study where ROI is highest.',
    primary_action: { label: 'Position basics', href: '/poker/playground' },
    related_collections: ['position-student'],
    user_interaction_type: 'view',
  }),
  ev('poker', {
    event_id: 'poker-debate-bankroll-skill',
    event_type: 'debate',
    title: 'Is bankroll discipline more important than skill?',
    short_hook: 'Survival vs edge.',
    deep_description: 'Skill without bankroll dies to variance; bankroll without skill bleeds slowly.',
    why_it_matters: 'Debates prioritize your next improvement block.',
    primary_action: { label: 'Track bankroll', href: '/poker/missions/track-bankroll' },
    user_interaction_type: 'respond',
    debate_options: [
      { id: 'bankroll', label: 'Bankroll discipline' },
      { id: 'skill', label: 'Technical skill' },
    ],
  }),
  ev('poker', {
    event_id: 'poker-challenge-ten-hands',
    event_type: 'challenge',
    title: 'Review 10 hands',
    short_hook: 'Honest tags — leak, hero, standard.',
    deep_description: 'Log ten hands with one sentence each about what you would change.',
    why_it_matters: 'Hand review is where amateurs become students.',
    primary_action: { label: 'Hand journal', href: '/poker/experiences/hand-review-journal' },
    related_collections: ['hand-analyst'],
    user_interaction_type: 'complete',
    collector_action: { action_type: 'event_challenge_completed', action_id: 'poker-challenge-ten-hands' },
  }),
  ev('poker', {
    event_id: 'poker-rabbit-bluffs',
    event_type: 'rabbit_hole',
    title: 'Famous bluffs',
    short_hook: 'When story met math on television.',
    deep_description: 'Legendary bluffs teach timing, table image, and courage — not recklessness.',
    why_it_matters: 'Rabbit holes make study entertaining.',
    primary_action: { label: 'Lore', href: '/poker/lore' },
    user_interaction_type: 'save',
  }),
  ev('poker', {
    event_id: 'poker-legend-final-table',
    event_type: 'legendary_object',
    title: 'First final table',
    short_hook: 'When variance smiled back.',
    deep_description: 'Final tables change how you see tournaments — pressure becomes familiar.',
    why_it_matters: 'Legendary objects mark competitive identity.',
    primary_action: { label: 'Portfolio', href: '/poker/portfolio' },
    user_interaction_type: 'view',
  }),
  ev('poker', {
    event_id: 'poker-history-wsop',
    event_type: 'history',
    title: 'World Series legends',
    short_hook: 'The tournament that made poker television.',
    deep_description: 'Moneymaker effect and beyond — culture shapes how you learn the game.',
    why_it_matters: 'History connects you to the global story.',
    primary_action: { label: 'Tournament tracker', href: '/poker/experiences/tournament-log' },
    user_interaction_type: 'view',
  }),
];
