import type { OperatorMissionDef } from '../../operator/types';

export const SHIFT_MISSION_ID = 'the-shift';

export const shiftMission: OperatorMissionDef = {
  id: SHIFT_MISSION_ID,
  internalTitle: 'THE SHIFT',
  clocks: {
    open: '4:17 PM',
    waveOne: '4:43 PM',
    waveTwo: '5:16 PM',
    finale: '6:02 PM',
  },
  place: 'HEADQUARTERS',
  openingLines: ['Someone just handed you the room.'],
  facts: [
    { id: 'event', text: 'Kelly is expected at an evening public event in about two hours.' },
    { id: 'five', text: 'Five volunteers are supposed to help.' },
    { id: 'missing', text: 'One volunteer has not arrived.' },
    { id: 'office', text: 'The campaign office needs to remain covered.' },
    { id: 'social', text: 'A social post about the event has not gone out.' },
    { id: 'organizer', text: 'The event organizer is asking whether Kelly can arrive 20 minutes earlier.' },
    { id: 'vehicle', text: 'One volunteer has a vehicle.' },
    { id: 'community', text: 'Another knows the community well.' },
    { id: 'new', text: 'A new volunteer has walked in and does not know what to do.' },
    { id: 'box', text: 'A box of campaign material still needs to get to the event.' },
  ],
  people: [
    {
      id: 'maya',
      name: 'Maya',
      facts: ['First campaign shift.', 'Organized.', 'Nervous talking to strangers.'],
      firstShift: true,
    },
    {
      id: 'jordan',
      name: 'Jordan',
      facts: ['Knows the town and many people at the event.', 'Has a car.', 'Only available until 7.'],
      hasVehicle: true,
      availableUntil: '7:00 PM',
    },
    {
      id: 'eli',
      name: 'Eli',
      facts: ['Strong social and digital instincts.', 'Sometimes moves before confirming details.'],
    },
    {
      id: 'taylor',
      name: 'Taylor',
      facts: ['Dependable and personable.', 'Has worked several events.', 'Arrives 20 minutes late.'],
      arrivesLateMinutes: 20,
    },
    {
      id: 'new',
      name: 'New volunteer',
      facts: ['Just walked in.', 'No campaign experience.', 'Wants to help.'],
      isNew: true,
    },
    {
      id: 'self',
      name: 'You',
      facts: ['Temporarily responsible for this window.'],
      isSelf: true,
    },
  ],
  needs: [
    { id: 'office', label: 'Office coverage', bucket: 'now' },
    { id: 'materials', label: 'Event setup / material delivery', bucket: 'event' },
    { id: 'greeting', label: 'Community greeting / table', bucket: 'event' },
    { id: 'social', label: 'Social / event update', bucket: 'campaign' },
    { id: 'kelly', label: 'Accompanying / supporting Kelly', bucket: 'event' },
    { id: 'onboard', label: 'New volunteer onboarding', bucket: 'people' },
  ],
  firstPriorities: [
    { id: 'office', label: 'Keep the office covered while people move.' },
    { id: 'new', label: 'The person who just walked in has no direction.' },
    { id: 'organizer', label: 'The organizer is waiting on Kelly’s arrival time.' },
    { id: 'materials', label: 'The box of material is still here.' },
    { id: 'social', label: 'Nothing public has gone out about the event.' },
    { id: 'picture', label: 'Learn who is actually in the room before assigning anything.' },
  ],
  clarificationPrompt: 'The event organizer texts: “Can Kelly come earlier? We need to know now.”',
  clarificationChoices: [
    { id: 'promise', label: 'Promise Kelly will arrive earlier.' },
    { id: 'refuse', label: 'Refuse. The time is the time.' },
    { id: 'locked', label: 'Tell them nothing can change.' },
    { id: 'check', label: 'Check the schedule / contact the person who would know.' },
    { id: 'hold', label: 'Acknowledge them and say you are confirming.' },
    { id: 'guess', label: 'Give your best guess from what you have seen.' },
  ],
  communicationPrompt: 'The event organizer is waiting. What do you send?',
  interruptionPrompt:
    'A local reporter just arrived at headquarters asking whether Kelly can give them five minutes before the event.',
  interruptionChoices: [
    { id: 'take', label: 'Walk them back yourself and try to make it work.' },
    { id: 'protect', label: 'Protect the event. Kelly cannot stop now.' },
    { id: 'delegate', label: 'Ask someone here to stay with them while you keep the room moving.' },
    { id: 'comms', label: 'Find the campaign person who should speak for this.' },
    { id: 'later', label: 'Thank them and offer a later window.' },
    { id: 'ignore', label: 'Leave it. There is too much else happening.' },
  ],
  peopleFirstPrompt: 'The new volunteer sent 50 printed handouts to the wrong place.',
  peopleFirstChoices: [
    { id: 'blame', label: 'Tell them they created a problem we do not have time for.' },
    { id: 'takeover', label: 'Take the work back and finish it yourself.' },
    { id: 'quiet', label: 'Correct it quietly and move on.' },
    { id: 'teach', label: 'Fix it with them so they can do the next one.' },
    { id: 'reassign', label: 'Move them to something that matches what they can do today.' },
    { id: 'ask', label: 'Ask what happened before you decide.' },
  ],
  unknownPrompt: 'The QR signup printed on the event material is failing.',
  unknownChoices: [
    { id: 'troubleshoot', label: 'Troubleshoot it yourself.' },
    { id: 'test', label: 'Test the destination from another phone.' },
    { id: 'alternate', label: 'Use an alternate campaign URL.' },
    { id: 'ask', label: 'Ask someone who might know the site.' },
    { id: 'research', label: 'Look it up.' },
    { id: 'ai', label: 'Use AI to troubleshoot.' },
    { id: 'workaround', label: 'Make a temporary workaround so people can still sign up.' },
    { id: 'ignore', label: 'Leave it. The room is already full.' },
  ],
  unknownActChoices: [
    { id: 'test', label: 'Test the destination before changing anything.' },
    { id: 'alternate', label: 'Switch to the alternate campaign URL.' },
    { id: 'workaround', label: 'Write a short paper signup and a known working link.' },
    { id: 'ask', label: 'Bring the options to the person who owns the site.' },
    { id: 'ignore', label: 'Leave the QR as it is.' },
  ],
  aiReply:
    'Possible causes: bad redirect, outdated QR target, temporary site problem, or phone connection. Test the destination directly before changing anything.',
  criticalPrompt: 'You have 25 minutes. What has to be true before Kelly walks out the door?',
  criticalChoices: [
    { id: 'kelly_ready', label: 'Kelly knows where she is going and who is meeting her.' },
    { id: 'materials_there', label: 'Event materials are physically there.' },
    { id: 'office_covered', label: 'The office has coverage.' },
    { id: 'social_perfect', label: 'The social post is perfect.' },
    { id: 'everyone_assigned', label: 'Every volunteer has an assignment.' },
    { id: 'reporter_closed', label: 'The reporter has a complete response.' },
  ],
  criticalLimit: 3,
  handoffPrompt: "You're leaving this in someone else's hands. What do they need to know?",
  reflectSelfPrompt: 'What would you change about how you ran the shift?',
  reflectTeamPrompt: 'What worked because of someone else — not because of you?',
};

export const shiftCopy = {
  foundEyebrow: 'Earlier',
  foundTitle: 'You found something earlier.',
  useKey: 'Use the key',
  unlockTitle: 'The key opens responsibility.',
  unlockBody: 'For the next few minutes, this is yours.',
  enter: 'Step in',
  firstAsk: 'What do you deal with first?',
  firstReason: 'Why this, if you want to say.',
  assignTitle: 'Who can take what?',
  assignHint: 'You cannot do all of it yourself. Assign people, including yourself if you must.',
  handleSelf: 'I’ll take this',
  unassigned: 'Unassigned',
  continue: 'Continue',
  send: 'Send',
  waveKicker: 'The room now',
  aiKicker: 'A tool',
  aiLead: 'It offered possibilities. Not certainty.',
  finaleLead: 'The campaign moved.',
  keyEyebrow: 'Earned',
  keyTitle: 'KEY 02 ACQUIRED',
  keyRule: 'The People Rule',
  keyBody: 'Responsibility changes the view.',
  keyHint: 'There is one door left.',
  hookLines: ['You’ve been the volunteer.', 'You’ve run the shift.', 'Next, the people are yours to develop.'],
  notYet: 'Not yet',
  continueWhenReady: 'Continue when ready',
  twoMinutes: 'You have two minutes before the next thing begins.',
};
