import type { AssemblyInput, EntityDraft } from '../types';

/**
 * AI #1 — Entity Builder
 * OpenAI generates. Supabase owns. This produces the draft record.
 */
export async function buildEntity(input: AssemblyInput): Promise<EntityDraft> {
  const aliases = input.topic.split(' ').length > 1 ? [input.topic] : [];

  return {
    slug: input.slug,
    display_name: input.topic,
    entity_type: input.entity_type,
    description: `${input.topic} — entity record generated by Foundry Factory (draft).`,
    attributes: {
      ...input.attributes,
      factory_generated: true,
      entity_type: input.entity_type,
    },
    metadata: {
      vertical_domain: input.vertical_domain,
      generation_pass: 'PASS-006',
    },
    aliases,
    sources: ['factory:entity-builder'],
    status: 'draft',
  };
}
