import type { BottleRecord, ProducerRecord } from '../types';
import { sv } from '../sources/citations';

/** Catalog facts indexed from Level 1 inventory — editorial copy stays in platform deep layers */
export const BOTTLE_CATALOG: Omit<BottleRecord, 'comparable_bottle_slugs' | 'collection_path_slugs'>[] = [
  { slug: 'evan-williams-black', name: sv('Evan Williams Black Label', 'commonly_reported', 'editorial'), producer_slug: 'heaven-hill', category: 'bourbon', proof: sv(86, 'commonly_reported', 'editorial'), price_usd_est: sv(18, 'editorial', 'editorial', undefined, 'Approximate MSRP — market varies'), mashbill_style: sv('traditional', 'commonly_reported', 'editorial'), mash_bill_slug: 'heaven-hill-traditional' },
  { slug: 'old-forester-86', name: sv('Old Forester 86 Proof', 'commonly_reported', 'editorial'), producer_slug: 'old-forester', category: 'bourbon', proof: sv(86, 'commonly_reported', 'editorial'), price_usd_est: sv(22, 'editorial', 'editorial'), mashbill_style: sv('traditional', 'commonly_reported', 'editorial'), mash_bill_slug: 'old-forester-traditional' },
  { slug: 'wild-turkey-101', name: sv('Wild Turkey 101', 'commonly_reported', 'editorial'), producer_slug: 'wild-turkey', category: 'bourbon', proof: sv(101, 'commonly_reported', 'editorial'), price_usd_est: sv(28, 'editorial', 'editorial'), mashbill_style: sv('high-rye', 'commonly_reported', 'editorial'), mash_bill_slug: 'wild-turkey-high-rye' },
  { slug: 'makers-mark', name: sv("Maker's Mark", 'commonly_reported', 'editorial'), producer_slug: 'makers-mark', category: 'bourbon', proof: sv(90, 'commonly_reported', 'editorial'), price_usd_est: sv(32, 'editorial', 'editorial'), mashbill_style: sv('wheated', 'producer_disclosed', 'editorial', undefined, 'Wheated mash publicly described; percentages not disclosed'), mash_bill_slug: 'makers-mark-wheated' },
  { slug: 'four-roses-yellow', name: sv('Four Roses Yellow Label', 'commonly_reported', 'editorial'), producer_slug: 'four-roses', category: 'bourbon', proof: sv(80, 'commonly_reported', 'editorial'), price_usd_est: sv(24, 'editorial', 'editorial'), mashbill_style: sv('high-rye', 'commonly_reported', 'editorial'), mash_bill_slug: 'four-roses-obsq-style' },
  { slug: 'buffalo-trace', name: sv('Buffalo Trace', 'commonly_reported', 'editorial'), producer_slug: 'buffalo-trace', category: 'bourbon', proof: sv(90, 'commonly_reported', 'editorial'), price_usd_est: sv(30, 'editorial', 'editorial'), mashbill_style: sv('traditional', 'commonly_reported', 'editorial'), mash_bill_slug: 'buffalo-trace-mash-1' },
  { slug: 'woodford-reserve', name: sv('Woodford Reserve', 'commonly_reported', 'editorial'), producer_slug: 'woodford-reserve', category: 'bourbon', proof: sv(90.4, 'commonly_reported', 'editorial'), price_usd_est: sv(38, 'editorial', 'editorial'), mashbill_style: sv('traditional', 'commonly_reported', 'editorial'), mash_bill_slug: 'woodford-traditional' },
  { slug: 'knob-creek-9', name: sv('Knob Creek 9 Year', 'commonly_reported', 'editorial'), producer_slug: 'jim-beam', category: 'bourbon', proof: sv(100, 'commonly_reported', 'editorial'), age_years: sv(9, 'commonly_reported', 'editorial'), price_usd_est: sv(38, 'editorial', 'editorial'), mashbill_style: sv('traditional', 'commonly_reported', 'editorial'), mash_bill_slug: 'jim-beam-traditional' },
  { slug: 'bulleit-bourbon', name: sv('Bulleit Bourbon', 'commonly_reported', 'editorial'), producer_slug: 'four-roses', category: 'bourbon', proof: sv(90, 'commonly_reported', 'editorial'), price_usd_est: sv(32, 'editorial', 'editorial'), mashbill_style: sv('high-rye', 'commonly_reported', 'editorial'), mash_bill_slug: 'four-roses-sourced-high-rye', editorial_ref: 'sourced_label:four-roses' },
  { slug: 'larceny', name: sv('Larceny', 'commonly_reported', 'editorial'), producer_slug: 'heaven-hill', category: 'bourbon', proof: sv(92, 'commonly_reported', 'editorial'), price_usd_est: sv(28, 'editorial', 'editorial'), mashbill_style: sv('wheated', 'commonly_reported', 'editorial'), mash_bill_slug: 'heaven-hill-wheated' },
  { slug: '1792-small-batch', name: sv('1792 Small Batch', 'commonly_reported', 'editorial'), producer_slug: 'barton-1792', category: 'bourbon', proof: sv(93.7, 'commonly_reported', 'editorial'), price_usd_est: sv(32, 'editorial', 'editorial'), mashbill_style: sv('high-rye', 'commonly_reported', 'editorial'), mash_bill_slug: 'barton-high-rye' },
  { slug: 'eagle-rare', name: sv('Eagle Rare 10 Year', 'commonly_reported', 'editorial'), producer_slug: 'buffalo-trace', category: 'bourbon', proof: sv(90, 'commonly_reported', 'editorial'), age_years: sv(10, 'commonly_reported', 'editorial'), price_usd_est: sv(45, 'editorial', 'editorial'), mashbill_style: sv('traditional', 'commonly_reported', 'editorial'), mash_bill_slug: 'buffalo-trace-mash-1' },
  { slug: 'four-roses-single-barrel', name: sv('Four Roses Single Barrel', 'commonly_reported', 'editorial'), producer_slug: 'four-roses', category: 'bourbon', proof: sv(100, 'commonly_reported', 'editorial'), price_usd_est: sv(45, 'editorial', 'editorial'), mashbill_style: sv('high-rye', 'commonly_reported', 'editorial'), mash_bill_slug: 'four-roses-single-barrel' },
  { slug: 'old-forester-1920', name: sv('Old Forester 1920', 'commonly_reported', 'editorial'), producer_slug: 'old-forester', category: 'bourbon', proof: sv(115, 'commonly_reported', 'editorial'), price_usd_est: sv(65, 'editorial', 'editorial'), mashbill_style: sv('traditional', 'commonly_reported', 'editorial'), mash_bill_slug: 'old-forester-traditional' },
  { slug: 'russells-reserve-10', name: sv("Russell's Reserve 10 Year", 'commonly_reported', 'editorial'), producer_slug: 'wild-turkey', category: 'bourbon', proof: sv(90, 'commonly_reported', 'editorial'), age_years: sv(10, 'commonly_reported', 'editorial'), price_usd_est: sv(42, 'editorial', 'editorial'), mashbill_style: sv('high-rye', 'commonly_reported', 'editorial'), mash_bill_slug: 'wild-turkey-high-rye' },
  { slug: 'michters-us1', name: sv("Michter's US*1 Bourbon", 'commonly_reported', 'editorial'), producer_slug: 'michters', category: 'bourbon', proof: sv(91.4, 'commonly_reported', 'editorial'), price_usd_est: sv(48, 'editorial', 'editorial'), mashbill_style: sv('traditional', 'commonly_reported', 'editorial'), mash_bill_slug: 'michters-traditional' },
  { slug: 'new-riff-bourbon', name: sv('New Riff Bourbon', 'commonly_reported', 'editorial'), producer_slug: 'new-riff', category: 'bourbon', proof: sv(100, 'commonly_reported', 'editorial'), price_usd_est: sv(42, 'editorial', 'editorial'), mashbill_style: sv('high-rye', 'producer_disclosed', 'editorial', undefined, 'Craft distiller — non-chill filtered; mash style disclosed, not exact percentages'), mash_bill_slug: 'new-riff-high-rye' },
  { slug: 'bookers', name: sv("Booker's", 'commonly_reported', 'editorial'), producer_slug: 'jim-beam', category: 'bourbon', proof: sv(126, 'commonly_reported', 'editorial'), price_usd_est: sv(90, 'editorial', 'editorial'), mashbill_style: sv('traditional', 'commonly_reported', 'editorial'), mash_bill_slug: 'jim-beam-traditional' },
  { slug: 'weller-special-reserve', name: sv('Weller Special Reserve', 'commonly_reported', 'editorial'), producer_slug: 'buffalo-trace', category: 'bourbon', proof: sv(90, 'commonly_reported', 'editorial'), price_usd_est: sv(35, 'editorial', 'editorial'), mashbill_style: sv('wheated', 'commonly_reported', 'editorial'), mash_bill_slug: 'buffalo-trace-wheated' },
  { slug: 'rhetoric-24', name: sv('Orphan Barrel Rhetoric 24', 'commonly_reported', 'editorial'), producer_slug: 'jim-beam', category: 'bourbon', proof: sv(90.8, 'commonly_reported', 'editorial'), age_years: sv(24, 'commonly_reported', 'editorial'), price_usd_est: sv(150, 'editorial', 'editorial'), mashbill_style: sv('traditional', 'unknown', 'editorial'), mash_bill_slug: 'orphan-barrel-unknown', editorial_ref: 'ndp:orphan-barrel-program' },
];

export const PRODUCER_CATALOG: ProducerRecord[] = [
  { slug: 'buffalo-trace', name: sv('Buffalo Trace Distillery', 'verified', 'verified'), kind: 'distiller', category: 'bourbon', headquarters: sv('Frankfort, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Sazerac Company', 'commonly_reported', 'editorial'), dsp_code: sv('DSP-KY-113', 'commonly_reported', 'editorial'), founded: sv('1775 (site); Buffalo Trace brand 1999', 'commonly_reported', 'editorial'), mash_bill_slugs: ['buffalo-trace-mash-1', 'buffalo-trace-wheated'], terroir_slug: 'buffalo-trace-terroir', leader_slot_id: 'buffalo-trace-master', bottle_slugs: [] },
  { slug: 'jim-beam', name: sv('Jim Beam Distillery', 'verified', 'verified'), kind: 'distiller', category: 'bourbon', headquarters: sv('Clermont, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Beam Suntory', 'commonly_reported', 'editorial'), dsp_code: sv('DSP-KY-230', 'commonly_reported', 'editorial'), mash_bill_slugs: ['jim-beam-traditional', 'orphan-barrel-unknown'], terroir_slug: 'jim-beam-terroir', leader_slot_id: 'jim-beam-master', bottle_slugs: [] },
  { slug: 'heaven-hill', name: sv('Heaven Hill Distillery', 'verified', 'verified'), kind: 'distiller', category: 'bourbon', headquarters: sv('Bardstown, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Heaven Hill Brands (private)', 'commonly_reported', 'editorial'), dsp_code: sv('DSP-KY-31', 'commonly_reported', 'editorial'), mash_bill_slugs: ['heaven-hill-traditional', 'heaven-hill-wheated'], terroir_slug: 'heaven-hill-terroir', leader_slot_id: 'heaven-hill-master', bottle_slugs: [] },
  { slug: 'wild-turkey', name: sv('Wild Turkey Distillery', 'verified', 'verified'), kind: 'distiller', category: 'bourbon', headquarters: sv('Lawrenceburg, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Campari Group', 'commonly_reported', 'editorial'), dsp_code: sv('DSP-KY-52', 'commonly_reported', 'editorial'), mash_bill_slugs: ['wild-turkey-high-rye'], terroir_slug: 'wild-turkey-terroir', leader_slot_id: 'wild-turkey-master', bottle_slugs: [] },
  { slug: 'makers-mark', name: sv("Maker's Mark Distillery", 'verified', 'verified'), kind: 'distiller', category: 'bourbon', headquarters: sv('Loretto, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Beam Suntory', 'commonly_reported', 'editorial'), mash_bill_slugs: ['makers-mark-wheated'], terroir_slug: 'makers-mark-terroir', leader_slot_id: 'makers-mark-master', bottle_slugs: [] },
  { slug: 'four-roses', name: sv('Four Roses Distillery', 'verified', 'verified'), kind: 'distiller', category: 'bourbon', headquarters: sv('Lawrenceburg, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Kirin Holdings', 'commonly_reported', 'editorial'), dsp_code: sv('DSP-KY-10', 'commonly_reported', 'editorial'), mash_bill_slugs: ['four-roses-obsq-style', 'four-roses-single-barrel', 'four-roses-sourced-high-rye'], terroir_slug: 'four-roses-terroir', leader_slot_id: 'four-roses-master', bottle_slugs: [] },
  { slug: 'old-forester', name: sv('Old Forester Distillery', 'verified', 'verified'), kind: 'legacy_brand', category: 'bourbon', headquarters: sv('Louisville, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Brown-Forman', 'commonly_reported', 'editorial'), mash_bill_slugs: ['old-forester-traditional'], terroir_slug: 'old-forester-terroir', bottle_slugs: [] },
  { slug: 'woodford-reserve', name: sv('Woodford Reserve Distillery', 'verified', 'verified'), kind: 'distiller', category: 'bourbon', headquarters: sv('Versailles, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Brown-Forman', 'commonly_reported', 'editorial'), dsp_code: sv('DSP-KY-112', 'commonly_reported', 'editorial'), mash_bill_slugs: ['woodford-traditional'], terroir_slug: 'woodford-terroir', bottle_slugs: [] },
  { slug: 'barton-1792', name: sv('Barton 1792 Distillery', 'verified', 'verified'), kind: 'distiller', category: 'bourbon', headquarters: sv('Bardstown, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Sazerac Company', 'commonly_reported', 'editorial'), dsp_code: sv('DSP-KY-14', 'commonly_reported', 'editorial'), mash_bill_slugs: ['barton-high-rye'], terroir_slug: 'barton-terroir', bottle_slugs: [] },
  { slug: 'michters', name: sv("Michter's Distillery", 'verified', 'verified'), kind: 'distiller', category: 'bourbon', headquarters: sv('Louisville, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Chatham Imports (private)', 'commonly_reported', 'editorial'), mash_bill_slugs: ['michters-traditional'], terroir_slug: 'michters-terroir', bottle_slugs: [] },
  { slug: 'new-riff', name: sv('New Riff Distilling', 'verified', 'verified'), kind: 'craft_distiller', category: 'bourbon', headquarters: sv('Newport, Kentucky', 'commonly_reported', 'editorial'), parent_company: sv('Independent', 'commonly_reported', 'editorial'), dsp_code: sv('DSP-KY-200', 'commonly_reported', 'editorial'), mash_bill_slugs: ['new-riff-high-rye'], terroir_slug: 'new-riff-terroir', bottle_slugs: [] },
];

/** Comparison sets — graph seeds, not reviews */
export const BOTTLE_COMPARISON_SETS: Record<string, string[]> = {
  'wild-turkey-101': ['buffalo-trace', 'knob-creek-9', '1792-small-batch'],
  'buffalo-trace': ['wild-turkey-101', 'eagle-rare', 'four-roses-yellow'],
  'makers-mark': ['larceny', 'weller-special-reserve'],
  'four-roses-yellow': ['buffalo-trace', 'wild-turkey-101'],
  'eagle-rare': ['buffalo-trace', 'russells-reserve-10'],
  'old-forester-1920': ['bookers', 'wild-turkey-101'],
  'weller-special-reserve': ['makers-mark', 'larceny'],
};

export const COLLECTION_PATHS: Record<string, string[]> = {
  'wild-turkey-101': ['value-daily-proof-ladder', 'high-rye-starter'],
  'buffalo-trace': ['gateway-bourbon', 'buffalo-trace-universe'],
  'makers-mark': ['wheated-comparison-flight'],
  'evan-williams-black': ['under-twenty-starter'],
};
