import type { MashBillRecord, TerroirRecord } from '../types';
import { sv, unknownField, unknownGrain } from '../sources/citations';

/** Mash / grain / barrel layer — percentages only when disclosed; otherwise explicit unknown */
export const MASH_BILL_REGISTRY: MashBillRecord[] = [
  {
    slug: 'wild-turkey-high-rye',
    producer_slug: 'wild-turkey',
    label: 'Wild Turkey bourbon mash (high-rye style)',
    style: sv('high-rye', 'commonly_reported', 'editorial', undefined, 'Rye-forward profile widely reported; exact percentages not publicly disclosed'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    yeast: unknownField('Yeast strain not publicly disclosed'),
    water_source: unknownField('Limestone water commonly associated with Kentucky distilling — not bottle-specific disclosure'),
    barrel: sv('New charred American oak', 'commonly_reported', 'editorial'),
    warehouse: unknownField('Rickhouse details vary by warehouse location'),
    flavor_family: sv(['spice', 'caramel', 'oak'], 'editorial', 'editorial'),
  },
  {
    slug: 'buffalo-trace-mash-1',
    producer_slug: 'buffalo-trace',
    label: 'Buffalo Trace Mash Bill #1',
    style: sv('traditional', 'commonly_reported', 'editorial', undefined, 'Low-rye mash #1 commonly reported in trade literature; not an official percentage disclosure'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    yeast: unknownField(),
    water_source: unknownField(),
    barrel: sv('New charred American oak', 'commonly_reported', 'editorial'),
    warehouse: sv('Campus rickhouses — warehouse position affects flavor', 'commonly_reported', 'editorial'),
    flavor_family: sv(['vanilla', 'caramel', 'gentle_spice'], 'editorial', 'editorial'),
  },
  {
    slug: 'buffalo-trace-wheated',
    producer_slug: 'buffalo-trace',
    label: 'Buffalo Trace wheated mash (Weller line)',
    style: sv('wheated', 'commonly_reported', 'editorial'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak', 'commonly_reported', 'editorial'),
    flavor_family: sv(['soft_wheat', 'vanilla', 'honey'], 'editorial', 'editorial'),
  },
  {
    slug: 'makers-mark-wheated',
    producer_slug: 'makers-mark',
    label: "Maker's Mark wheated mash bill",
    style: sv('wheated', 'producer_disclosed', 'verified', undefined, 'Red winter wheat substitution publicly described on official materials'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    yeast: sv('Proprietary yeast — family culture referenced in official history', 'producer_disclosed', 'editorial'),
    water_source: sv('Limestone-filtered water from Loretto, KY site', 'producer_disclosed', 'editorial'),
    barrel: sv('New charred American oak — rotated barrel program', 'producer_disclosed', 'editorial'),
    flavor_family: sv(['soft_wheat', 'vanilla', 'caramel'], 'editorial', 'editorial'),
  },
  {
    slug: 'heaven-hill-traditional',
    producer_slug: 'heaven-hill',
    label: 'Heaven Hill traditional bourbon mash',
    style: sv('traditional', 'commonly_reported', 'editorial'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak', 'commonly_reported', 'editorial'),
    flavor_family: sv(['caramel', 'corn_sweetness'], 'editorial', 'editorial'),
  },
  {
    slug: 'heaven-hill-wheated',
    producer_slug: 'heaven-hill',
    label: 'Heaven Hill wheated mash (Larceny / wheated portfolio)',
    style: sv('wheated', 'commonly_reported', 'editorial'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak', 'commonly_reported', 'editorial'),
    flavor_family: sv(['soft_wheat', 'honey'], 'editorial', 'editorial'),
  },
  {
    slug: 'jim-beam-traditional',
    producer_slug: 'jim-beam',
    label: 'Jim Beam family mash bill',
    style: sv('traditional', 'commonly_reported', 'editorial'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak', 'commonly_reported', 'editorial'),
    flavor_family: sv(['vanilla', 'oak', 'peanut_fudge'], 'editorial', 'editorial'),
  },
  {
    slug: 'four-roses-obsq-style',
    producer_slug: 'four-roses',
    label: 'Four Roses OBSQ-style profile (Yellow Label class)',
    style: sv('high-rye', 'commonly_reported', 'editorial', undefined, 'Four Roses uses multiple mash bills + yeast codes; Yellow Label is a blend'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    yeast: sv('Multiple yeast strains — five yeast codes publicly documented by Four Roses', 'producer_disclosed', 'editorial'),
    barrel: sv('New charred American oak', 'commonly_reported', 'editorial'),
    flavor_family: sv(['floral', 'fruit', 'spice'], 'editorial', 'editorial'),
  },
  {
    slug: 'four-roses-single-barrel',
    producer_slug: 'four-roses',
    label: 'Four Roses Single Barrel (recipe varies by barrel)',
    style: sv('high-rye', 'commonly_reported', 'editorial'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak — single barrel selection', 'commonly_reported', 'editorial'),
    flavor_family: sv(['spice', 'fruit'], 'editorial', 'editorial'),
  },
  {
    slug: 'four-roses-sourced-high-rye',
    producer_slug: 'four-roses',
    label: 'Four Roses distilled — Bulleit label (sourced)',
    style: sv('high-rye', 'commonly_reported', 'editorial', undefined, 'Bulleit bourbon historically associated with Four Roses sourcing — verify current contract on label'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak', 'commonly_reported', 'editorial'),
    flavor_family: sv(['spice', 'citrus'], 'editorial', 'editorial'),
  },
  {
    slug: 'old-forester-traditional',
    producer_slug: 'old-forester',
    label: 'Old Forester mash bill',
    style: sv('traditional', 'commonly_reported', 'editorial'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak', 'commonly_reported', 'editorial'),
    flavor_family: sv(['banana', 'caramel', 'spice'], 'editorial', 'editorial'),
  },
  {
    slug: 'woodford-traditional',
    producer_slug: 'woodford-reserve',
    label: 'Woodford Reserve mash bill',
    style: sv('traditional', 'commonly_reported', 'editorial'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak — pot still + column distillation', 'commonly_reported', 'editorial'),
    flavor_family: sv(['dried_fruit', 'oak', 'chocolate'], 'editorial', 'editorial'),
  },
  {
    slug: 'barton-high-rye',
    producer_slug: 'barton-1792',
    label: '1792 / Barton high-rye style mash',
    style: sv('high-rye', 'commonly_reported', 'editorial'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak', 'commonly_reported', 'editorial'),
    flavor_family: sv(['spice', 'caramel'], 'editorial', 'editorial'),
  },
  {
    slug: 'michters-traditional',
    producer_slug: 'michters',
    label: "Michter's bourbon mash",
    style: sv('traditional', 'commonly_reported', 'editorial'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak — barrel entry proof emphasized in brand materials', 'commonly_reported', 'editorial'),
    flavor_family: sv(['silky', 'vanilla', 'oak'], 'editorial', 'editorial'),
  },
  {
    slug: 'new-riff-high-rye',
    producer_slug: 'new-riff',
    label: 'New Riff bourbon mash',
    style: sv('high-rye', 'producer_disclosed', 'editorial', undefined, 'Rye-forward craft mash publicly described; non-chill filtered'),
    composition: { corn_pct: unknownGrain(), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: sv('New charred American oak', 'producer_disclosed', 'editorial'),
    flavor_family: sv(['spice', 'fruit', 'full_body'], 'editorial', 'editorial'),
  },
  {
    slug: 'orphan-barrel-unknown',
    producer_slug: 'jim-beam',
    label: 'Orphan Barrel program (NDP — mash unknown per release)',
    style: sv('unknown', 'unknown', 'editorial', undefined, 'Each Orphan Barrel release may differ — verify individual bottle disclosures'),
    composition: { corn_pct: unknownGrain('NDP release — mash bill not disclosed on all releases'), rye_pct: unknownGrain(), wheat_pct: unknownGrain(), barley_pct: unknownGrain() },
    barrel: unknownField('Varies by orphan barrel release'),
    flavor_family: sv(['oak', 'age'], 'editorial', 'editorial'),
  },
];

export const TERROIR_REGISTRY: TerroirRecord[] = [
  { slug: 'wild-turkey-terroir', producer_slug: 'wild-turkey', grain_source: unknownField('Grain source: Not publicly disclosed'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'not_disclosed' },
  { slug: 'buffalo-trace-terroir', producer_slug: 'buffalo-trace', grain_source: unknownField('Grain source: Not publicly disclosed at single-farm level'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'low' },
  { slug: 'makers-mark-terroir', producer_slug: 'makers-mark', grain_source: sv('Red winter wheat publicly emphasized; corn and barley sourcing not farm-mapped', 'producer_disclosed', 'editorial'), growing_region: unknownField('Growing region: Not publicly disclosed at field level'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'low' },
  { slug: 'new-riff-terroir', producer_slug: 'new-riff', grain_source: sv('Local Kentucky sourcing referenced in craft materials — verify current disclosures', 'commonly_reported', 'editorial'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'low' },
  { slug: 'heaven-hill-terroir', producer_slug: 'heaven-hill', grain_source: unknownField('Grain source: Not publicly disclosed'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'not_disclosed' },
  { slug: 'jim-beam-terroir', producer_slug: 'jim-beam', grain_source: unknownField('Grain source: Not publicly disclosed'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'not_disclosed' },
  { slug: 'four-roses-terroir', producer_slug: 'four-roses', grain_source: unknownField('Grain source: Not publicly disclosed'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'not_disclosed' },
  { slug: 'old-forester-terroir', producer_slug: 'old-forester', grain_source: unknownField('Grain source: Not publicly disclosed'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'not_disclosed' },
  { slug: 'woodford-terroir', producer_slug: 'woodford-reserve', grain_source: unknownField('Grain source: Not publicly disclosed'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'not_disclosed' },
  { slug: 'barton-terroir', producer_slug: 'barton-1792', grain_source: unknownField('Grain source: Not publicly disclosed'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'not_disclosed' },
  { slug: 'michters-terroir', producer_slug: 'michters', grain_source: unknownField('Grain source: Not publicly disclosed'), soil_influence: unknownField('Soil influence: Not producer-disclosed'), terroir_confidence: 'not_disclosed' },
];
