/** BBQ World meta — generated by @foundry/world-factory (PASS-024) */

export const BBQ_PLAYGROUND_LABS = [
  { slug: 'fire-lab', title: 'Fire Management Lab', description: 'Practice fire management lab — unlocks at academy level 2.', unlockLevel: 2 },
];

export const BBQ_PORTFOLIO_SECTIONS = [
  { slug: 'cooks', title: 'Cook Logs', description: 'Temps and outcomes' },
];

export const BBQ_PARENT_VIEW = {
  headline: 'Why BBQ matters for your child',
  oneLiner: 'Your child learns patience, hosting, and real cooking skills through smokes and backyard experiences.',
  sections: [
    { title: 'Why this matters now', body: 'Your child learns patience, hosting, and real cooking skills through smokes and backyard experiences.' },
    { title: 'Skills that transfer', body: 'Create Experiences — Become a Pitmaster. Real missions, not worksheets.' },
    { title: 'What your child is building', body: 'Five missions culminating in become a pitmaster — documented in My BBQ Journal.' },
    { title: 'How progress is measured', body: 'Evidence documents · Reflections · Portfolio artifacts — not test scores.' },
  ],
};

export const BBQ_CAREERS = [
  { title: 'Competition Pitmaster', connection: 'Travel the BBQ circuit.' },
];

export const BBQ_GLOSSARY = [
  { term: 'Low and slow', definition: 'Cooking at low temperature for many hours.' },
];
