/** Bourbon World meta — generated by @foundry/world-factory (PASS-024) */

export const BOURBON_PLAYGROUND_LABS = [
  { slug: 'tasting-lab', title: 'Tasting Lab', description: 'Practice tasting lab — unlocks at academy level 2.', unlockLevel: 2 },
  { slug: 'pairing-lab', title: 'Food Pairing Lab', description: 'Practice food pairing lab — unlocks at academy level 3.', unlockLevel: 3 },
];

export const BOURBON_PORTFOLIO_SECTIONS = [
  { slug: 'tastings', title: 'Tastings', description: 'Notes from every pour' },
  { slug: 'shelf', title: 'My Shelf', description: 'Collection photos and philosophy' },
];

export const BOURBON_PARENT_VIEW = {
  headline: 'Why Bourbon matters for your child',
  oneLiner: 'Your child learns to appreciate craft, host tastings, and build a real collection — not just consume.',
  sections: [
    { title: 'Why this matters now', body: 'Your child learns to appreciate craft, host tastings, and build a real collection — not just consume.' },
    { title: 'Skills that transfer', body: 'Appreciate Craft — Become a Bourbon Steward. Real missions, not worksheets.' },
    { title: 'What your child is building', body: 'Five missions culminating in become a bourbon steward — documented in My Bourbon Journey.' },
    { title: 'How progress is measured', body: 'Evidence documents · Reflections · Portfolio artifacts — not test scores.' },
  ],
};

export const BOURBON_CAREERS = [
  { title: 'Brand Ambassador', connection: 'Represent distilleries and educate consumers.' },
  { title: 'Bar Program Director', connection: 'Curate spirits programs for venues.' },
];

export const BOURBON_GLOSSARY = [
  { term: 'Mash bill', definition: 'The grain recipe used to make bourbon.' },
  { term: 'Proof', definition: 'Alcohol content — twice the ABV percentage.' },
];
