/** Civic Engagement World meta — generated by @foundry/world-factory (PASS-024) */

export const CIVIC_ENGAGEMENT_PLAYGROUND_LABS = [
  { slug: 'ballot-lab', title: 'Ballot Research Lab', description: 'Practice ballot research lab — unlocks at academy level 1.', unlockLevel: 1 },
];

export const CIVIC_ENGAGEMENT_PORTFOLIO_SECTIONS = [
  { slug: 'actions', title: 'Civic Actions', description: 'Meetings and volunteer hours' },
];

export const CIVIC_ENGAGEMENT_PARENT_VIEW = {
  headline: 'Why Civic Engagement matters for your child',
  oneLiner: 'Your child learns to research, participate, and lead locally — citizenship through action, not worksheets.',
  sections: [
    { title: 'Why this matters now', body: 'Your child learns to research, participate, and lead locally — citizenship through action, not worksheets.' },
    { title: 'Skills that transfer', body: 'Improve Your Community — Become an Informed Citizen. Real missions, not worksheets.' },
    { title: 'What your child is building', body: 'Five missions culminating in become an informed citizen — documented in My Civic Portfolio.' },
    { title: 'How progress is measured', body: 'Evidence documents · Reflections · Portfolio artifacts — not test scores.' },
  ],
};

export const CIVIC_ENGAGEMENT_CAREERS = [
  { title: 'Community Organizer', connection: 'Build coalitions around local issues.' },
];

export const CIVIC_ENGAGEMENT_GLOSSARY = [
  { term: 'Precinct', definition: 'Your local voting district.' },
];
