/** Poker World meta — generated by @foundry/world-factory (PASS-024) */

export const POKER_PLAYGROUND_LABS = [
  { slug: 'hand-review-lab', title: 'Hand Review Lab', description: 'Practice hand review lab — unlocks at academy level 2.', unlockLevel: 2 },
];

export const POKER_PORTFOLIO_SECTIONS = [
  { slug: 'sessions', title: 'Session Logs', description: 'Bankroll notes' },
];

export const POKER_PARENT_VIEW = {
  headline: 'Why Poker matters for your child',
  oneLiner: 'Your child learns decision-making under uncertainty and bankroll discipline — transferable life skills.',
  sections: [
    { title: 'Why this matters now', body: 'Your child learns decision-making under uncertainty and bankroll discipline — transferable life skills.' },
    { title: 'Skills that transfer', body: 'Strategic Thinking — Become a Strategic Player. Real missions, not worksheets.' },
    { title: 'What your child is building', body: 'Five missions culminating in become a strategic player — documented in My Poker Journey.' },
    { title: 'How progress is measured', body: 'Evidence documents · Reflections · Portfolio artifacts — not test scores.' },
  ],
};

export const POKER_CAREERS = [
  { title: 'Poker Coach', connection: 'Teach decision-making and hand review.' },
];

export const POKER_GLOSSARY = [
  { term: 'Bankroll', definition: 'Dedicated money for poker — separate from life expenses.' },
];
