import type { SeedWorldBundle } from './types';

const d = (title: string, body: string, author: string) => ({ title, body, author });
const s = (title: string, body: string, author: string) => ({ title, body, author });
const w = (theme: string, prompt: string) => ({ theme, prompt });

export const AI_BUILDER_SEED: SeedWorldBundle = {
  world_slug: 'ai-builder',
  mentor: {
    display_name: 'Jordan · AI Guide',
    bio: 'Built automations for three startups. Helps newcomers ship their first workflow in week one.',
    help_count: 47,
    recognition: 'Foundry AI Lab founding guide — 40+ members mentored',
  },
  members: [
    { display_name: 'Maya', role: 'member', help_count: 8 },
    { display_name: 'Dev', role: 'member', help_count: 5 },
    { display_name: 'Priya', role: 'member', help_count: 12 },
    { display_name: 'Alex', role: 'member', help_count: 3 },
  ],
  discussions: [
    d('Best AI tool you discovered this week?', 'I finally tried Claude for long documents — the context window changed how I research for school projects. What tool surprised you recently?', 'Maya'),
    d('What was your first successful automation?', 'Mine was auto-sorting email labels for club announcements. Took 20 minutes to set up, saves me an hour a week.', 'Dev'),
    d('What project should every beginner build?', 'Homework assistant with a strict system prompt. Forces you to learn prompting, guardrails, and iteration.', 'Jordan · AI Guide'),
    d('How do you avoid AI hallucinations on facts?', 'I always ask for sources and verify one claim manually. RAG over my own notes helped a lot for history.', 'Priya'),
    d('Favorite prompt pattern for beginners?', 'Role + task + format + example. Four lines, repeatable across subjects.', 'Alex'),
    d('When did AI click for you personally?', 'When I used it to explain calculus step-by-step instead of giving answers. That was the shift.', 'Maya'),
    d('Build vs buy for school projects?', 'Build small custom tools — you learn more than wrapping a generic chat.', 'Dev'),
    d('How much time do you spend reviewing AI output?', 'About 1:3 — one minute review per three minutes generation. Non-negotiable.', 'Jordan · AI Guide'),
    d('What would you put in a portfolio on day 1?', 'Screenshot of homework assistant + reflection on what you changed after testing.', 'Priya'),
    d('Agents vs simple chat — when to upgrade?', 'When you repeat the same 5-step workflow twice. That is agent territory.', 'Alex'),
    d('Biggest mistake new builders make?', 'Trying to automate everything before one workflow works reliably.', 'Maya'),
    d('How do you test prompts systematically?', 'Keep a spreadsheet: prompt version, input, output quality 1-5.', 'Dev'),
    d('What ethics rule do you follow?', 'Never submit AI output without understanding it. Especially for graded work.', 'Jordan · AI Guide'),
    d('Tools for voice or image — worth it early?', 'Voice notes → summary is underrated for reflection missions.', 'Priya'),
    d('How do you explain AI to parents?', 'Calculator for language — useful, not a replacement for thinking.', 'Alex'),
    d('First API you wired up?', 'Weather + email draft for event planning. Tiny win, huge confidence boost.', 'Maya'),
    d('What mission felt hardest?', 'Personal AI team — orchestration is real work. Worth it.', 'Dev'),
    d('Share a failed automation', 'Tried auto-reply to everything — missed a urgent teacher email. Added human review step.', 'Priya'),
    d('Best free resource for learners?', 'Provider docs + Foundry glossary. Skip random YouTube rabbit holes at first.', 'Jordan · AI Guide'),
    d('How do you name your projects?', 'Problem-first: homework-assistant, not cool-ai-thing-v2.', 'Alex'),
    d('Multimodal projects that worked?', 'Photo of math problem → step breakdown. Game changer for visual learners.', 'Maya'),
    d('When to use temperature settings?', 'Low for code and facts, higher for brainstorming names and hooks.', 'Dev'),
    d('What do you wish you knew on day 1?', 'Start with one class, one workflow. Depth beats breadth.', 'Priya'),
    d('Who do you ask when stuck?', 'This community — post your prompt and one bad output. Faster than guessing.', 'Alex'),
    d('What are you building next?', 'Research agent for science fair — citations are the hard part.', 'Maya'),
  ],
  showcases: [
    s('Homework Assistant', 'System prompt: patient tutor, no final answers without steps. Tested on algebra and biology — screenshot in portfolio.', 'Maya'),
    s('Club Email Sorter', 'Zapier + AI labels for robotics team announcements. Parents love the digest on Sundays.', 'Dev'),
    s('Research Brief Agent', 'Uploads 3 PDFs, outputs one-page brief with bullet citations. Used for civics crossover project.', 'Priya'),
    s('Study Guide Generator', 'Pastes textbook chapter → practice quiz + flashcards. Shared with two classmates.', 'Alex'),
    s('Budget Text Parser', 'Texts receipts → categorizes spending. Built while doing FI missions in parallel.', 'Maya'),
    s('Presentation Outline Bot', 'Inputs topic + audience → 3-minute talk skeleton. Feeds public speaking missions.', 'Dev'),
    s('Code Explainer', 'Paste error screenshot → plain-English fix steps. Saved my web project.', 'Priya'),
    s('Personal Knowledge Base', 'Notion + embeddings for class notes. Semantic search actually works now.', 'Alex'),
    s('Website Landing Draft', 'Mission 4 output — one-page portfolio for AI projects with CTA to Foundry.', 'Jordan · AI Guide'),
    s('Family FAQ Bot', 'Answers recurring questions for parents about my science project. Silly but useful.', 'Maya'),
  ],
  weeklyChallenges: [
    w('Build one useful AI workflow', 'Share one AI workflow you built or improved this week — what problem does it solve?'),
    w('Prompt engineering drill', 'Post your best before/after prompt rewrite with quality score 1-5.'),
    w('Automation audit', 'List one repetitive task you automated — or one you should automate next.'),
    w('RAG experiment', 'Try search over your own notes. What worked? What failed?'),
    w('Ethics check', 'Share one guardrail you added to a project and why.'),
    w('Peer review week', 'Review two showcase posts — link your feedback comments.'),
    w('Multimodal mini', 'Use image or voice input in a project. Post screenshot or transcript snippet.'),
    w('Agent step map', 'Draw or list steps for a multi-step agent — even if not built yet.'),
    w('Portfolio polish', 'Update one portfolio artifact with reflection from mentor feedback.'),
    w('Teach back', 'Explain one AI concept to a beginner in 5 sentences.'),
    w('Failure post-mortem', 'Share a broken automation and what you fixed.'),
    w('Ship something small', 'One feature shipped this week — demo in showcase.'),
  ],
};

export const FI_SEED: SeedWorldBundle = {
  world_slug: 'financial-independence',
  mentor: {
    display_name: 'Sam · Financial Coach',
    bio: 'Paid off $24k student debt in 3 years. Runs monthly money reviews in the Circle.',
    help_count: 38,
    recognition: 'Wealth Builders Circle coach — budget systems specialist',
  },
  members: [
    { display_name: 'Riley', role: 'member', help_count: 6 },
    { display_name: 'Chris', role: 'member', help_count: 4 },
    { display_name: 'Jordan', role: 'member', help_count: 9 },
  ],
  discussions: [
    d('First money lesson you wish you learned earlier?', 'Compound interest before car payments. Would have changed my twenties.', 'Sam · Financial Coach'),
    d('How do you track spending without obsessing?', 'One category check per week — dining out only. Not every penny daily.', 'Riley'),
    d('Best free budgeting approach?', 'Spreadsheet with three buckets: needs, goals, fun. Boring works.', 'Chris'),
    d('When did saving click for you?', 'First $1,000 cushion — slept better immediately.', 'Jordan'),
    d('Investing before emergency fund?', 'I waited. Glad I did — car repair hit month two.', 'Riley'),
    d('How to talk money with partner?', 'Monthly 20-minute review, no blame language. Agenda helps.', 'Sam · Financial Coach'),
    d('Biggest budget surprise?', 'Subscriptions — found $47/month I forgot.', 'Chris'),
    d('Side income ideas for students?', 'Tutoring + flipping one skill. Small, repeatable.', 'Jordan'),
    d('Debt avalanche vs snowball?', 'Snowball for motivation, switched to avalanche later.', 'Riley'),
    d('How much emergency fund is enough?', 'Started at $500, then $1k, now one month expenses.', 'Chris'),
    d('First stock research mission tips?', 'Write bull case AND bear case — forces honesty.', 'Jordan'),
    d('Books vs action?', 'One book, then one budget. Action wins.', 'Sam · Financial Coach'),
    d('Allowance systems for teens?', 'Save/spend/give jars — still use the mental model at 22.', 'Riley'),
    d('Financial independence means what to you?', 'Options, not yachts. Choose work I care about.', 'Chris'),
    d('Mistake with credit cards?', 'Minimum payments — learned APR the hard way.', 'Jordan'),
    d('How do you celebrate wins?', 'Small dinner out under $30 — marked in budget.', 'Riley'),
    d('Index funds — when did you start?', 'After mission 3 research — paper traded first.', 'Chris'),
    d('Parent conversations about college cost?', 'Showed four-year projection spreadsheet. Real numbers help.', 'Jordan'),
    d('What app do you actually use?', 'Spreadsheet + one bank app. That is it.', 'Sam · Financial Coach'),
    d('Inflation and grocery planning?', 'Meal plan Sundays — 15% drop in impulse buys.', 'Riley'),
    d('Financial goals this year?', 'Fully fund Roth IRA + maintain $2k cushion.', 'Chris'),
    d('How FI connects to civic life?', 'Local budget meetings make more sense now.', 'Jordan'),
    d('Regret purchase that taught you?', 'Financed gadget — sold at loss, never again.', 'Riley'),
    d('Teaching kids about money?', 'Match savings for goals — instant engagement.', 'Chris'),
    d('Next mission you are attempting?', 'Analyze one stock with full write-up for portfolio.', 'Jordan'),
  ],
  showcases: [
    s('Budget Tracker', 'First-month budget: tracked every dollar, found $180 leak in delivery apps.', 'Riley'),
    s('$1,000 Cushion Milestone', 'Hit savings goal in 4 months — chart in portfolio with monthly notes.', 'Chris'),
    s('Stock Research: Index vs Single', 'Compared VTI vs one tech stock — risk table included.', 'Jordan'),
    s('Family Money Meeting Notes', 'Redacted spreadsheet shared with parents — college planning.', 'Riley'),
    s('Debt Paydown Tracker', 'Snowball method visual — two cards paid off.', 'Chris'),
    s('Side Hustle Ledger', 'Tutoring income vs time — $22/hr effective rate.', 'Jordan'),
    s('Monthly Money Review Template', 'Sam shared template — I filled month one reflections.', 'Sam · Financial Coach'),
    s('Emergency Fund Progress', '45% to one-month goal — automation from paycheck.', 'Riley'),
    s('Investment Policy One-Pager', 'Rules I follow before any buy — stops impulse trades.', 'Chris'),
    s('Net Worth Snapshot', 'First honest net worth calc — student loans included.', 'Jordan'),
  ],
  weeklyChallenges: [
    w('Save, earn, or invest challenge', 'Post one financial win this week — saved, earned, or invested.'),
    w('Spending audit', 'One category you cut or optimized — numbers optional.'),
    w('Budget honesty', 'Share one surprise from tracking expenses.'),
    w('Research one fund', 'Bullet bull and bear case for one investment.'),
    w('Emergency fund check', 'Update cushion progress — % or dollars.'),
    w('Subscription purge', 'List subscriptions you canceled or kept — and why.'),
    w('Side income log', 'One hour of extra income — what you did.'),
    w('Money conversation', 'One talk about finances you had — lesson learned.'),
    w('Portfolio reflection', 'Update FI portfolio with one new artifact.'),
    w('Debt or savings visual', 'Share chart or table — redact sensitive numbers.'),
    w('Teach one concept', 'Explain compound interest to a friend in 3 sentences.'),
    w('Monthly review prep', 'Three bullets for your next money review.'),
  ],
};

export const PS_SEED: SeedWorldBundle = {
  world_slug: 'public-speaking',
  mentor: {
    display_name: 'Elena · Speaking Coach',
    bio: 'TEDx speaker and debate coach. Specializes in first-talk nerves and story structure.',
    help_count: 52,
    recognition: 'Speaker Circle lead — 50+ first talks coached',
  },
  members: [
    { display_name: 'Taylor', role: 'member', help_count: 7 },
    { display_name: 'Marcus', role: 'member', help_count: 11 },
    { display_name: 'Aisha', role: 'member', help_count: 4 },
  ],
  discussions: [
    d('What was your biggest fear before your first talk?', 'Forgetting everything mid-sentence. Recording practice fixed 80% of that.', 'Taylor'),
    d('How do you calm nerves?', 'Box breathing 4-4-4-4 backstage. Sounds cliché, works.', 'Elena · Speaking Coach'),
    d('Hook examples that worked for you?', 'Started with a question the audience answered silently. Instant engagement.', 'Marcus'),
    d('Memorize vs notes?', 'Bullet cards only — full script made me sound robotic.', 'Aisha'),
    d('Biggest improvement from recording yourself?', 'Saw my pacing — rushed endings every time.', 'Taylor'),
    d('How long to prepare a 3-minute talk?', 'Three sessions: outline, draft, record-review. About 2 hours total.', 'Marcus'),
    d('Feedback that hurt but helped?', 'You swallow your ending — now I land the last line.', 'Aisha'),
    d('Story vs stats — what ratio?', 'One story, one number, one ask. Simple frame.', 'Elena · Speaking Coach'),
    d('Virtual vs in-person?', 'Virtual forced me to look at camera not faces — harder.', 'Taylor'),
    d('First audience you recommend?', 'Study group of three. Low stakes, real feedback.', 'Marcus'),
    d('What do you wear for confidence?', 'Outfit I wore for successful practice. Anchor ritual.', 'Aisha'),
    d('Handling Q&A anxiety?', 'Repeat question, pause, answer. Buys thinking time.', 'Taylor'),
    d('Best mission order for beginners?', 'First talk → record review → story that lands. Do not skip record.', 'Elena · Speaking Coach'),
    d('Voice warmups?', 'Hum scales in car before class presentations.', 'Marcus'),
    d('When did speaking feel fun?', 'When someone said my story changed their mind on volunteering.', 'Aisha'),
    d('Props — yes or no?', 'One prop max for 3-minute talks. More distracts.', 'Taylor'),
    d('How do you pick topics?', 'Something you argued about this week — passion shows.', 'Marcus'),
    d('Parent audience tips?', 'Slow down 20%. They want to hear you.', 'Aisha'),
    d('Biggest myth about public speaking?', 'That extroverts only win. Structure beats personality.', 'Elena · Speaking Coach'),
    d('Club vs class presentations?', 'Club feedback is kinder and deeper — join both.', 'Taylor'),
    d('Using humor safely?', 'Self-deprecating only — never punch down.', 'Marcus'),
    d('Post-talk ritual?', 'Write three things that worked before critiquing.', 'Aisha'),
    d('Connecting speaking to career?', 'Every interview is a 3-minute talk with Q&A.', 'Taylor'),
    d('Who gave you best peer review?', 'Marcus on my story arc — specific timestamps.', 'Aisha'),
    d('Next talk topic?', 'Why local libraries matter — civic crossover.', 'Marcus'),
  ],
  showcases: [
    s('3 Minute Speech — First Talk', 'Topic: learning from failure. Hook question + one story + clear ending.', 'Taylor'),
    s('Record Review Notes', 'Watched recording 3x — cut 40 seconds of filler words.', 'Marcus'),
    s('Story That Lands', 'Personal story about moving schools — lesson on empathy.', 'Aisha'),
    s('Club Election Speech', '2:45 timed — won treasurer role.', 'Taylor'),
    s('PechaKucha Style Slides', '6 slides, 20 seconds each — discipline builder.', 'Marcus'),
    s('Interview Intro Pitch', '60-second who I am — reused for internship.', 'Aisha'),
    s('Debate Rebuttal Practice', 'Structured counter-argument — timed rounds.', 'Elena · Speaking Coach'),
    s('Parent Night Talk', 'Explained my academy path — parents asked for slides.', 'Taylor'),
    s('Toastmasters Style Table Topics', 'Impromptu 2-minute on random prompt — recording linked in portfolio.', 'Marcus'),
    s('Reflection: Nerves vs Performance', 'Journal entry comparing fear rating to audience feedback.', 'Aisha'),
  ],
  weeklyChallenges: [
    w('3-minute talk prompt', 'Record or outline a 3-minute talk — share hook and one improvement.'),
    w('Hook workshop', 'Post three hook options for your next topic.'),
    w('Filler word audit', 'Count ums from one recording — goal for next week.'),
    w('Story spine', 'Setup → tension → resolution in 5 sentences.'),
    w('Peer review swap', 'Review two talks — timestamp one specific fix.'),
    w('Impromptu minute', '2-minute talk on random word — transcript only.'),
    w('Ending strong', 'Write last line three ways — pick best.'),
    w('Voice note practice', 'Audio practice clip — one thing you heard.'),
    w('Audience question', 'Anticipate hardest Q&A — draft answer.'),
    w('Visual aid limit', 'One slide or prop — describe why.'),
    w('Calm routine', 'Share pre-talk ritual that works.'),
    w('Portfolio update', 'Add reflection from latest mission sync.'),
  ],
};
