import type { SeedWorldBundle } from './types';

const d = (title: string, body: string, author: string) => ({ title, body, author });
const s = (title: string, body: string, author: string) => ({ title, body, author });
const w = (theme: string, prompt: string) => ({ theme, prompt });

export const BOURBON_SEED: SeedWorldBundle = {
  world_slug: 'bourbon',
  mentor: {
    display_name: 'Clay · Bourbon Steward',
    bio: 'Central Arkansas native. Hosts blind tastings and shelf curation workshops.',
    help_count: 41,
    recognition: 'Bourbon Society steward — guided 35+ first tastings',
  },
  members: [
    { display_name: 'Wes', role: 'member', help_count: 5 },
    { display_name: 'Nina', role: 'member', help_count: 7 },
    { display_name: 'Tom', role: 'member', help_count: 3 },
  ],
  discussions: [
    d('First bourbon that made you understand the hype?', 'Single barrel pick at a local shop — caramel hit different.', 'Wes'),
    d('Blind tasting tips for beginners?', 'Same proof range, hide labels, write notes before reveal.', 'Clay · Bourbon Steward'),
    d('How do you build a starter shelf?', 'One wheated, one high-rye, one proof point higher. Three bottles max.', 'Nina'),
    d('Nose vs palate — what clicked first?', 'Palate for me. Nose opens after ten tastings.', 'Tom'),
    d('Water — yes or no?', 'Few drops on high proof only. Changes more than I expected.', 'Wes'),
    d('Best food pairing you tried?', 'Dark chocolate with high-rye — not gimmicky.', 'Nina'),
    d('Distillery trip worth it?', 'Buffalo Trace tour — smell memory lasts months.', 'Clay · Bourbon Steward'),
    d('How to describe without pretension?', 'Plain words: vanilla, pepper, long finish. Skip theater.', 'Tom'),
    d('Budget blind night ideas?', 'Under $35 bottles — levels the playing field.', 'Wes'),
    d('Misconception you had?', 'Older always better. Some young bourbons crush.', 'Nina'),
    d('Favorite tasting note format?', 'Nose / palate / finish / guess / reveal.', 'Clay · Bourbon Steward'),
    d('How bourbon connects to place?', 'Kentucky trips + Arkansas bottle picks — story matters.', 'Tom'),
    d('First mission advice?', 'Homework-assistant level focus — one bottle, full notes.', 'Wes'),
    d('Sharing without gatekeeping?', 'Explain why you like it, not why they should pay more.', 'Nina'),
    d('Ice debate in your house?', 'Neat at tastings, one cube at home — both fine.', 'Tom'),
    d('Collecting vs drinking?', 'Drink window dates on shelf — no museum bottles.', 'Clay · Bourbon Steward'),
    d('Rye vs bourbon confusion?', '95% rye mashbill surprised me — read labels.', 'Wes'),
    d('Club night format?', 'Three blinds + one reveal dinner pairing.', 'Nina'),
    d('Gift bottle recommendations?', 'Small batch with story card you write yourself.', 'Tom'),
    d('What word did you learn this month?', 'Leather on palate — finally tasted it, not just read it.', 'Wes'),
    d('Shelf showcase themes?', 'High rye month — taught me more than random buys.', 'Nina'),
    d('Responsible tasting?', 'Spit cup at group nights — still learn aromas.', 'Clay · Bourbon Steward'),
    d('Bourbon and civic gatherings?', 'Town hall after — conversations flow easier. Weird but true.', 'Tom'),
    d('Next bottle on your list?', 'Local store pick — support Arkansas retailers.', 'Wes'),
    d('What makes Society different?', 'Structure without snobbery — notes template helps.', 'Nina'),
  ],
  showcases: [
    s('Blind Bourbon Tasting', 'Three under $40 — guessed wrong on middle, learned nose training.', 'Wes'),
    s('First Tasting Mission Notes', 'Mission 1 portfolio entry — nose/palate/finish template filled.', 'Nina'),
    s('Starter Shelf Photo', 'Three bottles with theme card: wheated, rye, classic.', 'Tom'),
    s('Distillery Field Notes', 'Kentucky weekend — three distilleries, one lesson each.', 'Clay · Bourbon Steward'),
    s('Compare Five Grid', 'Mission grid completed — proof correlation noted.', 'Wes'),
    s('Monthly Theme: High Rye', 'Four bottles compared — pepper scale drawn.', 'Nina'),
    s('Tasting with Parents', 'Intro flight — they preferred lower proof. Good data.', 'Tom'),
    s('Flavor Wheel Practice', 'Homemade wheel — mapped 12 tastings.', 'Wes'),
    s('Shelf Curator Write-up', 'Why each bottle earned its spot — not price flex.', 'Nina'),
    s('Blind Night Recap', 'Club night notes — two first-timers joined.', 'Clay · Bourbon Steward'),
  ],
  weeklyChallenges: [
    w('Blind tasting', 'Post blind tasting note: nose, palate, finish, guess before reveal.'),
    w('One new descriptor', 'Use one flavor word you never used before.'),
    w('Proof experiment', 'Same bottle neat vs few drops water — compare.'),
    w('Shelf photo story', 'One shelf photo + sentence per bottle why it stays.'),
    w('Local bottle hunt', 'Arkansas or regional pick — tasting notes.'),
    w('Food pairing test', 'One pairing attempt — honest rating.'),
    w('Compare two mashbills', 'Wheated vs rye side by side.'),
    w('Mission sync', 'Link mission portfolio reflection to community.'),
    w('Teach a friend', 'Guide someone through first structured tasting.'),
    w('Distillery research', 'One distillery history post — three facts.'),
    w('Budget blind', 'Under $35 blind — reveal and review.'),
    w('Year review', 'Best pour this quarter — what changed your palate.'),
  ],
};

export const BBQ_SEED: SeedWorldBundle = {
  world_slug: 'bbq',
  mentor: {
    display_name: 'Ray · Pitmaster Mentor',
    bio: 'Competition cook turned backyard teacher. Brisket stall whisperer.',
    help_count: 44,
    recognition: 'Pitmaster Collective founder — 30+ first cooks coached',
  },
  members: [
    { display_name: 'Lee', role: 'member', help_count: 6 },
    { display_name: 'Casey', role: 'member', help_count: 9 },
    { display_name: 'Dana', role: 'member', help_count: 4 },
  ],
  discussions: [
    d('First cut that taught you patience?', 'Pork butt — 10 hours taught me thermometers beat guessing.', 'Lee'),
    d('Stall panic stories?', 'Wrapped too early once — bark suffered. Wait it out now.', 'Ray · Pitmaster Mentor'),
    d('Wood choice in Arkansas?', 'Oak primary, cherry for color — local availability wins.', 'Casey'),
    d('Thermometer trust issues?', 'Two probes — grate temp and meat temp. Non-negotiable.', 'Dana'),
    d('Best beginner smoker?', 'Kettle with indirect setup before expensive gear.', 'Lee'),
    d('Rub vs sauce philosophy?', 'Rub on meat, sauce on plate — let smoke speak first.', 'Casey'),
    d('Cook log habit?', 'Every cook logged — patterns emerge after five cooks.', 'Ray · Pitmaster Mentor'),
    d('Backyard vs competition?', 'Backyard feeds people you love — different goal, same craft.', 'Dana'),
    d('Biggest mistake on brisket?', 'Trimmed too much fat first time — dry flat.', 'Lee'),
    d('Resting — how long?', 'Minimum one hour wrapped in cooler — game changer.', 'Casey'),
    d('Weather failures?', 'Wind killed my fire — learned wind blocks matter.', 'Dana'),
    d('Feeding a crowd math?', '1.5 lbs raw per person — still had leftovers.', 'Lee'),
    d('Spritz or not?', 'Apple cider spritz on pork — subtle, not mandatory.', 'Ray · Pitmaster Mentor'),
    d('Leftovers innovation?', 'Brisket tacos day two — sometimes better than day one.', 'Casey'),
    d('Sharing cook photos — what helps?', 'Timeline with temps, not just money shot.', 'Dana'),
    d('First mission pork butt tips?', 'Mission rub + log template — follow it exactly once.', 'Lee'),
    d('Community cookoff idea?', 'Monthly backyard — lowest stakes learning.', 'Casey'),
    d('Smoke ring myths?', 'Not required for good BBQ — flavor is required.', 'Ray · Pitmaster Mentor'),
    d('Cleaning ritual?', 'Hot burn after cook — discipline prevents off flavors.', 'Dana'),
    d('Pairing with bourbon?', 'Post-cook tasting — fat and smoke complement.', 'Lee'),
    d('Vegetarian at the cookout?', 'Smoked mac + grilled corn — inclusion matters.', 'Casey'),
    d('Winter smoking?', 'Insulation blanket on pellet — stable temps.', 'Dana'),
    d('What improved your bark?', 'Dry rub sit overnight — simple change.', 'Lee'),
    d('Next cook planned?', 'Brisket — applying stall lessons from Collective.', 'Casey'),
    d('Why log publicly?', 'Accountability + others learn from your mistakes.', 'Ray · Pitmaster Mentor'),
  ],
  showcases: [
    s('Brisket Cook Log', '14-hour cook — stall at 160, wrapped at 165, probe tender at 203.', 'Lee'),
    s('First Pork Butt Mission', 'Mission 1 complete — bark photo + hour-by-hour log.', 'Casey'),
    s('Backyard BBQ Spread', 'Feeding 12 — timeline and shopping list shared.', 'Dana'),
    s('Competition Turn-in Box', 'Practice box — appearance score notes from mentor.', 'Ray · Pitmaster Mentor'),
    s('Smoke Ring Progress', 'Three cooks compared — fuel and wood changes noted.', 'Lee'),
    s('Rub Recipe Card', 'House rub — paprika forward, less sugar than store bought.', 'Casey'),
    s('Failed Brisket Post-mortem', 'Dry flat autopsy — trim and wrap timing fixed.', 'Dana'),
    s('Pellet vs Charcoal Notes', 'Same cut two ways — flavor preference documented.', 'Lee'),
    s('Cookout Hosting Checklist', 'Prep timeline T-24 to serve — reused twice.', 'Casey'),
    s('Leftover Transformation', 'Brisket hash recipe — family favorite.', 'Dana'),
  ],
  weeklyChallenges: [
    w('Cook and post results', 'Share cook: meat, temps, stall, wrap, pull time, 1–10 rating.'),
    w('Thermometer trust', 'Log grate vs meat temp for one cook.'),
    w('Rub experiment', 'Change one rub ingredient — note result.'),
    w('Wood log', 'Wood type this week — flavor impression.'),
    w('Timeline photo series', 'Three photos across cook — not just final.'),
    w('Rest test', 'Compare rest times — texture notes.'),
    w('Side dish smoke', 'One non-meat item on smoker.'),
    w('Cook log template', 'Fill full template even on small cook.'),
    w('Peer review cook', 'Comment on two cook logs with one fix each.'),
    w('Weather note', 'How weather affected your cook.'),
    w('Feeding math', 'Portions planned vs actual — lesson learned.'),
    w('Mission link', 'Connect mission portfolio to showcase post.'),
  ],
};

export const POKER_SEED: SeedWorldBundle = {
  world_slug: 'poker',
  mentor: {
    display_name: 'Vince · Poker Mentor',
    bio: 'Focuses on decision quality over results. Runs weekly hand review threads.',
    help_count: 36,
    recognition: 'Strategic Thinking Society mentor — bankroll discipline advocate',
  },
  members: [
    { display_name: 'Kai', role: 'member', help_count: 8 },
    { display_name: 'Brooke', role: 'member', help_count: 5 },
    { display_name: 'Dan', role: 'member', help_count: 10 },
  ],
  discussions: [
    d('When did poker become strategy not luck?', 'Ten-hand review mission — saw patterns in my leaks.', 'Kai'),
    d('Bankroll rule you follow?', '20 buy-ins minimum for level I play — moved down once, saved money.', 'Vince · Poker Mentor'),
    d('Biggest leak beginners have?', 'Calling too wide on river — I still fight this.', 'Brooke'),
    d('Live vs online for learning?', 'Online volume for reps, live for reads — both teach.', 'Dan'),
    d('How to review a hand?', 'Street by street: range, size, decision, alternative.', 'Kai'),
    d('Tilt signals you notice?', 'Typing fast in chat — I stand up one orbit now.', 'Brooke'),
    d('First tournament lesson?', 'Survival early — stole blinds too much late.', 'Dan'),
    d('ICM moment you remember?', 'Folded trip on bubble — math hurt, bankroll thanked me.', 'Vince · Poker Mentor'),
    d('Study routine?', 'One hour reviews, one session play — ratio matters.', 'Kai'),
    d('Bluff story — good or bad?', 'Bluffed calling station — logged as leak not bad beat.', 'Brooke'),
    d('Home game etiquette?', 'Show one teaching hand after — grows the community.', 'Dan'),
    d('Tracking software worth it?', 'Spreadsheet enough for first 100 hours.', 'Kai'),
    d('Poker and life decisions?', 'Expected value thinking applied to college choice — seriously.', 'Brooke'),
    d('Hand reading framework?', 'Assign range preflop, narrow each street — write it down.', 'Vince · Poker Mentor'),
    d('Celebrating wins responsibly?', 'One buy-in off table rule — locks profit.', 'Dan'),
    d('Bad beat journal?', 'Write decision quality 1-5, ignore outcome that session.', 'Kai'),
    d('First mission bankroll tips?', 'Track every session — mission template is enough.', 'Brooke'),
    d('Study group format?', 'One hand per person per week — deep not wide.', 'Dan'),
    d('Position awareness click?', 'Button steals worksheet — opened my eyes.', 'Kai'),
    d('Mental game book or practice?', 'Practice — but one chapter on tilt helped.', 'Brooke'),
    d('Teaching a friend?', 'Start with positions and hand rankings only — patience.', 'Vince · Poker Mentor'),
    d('Online bankroll separation?', 'Separate account — never mix with bills.', 'Dan'),
    d('Most improved skill this month?', 'Fold equity estimation — still rough but better.', 'Kai'),
    d('Next review focus?', 'River bet sizing — posting hand Friday.', 'Brooke'),
    d('Why Society not just home game?', 'Structured review culture — accountability.', 'Dan'),
  ],
  showcases: [
    s('Poker Hand Analysis', 'AK on wet board — street-by-street with alternative line on turn.', 'Kai'),
    s('Bankroll Tracker — Month 1', 'Mission 1 spreadsheet — 12 sessions, trend line.', 'Brooke'),
    s('Ten Hand Review Summary', 'Top three leaks identified — calling river too wide.', 'Dan'),
    s('Tournament Log', 'First tournament — busted bubble, ICM note included.', 'Kai'),
    s('Final Table Decision', 'Push/fold chart applied — screenshot of math.', 'Vince · Poker Mentor'),
    s('Home Game Recap', 'Teaching night — one hand taught, feedback collected.', 'Brooke'),
    s('Session Graph', 'Online 500 hands — red line vs blue line lesson.', 'Dan'),
    s('Bluff Review', 'Marked bad bluff — opponent type misread documented.', 'Kai'),
    s('Study Plan Week', 'One hour ranges, one hour reviews — checklist.', 'Brooke'),
    s('Teach New Player Notes', 'Mission 5 draft — simplified positions handout.', 'Dan'),
  ],
  weeklyChallenges: [
    w('Analyze a hand', 'Post hand history with decisions each street — one line you would change.'),
    w('Bankroll check', 'Update session log — trend up or down?'),
    w('Leak hunt', 'One recurring mistake from last 5 sessions.'),
    w('Position focus', 'Play or review 10 hands from button — notes.'),
    w('River review', 'Three river decisions — quality score 1-5.'),
    w('Tilt log', 'One tilt moment — trigger and countermeasure.'),
    w('ICM or math', 'One calculation you ran — show work.'),
    w('Peer review', 'Review two hand posts — specific street feedback.'),
    w('Study block', 'One hour study — what you covered.'),
    w('Live vs online', 'One session reflection — environment comparison.'),
    w('Mission sync', 'Portfolio mission tied to strategy note.'),
    w('Teach back', 'Explain pot odds to beginner in 4 sentences.'),
  ],
};

export const CIVIC_SEED: SeedWorldBundle = {
  world_slug: 'civic-engagement',
  mentor: {
    display_name: 'Maria · Civic Mentor',
    bio: 'School board observer and precinct captain. Pairs new members through one election cycle.',
    help_count: 39,
    recognition: 'Civic Action Circle mentor — first-meeting escort program',
  },
  members: [
    { display_name: 'Jade', role: 'member', help_count: 6 },
    { display_name: 'Omar', role: 'member', help_count: 8 },
    { display_name: 'Hannah', role: 'member', help_count: 4 },
  ],
  discussions: [
    d('First local meeting you attended?', 'City council — public comment was intimidating but worth it.', 'Jade'),
    d('How to research a ballot without drowning?', 'Three issues max — Foundry ballot mission template helped.', 'Maria · Civic Mentor'),
    d('Volunteer shift that changed your view?', 'Park cleanup led to meeting parks director — connection matters.', 'Omar'),
    d('Talking politics with family?', 'Ask questions first — argue less, learn more.', 'Hannah'),
    d('Local news sources you trust?', 'Mix: city newsletter, one reporter, meeting minutes directly.', 'Jade'),
    d('First mission barrier?', 'Finding sample ballot — county site was buried. We should link guides.', 'Omar'),
    d('Student civic involvement ideas?', 'Register voters at school events — nonpartisan tables.', 'Maria · Civic Mentor'),
    d('Town hall etiquette?', 'Write comment beforehand — stay under time, stay specific.', 'Hannah'),
    d('Civic + other worlds?', 'Public speaking helped my comment delivery — crossover wins.', 'Jade'),
    d('Burnout from news?', 'One action per week rule — attend OR volunteer OR research, not all daily.', 'Omar'),
    d('Local issue you care about?', 'Sidewalk safety near school — started with one email to rep.', 'Hannah'),
    d('How to bring a friend?', 'Offer to go together first time — reduces fear.', 'Maria · Civic Mentor'),
    d('Documenting meetings?', 'Notes template: decision, vote count, next date.', 'Jade'),
    d('Misinformation you caught?', 'Shared viral post — verified false with primary source link.', 'Omar'),
    d('Project idea for beginners?', 'One-day park or food bank shift — tangible win.', 'Hannah'),
    d('School board vs city council?', 'Different budgets — learned which handles what.', 'Jade'),
    d('Precinct role curiosity?', 'Signed up to observe — training was welcoming.', 'Omar'),
    d('Reflection on Mission 1?', 'Ballot research took 90 min — now I vote confident.', 'Hannah'),
    d('Civic habit stack?', 'Sunday research, Monday email if needed — small rhythm.', 'Maria · Civic Mentor'),
    d('Leader you admire locally?', 'Council member who replies to emails — modeled that engagement.', 'Jade'),
    d('Youngest participant tip?', 'Your perspective is missing in rooms — bring it respectfully.', 'Omar'),
    d('Community project follow-through?', 'Assigned roles in group chat — simple accountability.', 'Hannah'),
    d('Next action this week?', 'Attending zoning meeting — land use affects neighborhood.', 'Jade'),
    d('Why Circle not just voting?', 'Habit of participation between elections — that is the point.', 'Maria · Civic Mentor'),
    d('Cross-world civic use of AI?', 'Summarize long ballot measures — verify still required.', 'Omar'),
  ],
  showcases: [
    s('City Council Meeting Reflection', 'First meeting notes — three decisions tracked, one comment delivered.', 'Jade'),
    s('Research Your Ballot — Mission 1', 'Sample ballot annotated — pro/con on two measures.', 'Omar'),
    s('Volunteer Shift Log', 'Food bank 4 hours — reflection on supply chain local tie.', 'Hannah'),
    s('Community Project Plan', 'Neighborhood cleanup — roles, date, supply list.', 'Maria · Civic Mentor'),
    s('Public Comment Script', 'Two-minute comment drafted and timed — speaking crossover.', 'Jade'),
    s('Meeting Minutes Summary', 'Shared with neighbors — five bullet digest.', 'Omar'),
    s('Voter Registration Event', 'Registered 12 at school fair — process notes for next year.', 'Hannah'),
    s('Local Issue One-Pager', 'Sidewalk safety — photos, map, contact list.', 'Jade'),
    s('Ballot Measure Deep Dive', 'One measure only — sources linked, decision explained.', 'Omar'),
    s('Civic Conversation Guide', 'Ground rules for family dinner discussion — worked once!', 'Hannah'),
  ],
  weeklyChallenges: [
    w('Attend · Learn · Do', 'Report one civic action: attended, learned, or did locally.'),
    w('Ballot bite', 'Research one item on an upcoming ballot — three bullets.'),
    w('Meeting minutes', 'Read or attend one public meeting — one takeaway.'),
    w('Volunteer hour', 'One volunteer shift or micro-action — reflection post.'),
    w('Local email', 'One email to rep — redact personal info, share topic only.'),
    w('Neighbor share', 'Share one civic resource with someone who needed it.'),
    w('Primary source', 'Fact-check one claim — link primary doc.'),
    w('Project step', 'One step on community project — photo or note.'),
    w('Comment practice', 'Draft 2-minute public comment — timed.'),
    w('Cross-world link', 'Connect civic action to another Foundry world — how?'),
    w('Habit check', 'Which civic habit stuck this month?'),
    w('Invite someone', 'Bring one person to next action — what you will do together.'),
  ],
};
