import type { AtlasSeed } from './types';

/** 100+ Bourbon Atlas seeds — expanded to full entries via buildAtlasEntry */
export const ATLAS_SEEDS: AtlasSeed[] = [
  // ─── Priority production & grain ─────────────────────────────
  { slug: 'mash-bill', title: 'Mash bill', category: 'grain', shortDefinition: 'The grain recipe for whiskey — bourbon requires at least 51% corn.', examples: ['Buffalo Trace low-rye', 'Four Roses multiple recipes', 'Maker\'s Mark wheated'], relatedSlugs: ['corn', 'rye', 'wheat', 'wheated-bourbon', 'high-rye-bourbon'], cousinIdeas: ['Recipe design', 'Flavor architecture'] },
  { slug: 'corn', title: 'Corn', category: 'grain', shortDefinition: 'Primary grain in bourbon — minimum 51% by law, often 70–80% in practice.', examples: ['Standard bourbon mash', 'Mellow Corn (corn whiskey)', 'High-corn craft recipes'], relatedSlugs: ['mash-bill', 'rye', 'wheat'], cousinIdeas: ['Sweetness', 'Body'] },
  { slug: 'rye', title: 'Rye', category: 'grain', shortDefinition: 'Spice grain in bourbon mash — higher rye means more pepper and mint.', examples: ['High-rye Four Roses', 'Old Forester', 'Rye whiskey (51%+ rye)'], relatedSlugs: ['high-rye-bourbon', 'mash-bill', 'rye-whiskey'], cousinIdeas: ['Spice', 'Baking notes'] },
  { slug: 'wheat', title: 'Wheat', category: 'grain', shortDefinition: 'Soft grain replacing rye in wheated bourbon — bread and honey notes.', examples: ['Maker\'s Mark', 'Weller line', 'Larceny'], relatedSlugs: ['wheated-bourbon', 'mash-bill'], cousinIdeas: ['Softness', 'Approachability'] },
  { slug: 'malted-barley', title: 'Malted barley', category: 'grain', shortDefinition: 'Enzyme-rich grain that helps convert starches to fermentable sugars.', examples: ['Typical 5–15% in bourbon mash', 'Single malt comparison'], relatedSlugs: ['mash-bill', 'fermentation'], cousinIdeas: ['Enzymes', 'Nutty notes'] },
  { slug: 'sour-mash', title: 'Sour mash', category: 'production', shortDefinition: 'Adding spent mash from a prior batch to new fermentation for pH control.', examples: ['Jim Beam process', 'Most Kentucky majors'], relatedSlugs: ['fermentation', 'sweet-mash', 'yeast-strain'], cousinIdeas: ['Consistency', 'Backset'] },
  { slug: 'sweet-mash', title: 'Sweet mash', category: 'production', shortDefinition: 'Fermentation without backset — fresh yeast and grain only.', examples: ['Craft distillers highlighting funk', 'Experimental batches'], relatedSlugs: ['sour-mash', 'fermentation'], cousinIdeas: ['Bold ferment character'] },
  { slug: 'fermentation', title: 'Fermentation', category: 'production', shortDefinition: 'Yeast converting grain sugars to alcohol before distillation.', examples: ['48-hour vs 72-hour ferments', 'Open vs closed fermenters'], relatedSlugs: ['yeast-strain', 'sour-mash', 'esters'], cousinIdeas: ['Beer stage', 'Fruity esters'] },
  { slug: 'yeast-strain', title: 'Yeast strain', category: 'production', shortDefinition: 'Specific yeast culture — house strains are closely guarded flavor signatures.', examples: ['Heaven Hill heritage yeast', 'Wild Turkey yeast line'], relatedSlugs: ['fermentation', 'esters', 'congeners'], cousinIdeas: ['House character'] },
  { slug: 'distillate', title: 'Distillate', category: 'production', shortDefinition: 'Spirit off the still before barreling — also called new make.', examples: ['White dog off the doubler', 'Pre-barrel spirit'], relatedSlugs: ['new-make', 'white-dog', 'hearts-cut'], cousinIdeas: ['New make spirit'] },
  { slug: 'new-make', title: 'New make', category: 'production', shortDefinition: 'Unaged whiskey straight from the still — clear, grain-forward, hot.', examples: ['Distillery new make tastings', 'White dog samples'], relatedSlugs: ['white-dog', 'distillate', 'entry-proof'], cousinIdeas: ['White whiskey'] },
  { slug: 'white-dog', title: 'White dog', category: 'production', shortDefinition: 'Informal term for unaged distillate — “dog” from rough early runs.', examples: ['Moonshine heritage', 'Legal new make at tours'], relatedSlugs: ['new-make', 'distillate'], cousinIdeas: ['Unaged spirit'] },
  { slug: 'column-still', title: 'Column still', category: 'production', shortDefinition: 'Continuous distillation — efficient high-proof spirit for scale.', examples: ['Major Kentucky plants', 'Hybrid systems'], relatedSlugs: ['pot-still', 'doubler', 'hearts-cut'], cousinIdeas: ['Continuous distillation'] },
  { slug: 'pot-still', title: 'Pot still', category: 'production', shortDefinition: 'Batch copper still — often richer, heavier spirit.', examples: ['Woodford Reserve heritage', 'Pot still components'], relatedSlugs: ['column-still', 'doubler'], cousinIdeas: ['Batch distillation'] },
  { slug: 'doubler', title: 'Doubler', category: 'production', shortDefinition: 'Secondary pot still refining low-wine into higher-proof spirit.', examples: ['Traditional bourbon doublers', 'Thumper alternative'], relatedSlugs: ['thumper', 'column-still', 'pot-still'], cousinIdeas: ['Second distillation'] },
  { slug: 'thumper', title: 'Thumper', category: 'production', shortDefinition: 'Steam-heated chamber re-distilling low wines — alternative to doubler.', examples: ['Older craft setups', 'Historical configurations'], relatedSlugs: ['doubler', 'column-still'], cousinIdeas: ['Reflux', 'Steam distillation'] },
  { slug: 'hearts-cut', title: 'Hearts cut', category: 'production', shortDefinition: 'Middle distillation fraction kept for whiskey — between heads and tails.', examples: ['Master distiller cut points', 'House style definition'], relatedSlugs: ['heads', 'tails', 'congeners'], cousinIdeas: ['Cut points'] },
  { slug: 'heads', title: 'Heads', category: 'production', shortDefinition: 'First volatile fraction — solvent-like, discarded or recycled.', examples: ['Foreshots', 'Early still run'], relatedSlugs: ['hearts-cut', 'tails'], cousinIdeas: ['Foreshots'] },
  { slug: 'tails', title: 'Tails', category: 'production', shortDefinition: 'Final heavy fraction — oily, often soapy if included in hearts.', examples: ['Late still run', 'Feints'], relatedSlugs: ['hearts-cut', 'heads'], cousinIdeas: ['Feints'] },
  { slug: 'congeners', title: 'Congeners', category: 'chemistry', shortDefinition: 'Flavor compounds beyond ethanol — esters, aldehydes, fusel oils.', examples: ['Rich mouthfeel pours', 'Heavy vs light spirit'], relatedSlugs: ['esters', 'ethanol', 'hearts-cut'], cousinIdeas: ['Flavor compounds'] },

  // ─── Barrel & aging ──────────────────────────────────────────
  { slug: 'rickhouse', title: 'Rickhouse', category: 'barrel', shortDefinition: 'Multi-story warehouse where bourbon barrels age on racks.', examples: ['Buffalo Trace rickhouses', 'Heaven Hill campus'], relatedSlugs: ['warehouse-floor', 'rickhouse-position', 'heat-cycling', 'angels-share'], cousinIdeas: ['Warehouse', 'Rick storage'], geography: 'Kentucky and Tennessee dominate iconic rickhouse imagery, though barrels age in warehouses nationwide.' },
  { slug: 'warehouse-floor', title: 'Warehouse floor', category: 'barrel', shortDefinition: 'Vertical position affects temperature swing and aging speed.', examples: ['Top floor hot barrels', 'Ground floor cooler aging'], relatedSlugs: ['rickhouse', 'rickhouse-position', 'heat-cycling'], cousinIdeas: ['Vertical aging'] },
  { slug: 'rickhouse-position', title: 'Rickhouse position', category: 'barrel', shortDefinition: 'Where a barrel sits in the stack — upper ricks age faster.', examples: ['Top-rick barrel picks', 'Floor vs ceiling comparisons'], relatedSlugs: ['warehouse-floor', 'heat-cycling', 'barrel-proof'], cousinIdeas: ['Barrel location'] },
  { slug: 'heat-cycling', title: 'Heat cycling', category: 'barrel', shortDefinition: 'Temperature swings driving spirit in and out of wood pores.', examples: ['Kentucky summer expansion', 'Climate-controlled warehouses'], relatedSlugs: ['rickhouse', 'angels-share', 'warehouse-floor'], cousinIdeas: ['Seasonal aging'] },
  { slug: 'angels-share', title: 'Angel\'s share', category: 'barrel', shortDefinition: 'Whiskey lost to evaporation during aging — roughly 2–4% per year.', examples: ['12-year volume loss', 'Humidity effects'], relatedSlugs: ['rickhouse', 'age-statement', 'entry-proof'], cousinIdeas: ['Evaporation', 'Barrel loss'] },
  { slug: 'cooperage', title: 'Cooperage', category: 'barrel', shortDefinition: 'Barrel-making craft — staves, toast, char, assembly.', examples: ['Independent cooperages', 'Brown-Forman cooperage'], relatedSlugs: ['stave', 'toasting', 'char-level'], cousinIdeas: ['Barrel craft'] },
  { slug: 'stave', title: 'Stave', category: 'barrel', shortDefinition: 'Curved oak plank forming a barrel — grain direction matters.', examples: ['Air-seasoned staves', 'American white oak'], relatedSlugs: ['cooperage', 'toasting'], cousinIdeas: ['Oak planks'] },
  { slug: 'toasting', title: 'Toasting', category: 'barrel', shortDefinition: 'Heating staves before char — coconut, almond, deeper wood notes.', examples: ['Toast then char barrels', 'Winemaker toast levels'], relatedSlugs: ['char-level', 'cooperage'], cousinIdeas: ['Barrel toast'] },
  { slug: 'char-level', title: 'Char level', category: 'barrel', shortDefinition: 'Depth of burnt inner barrel surface — filters and flavors spirit.', examples: ['Level 3 char common', 'Alligator char craft'], relatedSlugs: ['toasting', 'new-charred-oak', 'cooperage'], cousinIdeas: ['Barrel char', 'Charring'] },
  { slug: 'new-charred-oak', title: 'New charred oak', category: 'barrel', shortDefinition: 'Legal bourbon requirement — virgin American oak, charred inside.', examples: ['One-use bourbon barrels', 'Export to scotch aging'], relatedSlugs: ['char-level', 'cooperage'], cousinIdeas: ['Virgin oak'] },
  { slug: 'entry-proof', title: 'Barrel entry proof', category: 'barrel', shortDefinition: 'Proof when new make enters the barrel — affects extraction intensity.', examples: ['125 proof entry common', 'Lower entry craft experiments'], relatedSlugs: ['barrel-proof', 'proofing-water', 'new-make'], cousinIdeas: ['Entry proof'] },
  { slug: 'dump-date', title: 'Dump date', category: 'barrel', shortDefinition: 'When a barrel is emptied for bottling — traceability for picks.', examples: ['Store pick dump codes', 'Single barrel labels'], relatedSlugs: ['barrel-number', 'single-barrel', 'store-pick'], cousinIdeas: ['Bottling date'] },
  { slug: 'barrel-number', title: 'Barrel number', category: 'barrel', shortDefinition: 'Unique barrel ID — critical for single barrel and store picks.', examples: ['Pick label barrel IDs', 'Warehouse tracking'], relatedSlugs: ['dump-date', 'single-barrel'], cousinIdeas: ['Barrel ID'] },
  { slug: 'honey-barrel', title: 'Honey barrel', category: 'barrel', shortDefinition: 'Exceptionally good barrel — often reserved for premium releases.', examples: ['Hand-selected honey barrels', 'Master distiller holds'], relatedSlugs: ['single-barrel', 'store-pick', 'blending'], cousinIdeas: ['Select barrels'] },
  { slug: 'barrel-finish', title: 'Barrel finish', category: 'barrel', shortDefinition: 'Extra aging in a second barrel — wine, port, sherry, etc.', examples: ['Wine-finished limited releases', 'Secondary cask experiments'], relatedSlugs: ['finish-length', 'cooperage'], cousinIdeas: ['Secondary maturation'] },
  { slug: 'finish-length', title: 'Finish length', category: 'barrel', shortDefinition: 'Time in secondary cask — short finish vs long finish changes impact.', examples: ['Months vs years finished', 'Over-finished warnings'], relatedSlugs: ['barrel-finish', 'age-statement'], cousinIdeas: ['Secondary aging time'] },

  // ─── Proof & bottling ────────────────────────────────────────
  { slug: 'proof', title: 'Proof', category: 'legal', shortDefinition: 'Twice the alcohol by volume — 100 proof equals 50% ABV.', examples: ['90 proof daily drinker', '100 proof BiB'], relatedSlugs: ['barrel-proof', 'cask-strength', 'bottled-in-bond'], cousinIdeas: ['ABV', 'Alcohol strength'] },
  { slug: 'barrel-proof', title: 'Barrel proof', category: 'legal', shortDefinition: 'Strength of whiskey in the barrel — often higher than bottle.', examples: ['Stagg', 'Many store picks'], relatedSlugs: ['cask-strength', 'proof', 'hazmat-proof'], cousinIdeas: ['Uncut barrel strength'] },
  { slug: 'cask-strength', title: 'Cask strength', category: 'legal', shortDefinition: 'Bottled at barrel proof without dilution to standard proof.', examples: ['Booker\'s batches', 'Barrel pick proofs'], relatedSlugs: ['barrel-proof', 'non-chill-filtered'], cousinIdeas: ['Full proof bottling'] },
  { slug: 'hazmat-proof', title: 'Hazmat proof', category: 'market', shortDefinition: 'Whiskey above 140 proof — special shipping and handling rules.', examples: ['Extreme barrel proofs', 'Rare hazmat releases'], relatedSlugs: ['barrel-proof', 'cask-strength'], cousinIdeas: ['High proof logistics'] },
  { slug: 'proofing-water', title: 'Proofing water', category: 'production', shortDefinition: 'Water added to reduce proof before bottling — limestone matters in Kentucky.', examples: ['Kentucky limestone water', 'Proof down from barrel'], relatedSlugs: ['proof', 'bottling-proof'], cousinIdeas: ['Cut water'] },
  { slug: 'bottling-proof', title: 'Bottling proof', category: 'legal', shortDefinition: 'Final ABV in bottle after any water addition.', examples: ['Eagle Rare 90', 'Wild Turkey 101'], relatedSlugs: ['proof', 'barrel-proof'], cousinIdeas: ['Final proof'] },
  { slug: 'chill-filtration', title: 'Chill filtration', category: 'chemistry', shortDefinition: 'Cold-filtering to remove fatty compounds — prevents cloudiness when chilled.', examples: ['Standard shelf bottlings', 'Export chill filtered'], relatedSlugs: ['non-chill-filtered', 'mouthfeel'], cousinIdeas: ['Cold filtering'] },
  { slug: 'non-chill-filtered', title: 'Non-chill filtered', category: 'chemistry', shortDefinition: 'Skipped chill filtration — may haze when iced, richer mouthfeel.', examples: ['Four Roses Single Barrel', 'Many barrel proofs'], relatedSlugs: ['chill-filtration', 'mouthfeel'], cousinIdeas: ['NCF'] },

  // ─── Label categories ────────────────────────────────────────
  { slug: 'bottled-in-bond', title: 'Bottled-in-bond', category: 'legal', shortDefinition: 'One distiller, one season, 4+ years, 100 proof — US quality baseline.', examples: ['Old Grand-Dad Bonded', 'Evan Williams White Label BiB'], relatedSlugs: ['dsp', 'straight-bourbon', 'proof'], cousinIdeas: ['Bonded whiskey', '1897 Act'] },
  { slug: 'dsp', title: 'DSP', category: 'legal', shortDefinition: 'Distilled Spirits Plant ID — TTB number tracing who distilled the liquid.', examples: ['DSP-KY-1 Buffalo Trace', 'Sourced whiskey tracing'], relatedSlugs: ['bottled-in-bond', 'sourcing'], cousinIdeas: ['DSP number', 'Distillery ID'] },
  { slug: 'straight-bourbon', title: 'Straight bourbon', category: 'legal', shortDefinition: 'Aged 2+ years, no added flavoring — meets bourbon grain rules.', examples: ['Most shelf bourbon', 'Minimum age transparency'], relatedSlugs: ['kentucky-straight-bourbon', 'age-statement'], cousinIdeas: ['Straight whiskey'] },
  { slug: 'kentucky-straight-bourbon', title: 'Kentucky straight bourbon', category: 'legal', shortDefinition: 'Bourbon distilled and aged in Kentucky — dominant production region.', examples: ['Jim Beam', 'Wild Turkey', 'Maker\'s Mark'], relatedSlugs: ['straight-bourbon', 'bourbon-trail'], cousinIdeas: ['Kentucky whiskey'], geography: 'Kentucky — limestone water, climate, and concentration of distilleries.' },
  { slug: 'american-whiskey', title: 'American whiskey', category: 'legal', shortDefinition: 'Broad category including bourbon, rye, wheat whiskey, corn whiskey.', examples: ['Bourbon subset', 'Rye and wheat whiskey'], relatedSlugs: ['straight-bourbon', 'rye-whiskey'], cousinIdeas: ['US whiskey styles'] },
  { slug: 'rye-whiskey', title: 'Rye whiskey', category: 'legal', shortDefinition: 'At least 51% rye — spicier cousin, not bourbon.', examples: ['Rittenhouse', 'Wild Turkey Rye'], relatedSlugs: ['high-rye-bourbon', 'rye'], cousinIdeas: ['Spicy American whiskey'] },
  { slug: 'tennessee-whiskey', title: 'Tennessee whiskey', category: 'legal', shortDefinition: 'Charcoal mellowed before barreling — Jack Daniel\'s category.', examples: ['Jack Daniel\'s', 'George Dickel'], relatedSlugs: ['lincoln-county-process'], cousinIdeas: ['Charcoal filtered whiskey'], geography: 'Tennessee — Lynchburg and Cascade Hollow distilleries.' },
  { slug: 'lincoln-county-process', title: 'Lincoln County Process', category: 'production', shortDefinition: 'Sugar maple charcoal filtering before barreling — Tennessee signature.', examples: ['Jack Daniel\'s mellowing vats'], relatedSlugs: ['tennessee-whiskey'], cousinIdeas: ['Charcoal mellowing'], geography: 'Tennessee — historically Lincoln County, now broader state practice.' },
  { slug: 'age-statement', title: 'Age statement', category: 'legal', shortDefinition: 'Youngest whiskey age printed on label.', examples: ['Eagle Rare 10', 'Age-stated premiums'], relatedSlugs: ['non-age-stated', 'angels-share'], cousinIdeas: ['NAS vs aged'] },
  { slug: 'non-age-stated', title: 'Non-age stated', category: 'legal', shortDefinition: 'No age on label — youngest whiskey may be minimum legal age.', examples: ['Buffalo Trace flagship', 'Many NAS blends'], relatedSlugs: ['age-statement', 'blending'], cousinIdeas: ['NAS'] },

  // ─── Style types ─────────────────────────────────────────────
  { slug: 'wheated-bourbon', title: 'Wheated bourbon', category: 'grain', shortDefinition: 'Wheat replaces rye as flavor grain — soft, honey, bread notes.', examples: ['Maker\'s Mark', 'Weller', 'Larceny'], relatedSlugs: ['wheat', 'mash-bill', 'high-rye-bourbon'], cousinIdeas: ['Soft bourbon'] },
  { slug: 'high-rye-bourbon', title: 'High-rye bourbon', category: 'grain', shortDefinition: 'Elevated rye percentage — pepper, mint, spice forward.', examples: ['Four Roses recipes', 'Old Forester 100'], relatedSlugs: ['rye', 'mash-bill', 'wheated-bourbon'], cousinIdeas: ['Spicy bourbon'] },
  { slug: 'single-barrel', title: 'Single barrel', category: 'barrel', shortDefinition: 'One barrel bottled — variation between barrels expected.', examples: ['Blanton\'s', 'Store picks'], relatedSlugs: ['small-batch', 'store-pick', 'private-selection'], cousinIdeas: ['One barrel bottling'] },
  { slug: 'small-batch', title: 'Small batch', category: 'barrel', shortDefinition: 'Modest number of barrels blended — more consistent than single barrel.', examples: ['Knob Creek Small Batch', 'Elijah Craig Small Batch'], relatedSlugs: ['single-barrel', 'blending'], cousinIdeas: ['Limited blend'] },
  { slug: 'blending', title: 'Blending', category: 'production', shortDefinition: 'Combining barrels to hit flavor target and consistency.', examples: ['Master blender selections', 'House style maintenance'], relatedSlugs: ['small-batch', 'single-barrel'], cousinIdeas: ['Vatting'] },
  { slug: 'store-pick', title: 'Store pick', category: 'market', shortDefinition: 'Retailer-selected single barrel exclusive bottling.', examples: ['Local liquor store picks', 'Chain program picks'], relatedSlugs: ['single-barrel', 'private-selection', 'allocation'], cousinIdeas: ['Handpicked barrel'] },
  { slug: 'private-selection', title: 'Private selection', category: 'market', shortDefinition: 'Barrel chosen for a private group — clubs, restaurants, stores.', examples: ['Bourbon club picks', 'Restaurant single barrels'], relatedSlugs: ['store-pick', 'single-barrel'], cousinIdeas: ['Barrel select'] },
  { slug: 'dusty-bourbon', title: 'Dusty bourbon', category: 'market', shortDefinition: 'Older discontinued bottlings — collector term for vintage shelf finds.', examples: ['Pre-1990s labels', 'Closed distillery bottles'], relatedSlugs: ['secondary-market', 'age-statement'], cousinIdeas: ['Vintage bottles'] },

  // ─── Market ──────────────────────────────────────────────────
  { slug: 'allocation', title: 'Allocation', category: 'market', shortDefinition: 'Distillery-controlled scarce distribution — not everyone gets bottles.', examples: ['Weller allocation', 'BTAC drops'], relatedSlugs: ['allocation-season', 'msrp', 'secondary-market'], cousinIdeas: ['Allocated whiskey'] },
  { slug: 'allocation-season', title: 'Allocation season', category: 'market', shortDefinition: 'Periodic drops of allocated bottles to retailers.', examples: ['Fall BTAC', 'Regional Weller drops'], relatedSlugs: ['allocation', 'msrp'], cousinIdeas: ['Release calendar'] },
  { slug: 'msrp', title: 'MSRP', category: 'market', shortDefinition: 'Manufacturer suggested retail price — often far below secondary reality.', examples: ['Suggested vs shelf price', 'Markup debates'], relatedSlugs: ['secondary-market', 'allocation'], cousinIdeas: ['Retail price'] },
  { slug: 'secondary-market', title: 'Secondary market', category: 'market', shortDefinition: 'Resale market for bottles — auctions, groups, markup culture.', examples: ['Pappy secondary pricing', 'Online resale groups'], relatedSlugs: ['msrp', 'allocation', 'dusty-bourbon'], cousinIdeas: ['Resale'] },

  // ─── Tasting ─────────────────────────────────────────────────
  { slug: 'nose', title: 'Nose', category: 'tasting', shortDefinition: 'Aroma before tasting — often half the experience.', examples: ['Glencairn nosing', 'Cinnamon and caramel preview'], relatedSlugs: ['palate', 'flavor-wheel', 'blind-tasting'], cousinIdeas: ['Aroma'] },
  { slug: 'palate', title: 'Palate', category: 'tasting', shortDefinition: 'Flavors and mouthfeel on the tongue.', examples: ['Sweet vs spice balance', 'Wheated honey notes'], relatedSlugs: ['nose', 'finish', 'mouthfeel'], cousinIdeas: ['Taste'] },
  { slug: 'finish', title: 'Finish', category: 'tasting', shortDefinition: 'Lingering flavors after swallowing — short, medium, or long.', examples: ['Long vanilla finish', 'Pepper fade'], relatedSlugs: ['palate', 'finish-length'], cousinIdeas: ['Aftertaste'] },
  { slug: 'mouthfeel', title: 'Mouthfeel', category: 'tasting', shortDefinition: 'Texture and weight — oily, creamy, thin, astringent.', examples: ['NCF richness', 'Chill filtered thinness'], relatedSlugs: ['non-chill-filtered', 'palate', 'tannins'], cousinIdeas: ['Texture'] },
  { slug: 'flavor-wheel', title: 'Flavor wheel', category: 'tasting', shortDefinition: 'Visual map of common tasting descriptors — training tool.', examples: ['Foundry flavor wheel tool', 'Competition judging wheels'], relatedSlugs: ['nose', 'palate', 'blind-tasting'], cousinIdeas: ['Tasting vocabulary'] },
  { slug: 'blind-tasting', title: 'Blind tasting', category: 'tasting', shortDefinition: 'Samples without labels until after scoring — removes bias.', examples: ['Numbered bag pours', 'Blind league rounds'], relatedSlugs: ['nose', 'flavor-wheel'], cousinIdeas: ['Blind flight'] },
  { slug: 'neck-pour', title: 'Neck pour', category: 'tasting', shortDefinition: 'First pours from a newly opened bottle — often hotter, less settled.', examples: ['Open and revisit next week', 'Let it breathe'], relatedSlugs: ['open-bottle-effect', 'palate'], cousinIdeas: ['First pour'] },
  { slug: 'open-bottle-effect', title: 'Open bottle effect', category: 'tasting', shortDefinition: 'Flavor change after opening — oxidation and air exposure over weeks.', examples: ['Two-week revisit', 'Slow evolution'], relatedSlugs: ['neck-pour', 'palate'], cousinIdeas: ['Oxidation'] },

  // ─── Chemistry notes ─────────────────────────────────────────
  { slug: 'ethanol', title: 'Ethanol', category: 'chemistry', shortDefinition: 'Primary alcohol in whiskey — carries flavor, adds heat.', examples: ['Proof and burn', 'Dilution with water'], relatedSlugs: ['proof', 'congeners'], cousinIdeas: ['Alcohol'] },
  { slug: 'esters', title: 'Esters', category: 'chemistry', shortDefinition: 'Fruity aromatic compounds from fermentation — apple, banana, pear.', examples: ['Long ferment fruitiness', 'Yeast-driven esters'], relatedSlugs: ['fermentation', 'congeners'], cousinIdeas: ['Fruity compounds'] },
  { slug: 'vanillin', title: 'Vanillin', category: 'chemistry', shortDefinition: 'Vanilla compound from oak lignin breakdown — classic bourbon note.', examples: ['New oak extraction', 'Charred barrel vanilla'], relatedSlugs: ['cooperage', 'char-level'], cousinIdeas: ['Vanilla compound'] },
  { slug: 'lactones', title: 'Lactones', category: 'chemistry', shortDefinition: 'Coconut and woody compounds from oak — toast increases lactones.', examples: ['Toasted barrel coconut', 'Woody aroma'], relatedSlugs: ['toasting', 'cooperage'], cousinIdeas: ['Coconut notes'] },
  { slug: 'tannins', title: 'Tannins', category: 'chemistry', shortDefinition: 'Astringent compounds from wood — drying grip on palate.', examples: ['Young oak tannin', 'Long age softening'], relatedSlugs: ['mouthfeel', 'cooperage'], cousinIdeas: ['Astringency'] },

  // ─── Culture & history ───────────────────────────────────────
  { slug: 'prohibition', title: 'Prohibition', category: 'culture', shortDefinition: '1920–1933 US alcohol ban — medicinal licenses, bootlegging, industry consolidation.', examples: ['Medicinal whiskey prescriptions', 'Six distilleries allowed'], relatedSlugs: ['medicinal-whiskey', 'bourbon-county'], cousinIdeas: ['18th Amendment'], geography: 'United States — Kentucky distilleries received medicinal licenses.' },
  { slug: 'medicinal-whiskey', title: 'Medicinal whiskey', category: 'culture', shortDefinition: 'Prohibition-era legal whiskey with doctor prescription.', examples: ['Pharmacy bottlings', 'Historical labels'], relatedSlugs: ['prohibition'], cousinIdeas: ['Prescription whiskey'] },
  { slug: 'bourbon-county', title: 'Bourbon County', category: 'culture', shortDefinition: 'Kentucky county whose name is often linked to bourbon origin debates.', examples: ['Historical shipping name', 'Origin myths'], relatedSlugs: ['kentucky-straight-bourbon', 'house-of-bourbon'], cousinIdeas: ['Name origin'], geography: 'Kentucky — central Bluegrass region.' },
  { slug: 'house-of-bourbon', title: 'House of Bourbon', category: 'culture', shortDefinition: 'Political/dynastic term sometimes used for bourbon industry families and brands.', examples: ['Distilling dynasties', 'Brand heritage marketing'], relatedSlugs: ['bourbon-county', 'prohibition'], cousinIdeas: ['Distilling families'] },
  { slug: 'bourbon-street', title: 'Bourbon Street', category: 'culture', shortDefinition: 'New Orleans strip — cultural association with cocktails and nightlife, not production.', examples: ['Tourism confusion with spirit', 'Cocktail culture'], relatedSlugs: ['mint-julep'], cousinIdeas: ['New Orleans'], geography: 'Louisiana — French Quarter, New Orleans.' },
  { slug: 'bourbon-trail', title: 'Bourbon trail', category: 'culture', shortDefinition: 'Kentucky distillery tourism route — campuses, tastings, rickhouses.', examples: ['Kentucky Bourbon Trail', 'Craft trail extensions'], relatedSlugs: ['kentucky-straight-bourbon', 'distillery-pilgrim'], cousinIdeas: ['Distillery tourism'], geography: 'Kentucky — Bardstown, Louisville, Frankfort corridors.' },
  { slug: 'mint-julep', title: 'Mint julep', category: 'culture', shortDefinition: 'Classic bourbon cocktail — Derby tradition, crushed ice, mint.', examples: ['Kentucky Derby serve', 'Silver cup presentation'], relatedSlugs: ['kentucky-derby', 'bourbon-street'], cousinIdeas: ['Derby cocktail'] },
  { slug: 'kentucky-derby', title: 'Kentucky Derby', category: 'culture', shortDefinition: 'First Saturday in May — mint juleps, bourbon sponsorship, Kentucky identity.', examples: ['Derby day pours', 'Limited Derby bottlings'], relatedSlugs: ['mint-julep', 'bourbon-trail'], cousinIdeas: ['Horse racing tradition'], geography: 'Kentucky — Churchill Downs, Louisville.' },

  // ─── Additional depth terms ──────────────────────────────────
  { slug: 'master-distiller', title: 'Master distiller', category: 'production', shortDefinition: 'Lead craftsman overseeing production quality and house style.', examples: ['Jimmy Russell', 'Chris Morris'], relatedSlugs: ['blending', 'hearts-cut'], cousinIdeas: ['Distillery leadership'] },
  { slug: 'sourcing', title: 'Sourcing', category: 'market', shortDefinition: 'Buying bulk whiskey from another distillery — label may not show origin.', examples: ['NDP brands', 'DSP tracing'], relatedSlugs: ['dsp', 'bottled-in-bond'], cousinIdeas: ['Non-distiller producer'] },
  { slug: 'glencairn', title: 'Glencairn', category: 'tasting', shortDefinition: 'Tulip tasting glass concentrating aromas for serious nosing.', examples: ['Side-by-side flights', 'Academy tastings'], relatedSlugs: ['nose', 'blind-tasting'], cousinIdeas: ['Tasting glass'] },
  { slug: 'neat', title: 'Neat', category: 'tasting', shortDefinition: 'Whiskey alone at room temperature — no ice or mixers.', examples: ['Evaluation pours', 'Mission tastings'], relatedSlugs: ['palate', 'proof'], cousinIdeas: ['Straight pour'] },
  { slug: 'on-the-rocks', title: 'On the rocks', category: 'tasting', shortDefinition: 'Served over ice — dilution and chill change the experience.', examples: ['Casual serve', 'Large cube vs chips'], relatedSlugs: ['neat', 'chill-filtration'], cousinIdeas: ['Ice serve'] },

  // ─── Additional terms to reach 100+ ──────────────────────────
  { slug: 'charring', title: 'Charring', category: 'barrel', shortDefinition: 'Burning barrel interior to create char layer — activates wood compounds.', examples: ['Flame charring cooperages', 'Level 3 char standard'], relatedSlugs: ['char-level', 'new-charred-oak'], cousinIdeas: ['Barrel burn'] },
  { slug: 'distillation-proof', title: 'Distillation proof', category: 'production', shortDefinition: 'Strength of spirit coming off the still before barreling.', examples: ['160 proof new make', 'Lower proof pot still'], relatedSlugs: ['entry-proof', 'hearts-cut'], cousinIdeas: ['Still strength'] },
  { slug: 'corn-whiskey', title: 'Corn whiskey', category: 'legal', shortDefinition: 'At least 80% corn — can be unaged; different from bourbon minimums.', examples: ['Mellow Corn', 'Unaged corn spirit'], relatedSlugs: ['corn', 'mash-bill'], cousinIdeas: ['Corn spirit'] },
  { slug: 'straight-whiskey', title: 'Straight whiskey', category: 'legal', shortDefinition: 'Aged 2+ years with no added flavoring or coloring.', examples: ['Straight bourbon', 'Straight rye'], relatedSlugs: ['straight-bourbon', 'age-statement'], cousinIdeas: ['Aged whiskey category'] },
  { slug: 'nosing', title: 'Nosing', category: 'tasting', shortDefinition: 'Act of evaluating aroma before tasting — technique matters.', examples: ['Glencairn nosing', 'Distance from glass'], relatedSlugs: ['nose', 'glencairn'], cousinIdeas: ['Aroma evaluation'] },
  { slug: 'vatting', title: 'Vatting', category: 'production', shortDefinition: 'Blending multiple barrels in a vat before bottling.', examples: ['Large batch vatting', 'Small batch vatting'], relatedSlugs: ['blending', 'small-batch'], cousinIdeas: ['Batch combine'] },
  { slug: 'barrel-aging', title: 'Barrel aging', category: 'barrel', shortDefinition: 'Maturation in oak — time, climate, and wood transform new make.', examples: ['Minimum two years straight', 'Decades for premium'], relatedSlugs: ['rickhouse', 'angels-share', 'age-statement'], cousinIdeas: ['Maturation'] },
  { slug: 'craft-distillery', title: 'Craft distillery', category: 'culture', shortDefinition: 'Smaller-scale producer — often highlights sweet mash, local grain, innovation.', examples: ['Regional craft tours', 'Experimental mash bills'], relatedSlugs: ['sweet-mash', 'mash-bill'], cousinIdeas: ['Small batch producer'] },
  { slug: 'limestone-water', title: 'Limestone water', category: 'culture', shortDefinition: 'Kentucky karst water — low iron, often credited in bourbon lore.', examples: ['Central Kentucky aquifers', 'Distillery water sources'], relatedSlugs: ['kentucky-straight-bourbon', 'proofing-water'], cousinIdeas: ['Water chemistry'], geography: 'Kentucky — Bluegrass aquifer region.' },
  { slug: 'over-oaked', title: 'Over-oaked', category: 'tasting', shortDefinition: 'Excessive wood tannin and dryness — common in very long or hot aging.', examples: ['Tannic older bottles', 'Small barrel over-aging'], relatedSlugs: ['tannins', 'barrel-aging'], cousinIdeas: ['Wood fatigue'] },
  { slug: 'single-barrel-program', title: 'Single barrel program', category: 'market', shortDefinition: 'Distillery or retailer pipeline for one-barrel releases.', examples: ['Total Wine picks', 'Distillery private barrels'], relatedSlugs: ['single-barrel', 'store-pick'], cousinIdeas: ['Pick programs'] },
];
