import type { AiBuilderMission } from '../../ai-builder-world';
import type { WorldImmersionMeta, ImmersionMissionBlueprint } from '../types';
import { buildImmersionMission, chainMissions, withTrackLabels } from '../mission-builder';

export const AI_BUILDER_TRACKS = [
  { slug: 'ai-for-school', label: 'AI for School', description: 'Study smarter, research deeper, learn faster', estimatedHours: '10+' },
  { slug: 'ai-for-business', label: 'AI for Business', description: 'Automate work, serve customers, save hours', estimatedHours: '10+' },
  { slug: 'ai-for-creativity', label: 'AI for Creativity', description: 'Stories, art direction, media, personal brand', estimatedHours: '10+' },
  { slug: 'ai-automation', label: 'AI Automation', description: 'Workflows, agents, pipelines that run without you', estimatedHours: '10+' },
  { slug: 'ai-entrepreneurship', label: 'AI Entrepreneurship', description: 'Ship products, validate ideas, earn with AI', estimatedHours: '10+' },
] as const;

const TRACK_LABELS = Object.fromEntries(AI_BUILDER_TRACKS.map((t) => [t.slug, t.label]));

/** Missions 6–25 — generated from blueprints; missions 1–5 preserved in ai-builder-world.ts */
const EXPANSION_BLUEPRINTS: ImmersionMissionBlueprint[] = [
  // AI for School (6–10) — homework-assistant + research-agent are 1–2
  {
    slug: 'study-scheduler',
    number: 6,
    track: 'ai-for-school',
    title: 'Build an AI Study Scheduler',
    subtitle: 'Plan your week with an assistant that knows your deadlines',
    outcome: 'A weekly study plan generated and adjusted by AI based on your real syllabus',
    evidence: 'Screenshot of schedule + reflection on one tradeoff the AI missed',
    timeEstimate: '60 min',
    requiredLevel: 'AI User (Level 2)',
    futureProof: 'Time management with AI beats cramming — employers notice people who plan.',
    tomorrowHook: 'Tomorrow: Mission 7 — build an exam prep coach for your hardest test.',
    missionFocus: 'Export your syllabus deadlines. Ask AI to draft a 2-week study plan with daily 45-minute blocks. Adjust for one sport, job, or family commitment.',
    buildChecklist: ['List every deadline for the next 3 weeks', 'Generate a draft schedule with AI', 'Move one block manually — AI cannot know everything'],
    showArtifact: 'Save the final schedule to your portfolio. Highlight one day you redesigned yourself.',
    reflectPrompt: 'Where did AI over-schedule you? What rule would you add to the prompt next time?',
    improveAction: 'Add a "light day" rule and regenerate once.',
    mentorAction: 'Help a classmate build their version for a different class load.',
  },
  {
    slug: 'exam-prep-coach',
    number: 7,
    track: 'ai-for-school',
    title: 'Build an AI Exam Prep Coach',
    subtitle: 'Turn notes into quizzes, weak spots, and a cram plan',
    outcome: 'A prep system that quizzes you, tracks misses, and focuses review',
    evidence: 'Quiz log + list of 3 weak topics you drilled',
    timeEstimate: '75 min',
    requiredLevel: 'AI Creator (Level 3)',
    futureProof: 'Self-testing beats re-reading — AI makes it scalable.',
    tomorrowHook: 'Tomorrow: Mission 8 — language practice partner.',
    missionFocus: 'Pick one upcoming test. Upload or paste notes. Prompt AI to generate 20 questions, score your answers, and list weak topics.',
    buildChecklist: ['Paste or upload study material', 'Run 20-question quiz', 'Drill top 3 weak topics'],
    showArtifact: 'Save quiz results and weak-topic list to portfolio.',
    reflectPrompt: 'Which questions fooled you? Was the AI too easy or too hard?',
    improveAction: 'Add one "explain like I\'m 12" step for your hardest miss.',
    mentorAction: 'Quiz a sibling on one topic using your coach prompts.',
  },
  {
    slug: 'language-practice-partner',
    number: 8,
    track: 'ai-for-school',
    title: 'Build an AI Language Practice Partner',
    subtitle: 'Conversation practice without embarrassment',
    outcome: 'A bilingual drill partner with correction and vocabulary tracking',
    evidence: '5-minute conversation transcript + 10 new words learned',
    timeEstimate: '60 min',
    requiredLevel: 'AI User (Level 2)',
    futureProof: 'Language + AI fluency is a career multiplier in a global economy.',
    tomorrowHook: 'Tomorrow: Mission 9 — science fair project helper.',
    missionFocus: 'Choose a language you study. Build a prompt: role-play ordering food, asking directions, or debating a simple topic. Log corrections.',
    buildChecklist: ['Define 3 conversation scenarios', 'Run 5-minute role-play', 'Log 10 corrected phrases'],
    showArtifact: 'Save transcript excerpt and vocabulary list.',
    reflectPrompt: 'Did you rely on translation or think in the language?',
    improveAction: 'Add a "no English" rule for one scenario.',
    mentorAction: 'Teach a friend your best correction prompt.',
  },
  {
    slug: 'science-project-helper',
    number: 9,
    track: 'ai-for-school',
    title: 'Build a Science Project Helper',
    subtitle: 'Hypothesis, method, data, conclusion — with AI as lab partner',
    outcome: 'A structured science project workflow from question to poster',
    evidence: 'Project outline + one graph or data table you built',
    timeEstimate: '90 min',
    requiredLevel: 'AI Creator (Level 3)',
    futureProof: 'Science fairs teach inquiry — AI accelerates without replacing thinking.',
    tomorrowHook: 'Tomorrow: Mission 10 — peer study group facilitator.',
    missionFocus: 'Pick a testable question. Use AI to draft method, suggest variables, and format results — you run the experiment.',
    buildChecklist: ['Write hypothesis in your words', 'Collect real data (even small sample)', 'Draft conclusion without copy-paste'],
    showArtifact: 'Save outline + data table to portfolio.',
    reflectPrompt: 'What did you verify manually that AI got wrong?',
    improveAction: 'Add sources section with 2 primary references.',
    mentorAction: 'Walk a younger student through your method.',
  },
  {
    slug: 'study-group-facilitator',
    number: 10,
    track: 'ai-for-school',
    title: 'Build a Study Group Facilitator',
    subtitle: 'AI agendas, icebreakers, and recap notes for group sessions',
    outcome: 'A facilitator kit for running 30-minute peer study sessions',
    evidence: 'Agenda template + notes from one real session you led',
    timeEstimate: '60 min',
    requiredLevel: 'AI Builder (Level 4)',
    futureProof: 'Leaders who run study groups learn twice — facilitation is leadership.',
    tomorrowHook: 'Next track: AI for Business — client email system.',
    missionFocus: 'Design a 30-minute study session format: warm-up quiz, peer teach-back, AI-generated recap. Run it once with 2+ people.',
    buildChecklist: ['Create agenda template', 'Run one session', 'Send AI recap to group'],
    showArtifact: 'Save agenda + session notes.',
    reflectPrompt: 'What would make the next session better?',
    improveAction: 'Add a peer feedback question at the end.',
    mentorAction: 'Give your kit to another student to run their group.',
  },
  // AI for Business (11–15)
  {
    slug: 'client-email-system',
    number: 11,
    track: 'ai-for-business',
    title: 'Build a Client Email System',
    subtitle: 'Templates, tone guides, and follow-ups that sound like you',
    outcome: 'A reusable email workflow for outreach, replies, and follow-ups',
    evidence: '3 email templates + one sent email screenshot (redact private info)',
    timeEstimate: '60 min',
    requiredLevel: 'AI Builder (Level 4)',
    futureProof: 'Professional communication is a paid skill — AI drafts, you decide.',
    tomorrowHook: 'Tomorrow: proposal generator mission.',
    missionFocus: 'Define 3 email types you send (or will send): inquiry, follow-up, thank-you. Build tone guide + templates with AI. Send one real email.',
    buildChecklist: ['Write tone guide (3 rules)', 'Create 3 templates', 'Send or schedule one email'],
    showArtifact: 'Save templates to My Automations.',
    reflectPrompt: 'What would make these sound less generic?',
    improveAction: 'Add one personal detail rule AI must include.',
    mentorAction: 'Help a parent or club leader set up one template.',
  },
  {
    slug: 'proposal-generator',
    number: 12,
    track: 'ai-for-business',
    title: 'Build a Proposal Generator',
    subtitle: 'Scope, timeline, and pricing drafts for real offers',
    outcome: 'A proposal template you can customize for babysitting, tutoring, or club projects',
    evidence: 'One complete proposal PDF or doc',
    timeEstimate: '75 min',
    requiredLevel: 'AI Builder (Level 4)',
    futureProof: 'People who can scope work get hired — proposals prove you can deliver.',
    tomorrowHook: 'Tomorrow: meeting notes agent.',
    missionFocus: 'Pick a service you could offer. Use AI to draft scope, timeline, deliverables, and price range. Edit until you would send it.',
    buildChecklist: ['Define offer in one sentence', 'Draft proposal sections', 'Set a fair price with rationale'],
    showArtifact: 'Save proposal to portfolio.',
    reflectPrompt: 'Would you send this as-is? What is still missing?',
    improveAction: 'Add testimonials or sample work section.',
    mentorAction: 'Review a friend\'s proposal with your template.',
  },
  {
    slug: 'meeting-notes-agent',
    number: 13,
    track: 'ai-for-business',
    title: 'Build a Meeting Notes Agent',
    subtitle: 'Summaries, action items, and follow-ups from any meeting',
    outcome: 'A workflow that turns messy notes into actionable summaries',
    evidence: 'One meeting summary with owners and due dates',
    timeEstimate: '45 min',
    requiredLevel: 'AI User (Level 2)',
    futureProof: 'Every team needs someone who captures decisions — that is leverage.',
    tomorrowHook: 'Tomorrow: invoice tracker.',
    missionFocus: 'Attend or watch a club, family, or class meeting. Take raw notes. Prompt AI for summary, decisions, action items.',
    buildChecklist: ['Capture raw notes', 'Generate structured summary', 'Assign owners to 3 actions'],
    showArtifact: 'Save summary to portfolio.',
    reflectPrompt: 'Did AI miss a decision? What format works best?',
    improveAction: 'Add a "parking lot" section for unresolved items.',
    mentorAction: 'Share template with a club officer.',
  },
  {
    slug: 'invoice-tracker-ai',
    number: 14,
    track: 'ai-for-business',
    title: 'Build an Invoice & Payment Tracker',
    subtitle: 'Know who owes what — side hustle or club treasury',
    outcome: 'A simple tracker with AI reminders and payment follow-up drafts',
    evidence: 'Tracker screenshot + one follow-up message draft',
    timeEstimate: '60 min',
    requiredLevel: 'AI Builder (Level 4)',
    futureProof: 'Cash flow clarity prevents 90% of small business stress.',
    tomorrowHook: 'Tomorrow: sales outreach bot.',
    missionFocus: 'List 5+ real or practice invoices. Build a sheet with status, due date, amount. Use AI to draft polite follow-ups.',
    buildChecklist: ['Create tracker columns', 'Enter 5 entries', 'Draft 2 follow-up messages'],
    showArtifact: 'Save tracker + best follow-up template.',
    reflectPrompt: 'What would break if you scaled to 50 clients?',
    improveAction: 'Add automated reminder rule (calendar or Zapier).',
    mentorAction: 'Help a family member track one recurring bill.',
  },
  {
    slug: 'sales-outreach-bot',
    number: 15,
    track: 'ai-for-business',
    title: 'Build a Sales Outreach Bot',
    subtitle: 'Personalized outreach at scale — without spam',
    outcome: 'A research + draft pipeline for 10 personalized messages',
    evidence: 'Outreach log with 3 sent messages and response notes',
    timeEstimate: '90 min',
    requiredLevel: 'AI Entrepreneur (Level 6)',
    futureProof: 'Revenue follows conversations — ethical outreach is a superpower.',
    tomorrowHook: 'Next track: AI for Creativity.',
    missionFocus: 'Define 10 targets (customers, sponsors, mentors). Research each. Draft personalized 3-sentence opens. Send 3.',
    buildChecklist: ['Define ideal customer', 'Research 10 targets', 'Send 3 personalized messages'],
    showArtifact: 'Save outreach log (redact contacts if needed).',
    reflectPrompt: 'What got replies? What felt cringe?',
    improveAction: 'Rewrite worst message manually without AI.',
    mentorAction: 'Coach a peer on personalization vs templates.',
  },
  // AI for Creativity (16–20)
  {
    slug: 'story-world-builder',
    number: 16,
    track: 'ai-for-creativity',
    title: 'Build a Story World with AI',
    subtitle: 'Characters, rules, and plot arcs for a world you own',
    outcome: 'A story bible with 3 characters, setting rules, and chapter outline',
    evidence: 'Story bible doc + 500 words you wrote (not AI-generated wholesale)',
    timeEstimate: '90 min',
    requiredLevel: 'AI Creator (Level 3)',
    futureProof: 'Creators who ship worlds build audiences — AI is the studio intern.',
    tomorrowHook: 'Tomorrow: art direction assistant.',
    missionFocus: 'Define genre and theme. Use AI for brainstorming — you write the canon. Produce character sheets and 5-chapter outline.',
    buildChecklist: ['Define theme in one sentence', 'Create 3 character sheets', 'Write 500 words of chapter 1 yourself'],
    showArtifact: 'Save bible + your prose sample.',
    reflectPrompt: 'What must stay human in your creative process?',
    improveAction: 'Cut one AI cliché from your outline.',
    mentorAction: 'Read your opening to someone and note their reaction.',
  },
  {
    slug: 'art-direction-assistant',
    number: 17,
    track: 'ai-for-creativity',
    title: 'Build an Art Direction Assistant',
    subtitle: 'Mood boards, palettes, and briefs for visual projects',
    outcome: 'A creative brief + mood board for one real project',
    evidence: 'Mood board (Pinterest, Figma, or slides) + brief doc',
    timeEstimate: '75 min',
    requiredLevel: 'AI Creator (Level 3)',
    futureProof: 'Visual taste is scarce — AI generates options, you curate.',
    tomorrowHook: 'Tomorrow: podcast outline lab.',
    missionFocus: 'Pick a poster, thumbnail, or room redesign. Prompt AI for 3 directions. Choose one. Build mood board with references.',
    buildChecklist: ['Write creative brief', 'Generate 3 directions', 'Finalize mood board'],
    showArtifact: 'Link mood board in portfolio.',
    reflectPrompt: 'Which direction is most you? Why?',
    improveAction: 'Remove half the board — keep only strongest refs.',
    mentorAction: 'Explain your direction to a non-designer.',
  },
  {
    slug: 'podcast-outline-lab',
    number: 18,
    track: 'ai-for-creativity',
    title: 'Build a Podcast Outline Lab',
    subtitle: 'Episodes, segments, and guest questions — ready to record',
    outcome: 'A 3-episode podcast plan with outlines and hook scripts',
    evidence: 'Episode 1 full outline + 60-second hook you recorded or wrote',
    timeEstimate: '60 min',
    requiredLevel: 'AI Creator (Level 3)',
    futureProof: 'Voice and POV beat generic content — planning makes you consistent.',
    tomorrowHook: 'Tomorrow: video script lab.',
    missionFocus: 'Define show premise and audience. Outline 3 episodes. Write hook scripts. Optional: record 60-second intro.',
    buildChecklist: ['Define show in one sentence', 'Outline episode 1 beat-by-beat', 'Write 60-second hook'],
    showArtifact: 'Save outlines + hook script.',
    reflectPrompt: 'Would you listen? What is missing?',
    improveAction: 'Add one contrarian segment idea.',
    mentorAction: 'Pitch episode 1 to a friend in 30 seconds.',
  },
  {
    slug: 'video-script-lab',
    number: 19,
    track: 'ai-for-creativity',
    title: 'Build a Video Script Lab',
    subtitle: 'Short-form scripts that hook in 3 seconds',
    outcome: '5 video scripts with hooks, beats, and CTAs',
    evidence: 'Best script + storyboard or shot list',
    timeEstimate: '75 min',
    requiredLevel: 'AI Creator (Level 3)',
    futureProof: 'Video literacy is the new literacy — scripts are the blueprint.',
    tomorrowHook: 'Tomorrow: personal brand builder (website mission follows).',
    missionFocus: 'Pick platform (TikTok, YouTube Shorts). Write 5 scripts using hook-problem-proof-CTA. Storyboard your favorite.',
    buildChecklist: ['Study 3 videos you admire', 'Write 5 scripts', 'Storyboard one'],
    showArtifact: 'Save scripts + storyboard.',
    reflectPrompt: 'Which hook would you click? Test on one person.',
    improveAction: 'Film 15-second test clip of best hook.',
    mentorAction: 'Swap scripts with a peer for feedback.',
  },
  {
    slug: 'personal-brand-builder',
    number: 20,
    track: 'ai-for-creativity',
    title: 'Build Your Personal Brand with AI',
    subtitle: 'Bio, pillars, and content calendar for who you are becoming',
    outcome: 'Brand one-pager + 2-week content calendar',
    evidence: 'Brand doc + 3 posts drafted (not all published required)',
    timeEstimate: '90 min',
    requiredLevel: 'AI Architect (Level 5)',
    futureProof: 'Your brand is what people say when you leave the room — design it.',
    tomorrowHook: 'Next track: AI Automation — workflow chains.',
    missionFocus: 'Define 3 content pillars aligned with who you are becoming. Draft bio, tagline, and 6 post ideas with AI — edit to sound like you.',
    buildChecklist: ['Write 3 pillars', 'Draft bio you would use', 'Plan 6 posts'],
    showArtifact: 'Save brand one-pager to portfolio.',
    reflectPrompt: 'What feels inauthentic? Delete it.',
    improveAction: 'Publish or send one post to a trusted friend.',
    mentorAction: 'Help a peer find their pillars.',
  },
  // AI Automation (21–23) — research-agent + personal-ai-team anchor this track
  {
    slug: 'workflow-chain',
    number: 21,
    track: 'ai-automation',
    title: 'Build a Multi-Step Workflow Chain',
    subtitle: 'When A happens, AI does B then C — no manual copy-paste',
    outcome: 'A 3-step automated chain with documented triggers',
    evidence: 'Workflow diagram + screenshot of one successful run',
    timeEstimate: '90 min',
    requiredLevel: 'AI Architect (Level 5)',
    futureProof: 'Automation is the closest thing to leverage without capital.',
    tomorrowHook: 'Tomorrow: data extraction bot.',
    missionFocus: 'Pick a repeating task (email → summary → task list). Build chain in Make, Zapier, or manual checklist first. Automate one link.',
    buildChecklist: ['Map 3 steps', 'Run manually once', 'Automate at least one handoff'],
    showArtifact: 'Save diagram + run screenshot.',
    reflectPrompt: 'Where did the chain break?',
    improveAction: 'Add error notification step.',
    mentorAction: 'Document chain so someone else could run it.',
  },
  {
    slug: 'data-extraction-bot',
    number: 22,
    track: 'ai-automation',
    title: 'Build a Data Extraction Bot',
    subtitle: 'Pull structured data from messy text or PDFs',
    outcome: 'A pipeline that turns unstructured input into a clean table',
    evidence: 'Before/after table with 10+ rows extracted',
    timeEstimate: '75 min',
    requiredLevel: 'AI Architect (Level 5)',
    futureProof: 'Data cleaning is half of knowledge work — automate the boring half.',
    tomorrowHook: 'Tomorrow: document classifier.',
    missionFocus: 'Find messy source: emails, receipts, articles. Prompt AI to extract fields into CSV. Verify 5 rows manually.',
    buildChecklist: ['Choose messy source', 'Define output columns', 'Verify 5 rows manually'],
    showArtifact: 'Save CSV + verification notes.',
    reflectPrompt: 'What errors would cost money if unchecked?',
    improveAction: 'Add validation rule for one column.',
    mentorAction: 'Show a parent how this saves time at work.',
  },
  {
    slug: 'document-classifier',
    number: 23,
    track: 'ai-automation',
    title: 'Build a Document Classifier',
    subtitle: 'Sort, tag, and route files automatically',
    outcome: 'A classification system for 20+ sample documents',
    evidence: 'Tagging rules doc + accuracy report on 20 samples',
    timeEstimate: '60 min',
    requiredLevel: 'AI Architect (Level 5)',
    futureProof: 'Organizations drown in files — classifiers are employable magic.',
    tomorrowHook: 'Next: AI Entrepreneurship track.',
    missionFocus: 'Define 4 categories (school, finance, personal, archive). Classify 20 files with AI. Measure accuracy. Fix rules for top 3 errors.',
    buildChecklist: ['Define categories', 'Classify 20 samples', 'Fix top 3 mislabels'],
    showArtifact: 'Save rules + accuracy score.',
    reflectPrompt: 'When should a human override the classifier?',
    improveAction: 'Add one "uncertain" bucket rule.',
    mentorAction: 'Apply to a shared family or club folder.',
  },
  // AI Entrepreneurship (24–25)
  {
    slug: 'market-research-agent',
    number: 24,
    track: 'ai-entrepreneurship',
    title: 'Build a Market Research Agent',
    subtitle: 'Validate an idea before you build for months',
    outcome: 'A one-page market memo: problem, competitors, gap, first customer',
    evidence: 'Market memo + list of 5 people you could interview',
    timeEstimate: '90 min',
    requiredLevel: 'AI Entrepreneur (Level 6)',
    futureProof: 'Founders who validate fast win — AI speeds research, not judgment.',
    tomorrowHook: 'Tomorrow: final mission — launch your AI service offer.',
    missionFocus: 'Pick a micro-problem you could solve. Research competitors, pricing, and customer quotes. Write memo — include what AI might be wrong about.',
    buildChecklist: ['Define problem in one sentence', 'List 5 competitors/alternatives', 'Identify first customer profile'],
    showArtifact: 'Save market memo.',
    reflectPrompt: 'Would you bet $100 on this idea? Why or why not?',
    improveAction: 'Message one potential customer — no pitch, just learn.',
    mentorAction: 'Present memo in 3 minutes to a parent or mentor.',
  },
  {
    slug: 'ai-service-offer',
    number: 25,
    track: 'ai-entrepreneurship',
    title: 'Launch Your First AI Service Offer',
    subtitle: 'Package what you built into something someone would pay $4–$50 for',
    outcome: 'A landing page or one-pager offer with price, scope, and proof',
    evidence: 'Live link or PDF + one outreach message sent',
    timeEstimate: '2–3 hours',
    requiredLevel: 'AI Mentor (Level 7)',
    futureProof: 'Entrepreneurship is shipping offers and learning from responses — not slides.',
    tomorrowHook: 'Share in AI Builders Circle. Start your next track or mentor a peer.',
    missionFocus: 'Combine your best 2 projects into one offer: who, outcome, price, timeline. Publish one-pager. Send to 3 prospects.',
    buildChecklist: ['Define offer package', 'Publish one-pager or site', 'Send 3 outreach messages'],
    showArtifact: 'Save offer + responses to portfolio.',
    reflectPrompt: 'What objection came up? How would you answer it next time?',
    improveAction: 'Adjust price or scope based on one conversation.',
    mentorAction: 'Mentor a new AI Builder through Mission 1.',
  },
];

export function expandAiBuilderMissions(existing: AiBuilderMission[]): AiBuilderMission[] {
  const trackForExisting: Record<string, string> = {
    'homework-assistant': 'ai-for-school',
    'research-agent': 'ai-for-school',
    'business-assistant': 'ai-for-business',
    'website-builder': 'ai-for-creativity',
    'personal-ai-team': 'ai-automation',
  };

  const preserved = existing.map((m) => ({
    ...m,
    track: trackForExisting[m.slug] ?? 'ai-for-school',
    trackLabel: TRACK_LABELS[trackForExisting[m.slug] ?? 'ai-for-school'] ?? 'AI for School',
  }));

  const expanded = EXPANSION_BLUEPRINTS.map((bp) => buildImmersionMission(bp));
  const all = [...preserved, ...expanded] as AiBuilderMission[];
  return chainMissions(withTrackLabels(all, TRACK_LABELS)) as AiBuilderMission[];
}

export const AI_BUILDER_EXPERIENCES = [
  { slug: 'prompt-library', title: 'Prompt Library', description: 'Save and tag your best prompts', category: 'tool' as const, estimatedMinutes: 30, portfolioSection: 'experiments' },
  { slug: 'project-showcase', title: 'Project Showcase', description: 'Gallery of everything you shipped', category: 'journal' as const, estimatedMinutes: 20, href: '/ai-builder/portfolio' },
  { slug: 'automation-log', title: 'Automation Log', description: 'Track time saved per workflow', category: 'tracker' as const, estimatedMinutes: 15, portfolioSection: 'automations' },
  { slug: 'peer-review-queue', title: 'Peer Review Queue', description: 'Review 2 projects to get feedback on yours', category: 'pathway' as const, estimatedMinutes: 45, href: '/community/ai-builder' },
];

export const AI_BUILDER_IMMERSION: WorldImmersionMeta = {
  slug: 'ai-builder',
  displayName: 'AI Builder',
  missionTarget: 25,
  estimatedHours: '50+',
  tracks: [...AI_BUILDER_TRACKS],
  experiences: AI_BUILDER_EXPERIENCES,
};
