import type { WorldMission } from '../../../components/world/WorldMissionRunner';
import type { WorldImmersionMeta, ImmersionMissionBlueprint } from '../types';
import { buildImmersionMission, chainMissions, withTrackLabels } from '../mission-builder';

export const CHESS_TRACKS = [
  { slug: 'foundation', label: 'Foundation', description: 'Games, notation, tactics, repertoire, endgames', estimatedHours: '12+' },
  { slug: 'tactics', label: 'Tactics Lab', description: 'Calculation, combinations, pattern drills', estimatedHours: '8+' },
  { slug: 'structure', label: 'Structure', description: 'Openings, pawn structures, middlegame plans', estimatedHours: '10+' },
  { slug: 'competition', label: 'Competition', description: 'Rated play, tournaments, time management', estimatedHours: '10+' },
  { slug: 'mastery', label: 'Master Track', description: 'Study plans, teaching, norm milestones', estimatedHours: '15+' },
] as const;

const TRACK_LABELS = Object.fromEntries(CHESS_TRACKS.map((t) => [t.slug, t.label]));

const EXPANSION_BLUEPRINTS: ImmersionMissionBlueprint[] = [
  {
    slug: 'ten-post-mortems',
    number: 6,
    track: 'tactics',
    title: 'Post-Mortem Ten Games',
    subtitle: 'Name the blunder — engines confirm, they do not excuse',
    outcome: 'Ten games with one critical moment tagged per game',
    evidence: 'Post-mortem doc + one game where you found a better move',
    timeEstimate: '3 hours',
    requiredLevel: 'Tactician (Level 4)',
    futureProof: 'Club strength is built in review, not blitz alone.',
    tomorrowHook: 'Tomorrow: Mission 7 — study one pawn structure deeply.',
    missionFocus: 'Pick your last 10 games. For each: opening name, critical move, blunder or inaccuracy, lesson in one sentence.',
    buildChecklist: ['10 games selected', 'Critical moment tagged in each', 'One line you would play differently'],
    showArtifact: 'Save post-mortem summary to portfolio.',
    reflectPrompt: 'What mistake repeats — time trouble, opening gaps, hanging pieces?',
    improveAction: 'Pick one recurring blunder type and drill 20 puzzles on that theme.',
    mentorAction: 'Walk a beginner through one post-mortem — show the critical moment on the board.',
  },
  {
    slug: 'pawn-structure-study',
    number: 7,
    track: 'structure',
    title: 'Study One Pawn Structure',
    subtitle: 'Isolated queen pawn, Carlsbad, or French chain — pick one, go deep',
    outcome: 'Notes on plans for both sides in one structure + 3 model games',
    evidence: 'Structure study sheet + one game you played into the structure',
    timeEstimate: '2 hours',
    requiredLevel: 'Strategist (Level 5)',
    futureProof: 'Middlegame plans come from pawn skeletons, not memorized tricks.',
    tomorrowHook: 'Tomorrow: Mission 8 — basic rook endgames.',
    missionFocus: 'Choose IQP, Carlsbad, or French pawn chain. Document White plans, Black plans, typical piece placement, 3 model games.',
    buildChecklist: ['Structure chosen', 'Plans for both colors', '3 model games annotated lightly'],
    showArtifact: 'Save structure notes.',
    reflectPrompt: 'Which side do you understand better — and why?',
    improveAction: 'Play 5 games aiming to reach your structure.',
    mentorAction: 'Explain the structure plans to a club player in five minutes.',
  },
  {
    slug: 'rook-endgames',
    number: 8,
    track: 'structure',
    title: 'Rook Endgame Essentials',
    subtitle: 'Lucena, Philidor, and cutting off the king — technique wins draws',
    outcome: 'Can execute Philidor draw and Lucena win from standard setups',
    evidence: 'Drill log + one rook ending saved from a loss or stolen as a draw',
    timeEstimate: '90 min',
    requiredLevel: 'Strategist (Level 5)',
    futureProof: 'Rook endings appear constantly in club and tournament play.',
    tomorrowHook: 'Tomorrow: Mission 9 — calculation workout.',
    missionFocus: 'Study Lucena bridge and Philidor position. Drill 5 wins and 5 holds. Find one rook ending from your games.',
    buildChecklist: ['Lucena win demonstrated', 'Philidor hold demonstrated', 'One personal rook ending analyzed'],
    showArtifact: 'Save drill notes.',
    reflectPrompt: 'Did you know the idea before calculation or only after?',
    improveAction: 'Add one rook endgame to weekly study block.',
    mentorAction: 'Set up Philidor and ask a novice why the draw holds.',
  },
  {
    slug: 'calculation-workout',
    number: 9,
    track: 'tactics',
    title: 'Calculation Workout',
    subtitle: 'Three candidate moves, calculate to the end, then move',
    outcome: 'Ten positions solved with written variation trees (no moving pieces mid-calc)',
    evidence: 'Calculation journal + hardest position revisited',
    timeEstimate: '2 hours',
    requiredLevel: 'Tactician (Level 4)',
    futureProof: 'Calculation discipline separates quick improvers from plateaued players.',
    tomorrowHook: 'Tomorrow: Mission 10 — your first rated game.',
    missionFocus: 'Use a calculation book or hard puzzles. For each: list candidates, calculate fully, compare, choose. Log blind spots.',
    buildChecklist: ['10 positions', 'Variation written for each', 'One rechecked with engine after'],
    showArtifact: 'Save calculation journal excerpt.',
    reflectPrompt: 'Where did you stop calculating too early?',
    improveAction: 'One daily calculation exercise for two weeks.',
    mentorAction: 'Teach a friend the three-candidate-move method.',
  },
  {
    slug: 'first-rated-game',
    number: 10,
    track: 'competition',
    title: 'Play Your First Rated Game',
    subtitle: 'Baseline rating — proof, not verdict',
    outcome: 'One USCF/FIDE online or OTB rated game completed',
    evidence: 'Rating change or provisional rating screenshot + post-mortem',
    timeEstimate: '1–2 hours',
    requiredLevel: 'Competitor (Level 6)',
    futureProof: 'Rated play creates accountability and a graph worth studying.',
    tomorrowHook: 'Tomorrow: Mission 11 — club or online tournament.',
    missionFocus: 'Register if needed. Play one serious rated game (G/30+ or OTB). Full post-mortem within 24 hours.',
    buildChecklist: ['Rated game completed', 'Post-mortem written', 'Opening name recorded'],
    showArtifact: 'Save rating snapshot and PGN.',
    reflectPrompt: 'Time trouble? Opening prep? Endgame? Tag the loss or draw reason honestly.',
    improveAction: 'One opening gap to patch before next rated session.',
    mentorAction: 'Tell a beginner what rated play is for — measurement, not ego.',
  },
  {
    slug: 'first-tournament',
    number: 11,
    track: 'competition',
    title: 'Enter a Club or Online Tournament',
    subtitle: 'Multiple games, one day, real nerves',
    outcome: 'Completed tournament with scoresheet and energy log',
    evidence: 'Standings + 2 game post-mortems + one lesson for next event',
    timeEstimate: 'Half or full day',
    requiredLevel: 'Competitor (Level 6)',
    futureProof: 'Tournament stamina is a skill — round two is not round one.',
    tomorrowHook: 'Tomorrow: Mission 12 — time management drill.',
    missionFocus: 'Enter local club Swiss or online arena. Log energy between rounds. Post-mortem two games same day.',
    buildChecklist: ['Event completed', '2 post-mortems', 'Energy/focus note between rounds'],
    showArtifact: 'Save standings and notes.',
    reflectPrompt: 'Did quality drop in later rounds? Opening prep hold up?',
    improveAction: 'One pre-tournament checklist item (food, sleep, opening review).',
    mentorAction: 'Share tournament etiquette with someone entering their first event.',
  },
  {
    slug: 'time-management',
    number: 12,
    track: 'competition',
    title: 'Time Management Drill',
    subtitle: 'Budget minutes per move — flagging loses won games',
    outcome: 'Five games with time log at move 10, 20, and critical moment',
    evidence: 'Time log sheet + one game saved from time trouble',
    timeEstimate: '2–3 hours',
    requiredLevel: 'Competitor (Level 6)',
    futureProof: 'Clock management is worth rating points at every level below master.',
    tomorrowHook: 'Tomorrow: Mission 13 — weekly study plan.',
    missionFocus: 'Play 5 G/15 or G/30 games. Record clock at moves 10 and 20. Set rule: if under 5 min, simplify calculation.',
    buildChecklist: ['5 games logged', 'Time at move 10 and 20', 'One rule you followed under pressure'],
    showArtifact: 'Save time log.',
    reflectPrompt: 'Where do you burn time — opening, middlegame, or endgame?',
    improveAction: 'Set default think budget for your common time control.',
    mentorAction: 'Explain increment and delay to a new tournament player.',
  },
  {
    slug: 'weekly-study-plan',
    number: 13,
    track: 'mastery',
    title: 'Build a Weekly Study Plan',
    subtitle: 'Tactics, openings, endgames, games — blocks, not vibes',
    outcome: 'Written weekly schedule you follow for 3 weeks',
    evidence: 'Study plan doc + adherence log (hours per block)',
    timeEstimate: '60 min setup + 3 weeks',
    requiredLevel: 'Candidate (Level 7)',
    futureProof: 'Master-track players treat study like training — repeatable blocks.',
    tomorrowHook: 'Tomorrow: Mission 14 — teach a complete beginner.',
    missionFocus: 'Allocate: tactics daily, opening 2x/week, endgame 2x/week, game review 2x/week. Log adherence 3 weeks.',
    buildChecklist: ['Plan written', '3 weeks logged', 'One adjustment after week 1'],
    showArtifact: 'Save plan and log.',
    reflectPrompt: 'Which block do you skip when busy — and is that your leak?',
    improveAction: 'Protect your weakest block like a tournament round.',
    mentorAction: 'Share your plan template with the study circle.',
  },
  {
    slug: 'teach-beginner',
    number: 14,
    track: 'mastery',
    title: 'Teach a Complete Beginner',
    subtitle: 'Piece movement, check, checkmate — one hour, no overload',
    outcome: 'A novice plays a legal game after your lesson',
    evidence: 'Lesson outline + student plays legal moves through move 15',
    timeEstimate: '90 min',
    requiredLevel: 'Candidate (Level 7)',
    futureProof: 'Teaching forces clarity — the path to master passes through coaching.',
    tomorrowHook: 'Tomorrow: Mission 15 — lead a study session.',
    missionFocus: 'Lesson 1 only: board, pieces, check, checkmate, one game you supervise. Stop before opening theory.',
    buildChecklist: ['Lesson outline', 'Student completes partial game', 'One misconception corrected'],
    showArtifact: 'Save outline and feedback.',
    reflectPrompt: 'What did you explain too fast?',
    improveAction: 'Prepare lesson 2: castling and basic tactics.',
    mentorAction: 'Invite them to the Chess Study Circle when ready.',
  },
  {
    slug: 'lead-study-session',
    number: 15,
    track: 'mastery',
    title: 'Lead a Study Session',
    subtitle: 'Post-mortem circle, tactics sprint, or repertoire workshop',
    outcome: 'One hosted session with agenda and follow-up puzzle or game',
    evidence: 'Agenda + attendance + one shared analysis link or board photo',
    timeEstimate: '2 hours',
    requiredLevel: 'Master (Level 8)',
    futureProof: 'Masters grow communities — the guild remembers who ran study.',
    tomorrowHook: 'You are on the master track. Keep logging evidence. Set a rating or norm goal for the year.',
    missionFocus: 'Pick format: group post-mortem, 30-puzzle sprint, or repertoire Q&A. Send agenda 24h ahead. Run 60–90 min. Assign homework.',
    buildChecklist: ['Agenda sent', 'Session hosted', 'Homework assigned'],
    showArtifact: 'Save agenda and one takeaway quote from a participant.',
    reflectPrompt: 'What would make session 2 stronger?',
    improveAction: 'Schedule recurring monthly study — same day, same format.',
    mentorAction: 'Recruit a co-host for the next session.',
  },
];

export function expandChessMissions(existing: WorldMission[]): WorldMission[] {
  const built = EXPANSION_BLUEPRINTS.map((bp) => buildImmersionMission(bp));
  return withTrackLabels(chainMissions([...existing, ...built]), TRACK_LABELS);
}

export const CHESS_IMMERSION: WorldImmersionMeta = {
  slug: 'chess',
  displayName: 'Chess',
  missionTarget: 15,
  estimatedHours: '45+',
  tracks: [...CHESS_TRACKS],
  experiences: [
    { slug: 'game-log', title: 'Game Log', description: 'PGN, result, and post-mortem notes', category: 'journal', estimatedMinutes: 15 },
    { slug: 'tactics-trainer', title: 'Tactics Trainer', description: 'Daily puzzle streak and theme drills', category: 'tool', estimatedMinutes: 20 },
    { slug: 'repertoire-builder', title: 'Repertoire Builder', description: 'Opening lines and deviation notes', category: 'pathway', estimatedMinutes: 30 },
    { slug: 'endgame-lab', title: 'Endgame Lab', description: 'K+P, rook endings, technique drills', category: 'tool', estimatedMinutes: 25 },
    { slug: 'rating-tracker', title: 'Rating Tracker', description: 'Rated sessions and tournament log', category: 'tracker', estimatedMinutes: 10, href: '/chess/portfolio' },
    { slug: 'study-circle', title: 'Study Circle', description: 'Group post-mortems and sparring', category: 'explorer', href: '/chess/community' },
  ],
};
