import type { WorldMission } from '../../../components/world/WorldMissionRunner';
import type { WorldImmersionMeta, ImmersionMissionBlueprint } from '../types';
import { buildImmersionMission, chainMissions } from '../mission-builder';

export const CIVIC_TRACKS = [
  { slug: 'voting', label: 'Voting & Ballots', description: 'Research, decide, cast informed votes', estimatedHours: '6+' },
  { slug: 'local-gov', label: 'Local Government', description: 'Meetings, boards, commissions', estimatedHours: '10+' },
  { slug: 'advocacy', label: 'Advocacy & Policy', description: 'Issues, referendums, testimony', estimatedHours: '8+' },
  { slug: 'organizing', label: 'Community Organizing', description: 'Projects, volunteers, coalitions', estimatedHours: '10+' },
  { slug: 'leadership', label: 'Civic Leadership', description: 'Facilitate, mentor, sustain impact', estimatedHours: '8+' },
] as const;

const NEW_CIVIC: ImmersionMissionBlueprint[] = [
  { slug: 'register-voters', number: 6, track: 'Voting & Ballots', title: 'Register Voters or Pre-Register Peers', subtitle: 'Democracy starts with people on the rolls', outcome: 'Help 3 people check registration or pre-register if eligible', evidence: 'Log (no private data) + reflection on barriers found', timeEstimate: '90 min', requiredLevel: 'Informed Voter (Level 1)', futureProof: 'Registration drives win elections — organizing skill for life.', tomorrowHook: 'School board research mission.', missionFocus: 'Learn registration rules in your state. Help 3 people verify status or pre-register. Note common barriers.', buildChecklist: ['Learn local rules', 'Help 3 people', 'Log barriers'], showArtifact: 'Save anonymized log.', reflectPrompt: 'What stopped people from being registered?', improveAction: 'Share one resource widely.', mentorAction: 'Partner with a club on registration drive.' },
  { slug: 'school-board-research', number: 7, track: 'Local Government', title: 'Research Your School Board', subtitle: 'Who decides what happens in your school', outcome: 'School board member profiles + one upcoming decision', evidence: 'Research doc + meeting date on calendar', timeEstimate: '60 min', requiredLevel: 'Local Participant (Level 2)', futureProof: 'Local education policy affects you for 12 years — know who leads.', tomorrowHook: 'Attend commission meeting.', missionFocus: 'List board members, terms, recent votes. Find one upcoming agenda item. Attend or watch one meeting clip.', buildChecklist: ['Profile members', 'Find upcoming item', 'Watch or attend clip'], showArtifact: 'Save research doc.', reflectPrompt: 'What decision surprised you?', improveAction: 'Submit one public comment (written is fine).', mentorAction: 'Explain board role to a younger student.' },
  { slug: 'commission-meeting', number: 8, track: 'Local Government', title: 'Attend a Commission Meeting', subtitle: 'Planning, zoning, parks — where boring becomes powerful', outcome: 'Notes from one commission meeting + one issue tracked', evidence: 'Meeting notes + follow-up action', timeEstimate: '90 min', requiredLevel: 'Local Participant (Level 2)', futureProof: 'Commissions decide sidewalks, housing, and parks — show up.', tomorrowHook: 'Referendum deep dive.', missionFocus: 'Find planning or parks commission calendar. Attend or watch stream. Take notes on one decision.', buildChecklist: ['Find meeting', 'Take notes', 'Identify one follow-up'], showArtifact: 'Save notes to portfolio.', reflectPrompt: 'Who spoke from the public?', improveAction: 'Email one question to staff.', mentorAction: 'Bring a friend to next meeting.' },
  { slug: 'referendum-deep-dive', number: 9, track: 'Advocacy & Policy', title: 'Deep Dive One Referendum or Ballot Measure', subtitle: 'Primary sources, fiscal impact, opposing views', outcome: 'A pro/con memo you could defend in debate', evidence: 'Memo + 3 primary sources cited', timeEstimate: '90 min', requiredLevel: 'Informed Voter (Level 1)', futureProof: 'Referendums bind law — shallow takes have long consequences.', tomorrowHook: 'Advocacy letter mission.', missionFocus: 'Pick one measure. Read official text, fiscal note, and best opposing op-eds. Write balanced memo.', buildChecklist: ['Read official text', 'Find fiscal impact', 'Write pro/con memo'], showArtifact: 'Save memo.', reflectPrompt: 'What would change your vote?', improveAction: 'Discuss with someone who disagrees.', mentorAction: 'Present memo at dinner.' },
  { slug: 'advocacy-letter', number: 10, track: 'Advocacy & Policy', title: 'Write and Send an Advocacy Letter', subtitle: 'To a representative about an issue you researched', outcome: 'One sent letter or email with specific ask', evidence: 'Copy of letter + send confirmation', timeEstimate: '60 min', requiredLevel: 'Project Organizer (Level 4)', futureProof: 'Elected officials count contacts — your letter is data.', tomorrowHook: 'Campaign volunteer shift.', missionFocus: 'Pick issue from prior research. Write letter: fact, story, specific ask. Send to correct official.', buildChecklist: ['Identify official', 'Write letter', 'Send and log'], showArtifact: 'Save letter copy.', reflectPrompt: 'Was your ask specific enough?', improveAction: 'Follow up in 2 weeks if no reply.', mentorAction: 'Help peer send their first letter.' },
  { slug: 'campaign-volunteer', number: 11, track: 'Community Organizing', title: 'Volunteer on a Campaign Shift', subtitle: 'Canvass, phone bank, or event — see campaigns from inside', outcome: 'One completed volunteer shift + reflection', evidence: 'Shift log + one thing you learned about voters', timeEstimate: '3 hours', requiredLevel: 'Community Volunteer (Level 3)', futureProof: 'Campaigns are MBA programs for civic leaders.', tomorrowHook: 'Coalition building mission.', missionFocus: 'Sign up for one shift with a campaign or cause you support. Complete shift. Reflect on voter/citizen conversations.', buildChecklist: ['Sign up for shift', 'Complete shift', 'Write reflection'], showArtifact: 'Save shift log.', reflectPrompt: 'What surprised you about voters?', improveAction: 'Sign up for second shift OR recruit one volunteer.', mentorAction: 'Debrief with campaign staff if possible.' },
  { slug: 'coalition-building', number: 12, track: 'Community Organizing', title: 'Build a Mini Coalition', subtitle: '3 groups aligned on one local issue', outcome: 'Coalition map: groups, contacts, shared goal', evidence: 'Coalition one-pager + one outreach sent', timeEstimate: '90 min', requiredLevel: 'Project Organizer (Level 4)', futureProof: 'Power is organized people — coalitions multiply impact.', tomorrowHook: 'Sustainability plan mission.', missionFocus: 'Define issue. Identify 3 groups (club, church, nonprofit). Draft shared ask. Contact one leader.', buildChecklist: ['Define issue', 'Map 3 groups', 'Send one outreach'], showArtifact: 'Save coalition map.', reflectPrompt: 'Where do incentives align?', improveAction: 'Schedule one intro call.', mentorAction: 'Present map to Civic Action Circle.' },
  { slug: 'civic-sustainability-plan', number: 13, track: 'Civic Leadership', title: 'Write a 90-Day Civic Sustainability Plan', subtitle: 'How you will stay engaged after the election cycle', outcome: 'A calendar with monthly civic actions', evidence: '90-day plan + first month scheduled', timeEstimate: '60 min', requiredLevel: 'Civic Leader (Level 5)', futureProof: 'Sustained engagement beats viral moments.', tomorrowHook: 'Mentor a first-time voter.', missionFocus: 'Schedule monthly actions: meeting, volunteer, letter, registration help. Block calendar.', buildChecklist: ['List 6 actions', 'Put on calendar', 'Complete first action'], showArtifact: 'Save plan.', reflectPrompt: 'What will you skip when busy?', improveAction: 'Add accountability partner.', mentorAction: 'Share plan with Civic Circle mentor.' },
  { slug: 'mentor-first-voter', number: 14, track: 'Civic Leadership', title: 'Mentor a First-Time Voter', subtitle: 'Walk someone through ballot research and voting plan', outcome: 'One mentee completes ballot research with you', evidence: 'Anonymized checklist + mentor reflection', timeEstimate: '90 min', requiredLevel: 'Civic Mentor (Level 6)', futureProof: 'Teaching civic duty multiplies democracy.', tomorrowHook: 'Leadership capstone mission.', missionFocus: 'Pair with first-time voter. Use your ballot research method. Answer questions. Plan vote day.', buildChecklist: ['Pair with mentee', 'Complete research together', 'Plan vote/logistics'], showArtifact: 'Save mentor reflection.', reflectPrompt: 'What question stumped you?', improveAction: 'Create FAQ for next mentee.', mentorAction: 'Log session in Civic Circle.' },
  { slug: 'civic-leadership-capstone', number: 15, track: 'Civic Leadership', title: 'Lead a Civic Leadership Capstone', subtitle: 'Facilitate one conversation that ends with commitments', outcome: 'Facilitated session with agenda, notes, and 3 commitments', evidence: 'Agenda + commitments log', timeEstimate: '2 hours', requiredLevel: 'Community Steward (Level 7)', futureProof: 'Leaders create action — not just awareness.', tomorrowHook: 'Sustain in Civic Action Circle year-round.', missionFocus: 'Design 45-min session on local issue. Facilitate 4+ people. Capture commitments with owners and dates.', buildChecklist: ['Design agenda', 'Facilitate session', 'Log 3 commitments'], showArtifact: 'Save agenda + commitments.', reflectPrompt: 'Which commitment will actually happen?', improveAction: 'Follow up in one week.', mentorAction: 'Train next facilitator.' },
];

export function expandCivicMissions(existing: WorldMission[]): WorldMission[] {
  return chainMissions([...existing, ...NEW_CIVIC.map((bp) => buildImmersionMission(bp))]);
}

export const CIVIC_IMMERSION: WorldImmersionMeta = {
  slug: 'civic-engagement',
  displayName: 'Civic Engagement',
  missionTarget: 15,
  estimatedHours: '45+',
  tracks: [...CIVIC_TRACKS],
  experiences: [
    { slug: 'ballot-builder', title: 'Ballot Builder', description: 'Research template for every election', category: 'tool', estimatedMinutes: 45, portfolioSection: 'projects' },
    { slug: 'meeting-notes-journal', title: 'Meeting Notes Journal', description: 'Every council meeting you attend', category: 'journal', estimatedMinutes: 20 },
    { slug: 'civic-calendar', title: 'Civic Calendar', description: 'Elections, meetings, deadlines', category: 'tracker', estimatedMinutes: 15 },
    { slug: 'volunteer-log', title: 'Volunteer Log', description: 'Hours and impact tracking', category: 'tracker', estimatedMinutes: 10 },
  ],
};
