import type { WorldMission } from '../../../components/world/WorldMissionRunner';
import type { WorldImmersionMeta, ImmersionMissionBlueprint } from '../types';
import { buildImmersionMission, chainMissions } from '../mission-builder';

export const FI_TRACKS = [
  { slug: 'money-foundations', label: 'Money Foundations', description: 'Budget, save, understand cash flow', estimatedHours: '8+' },
  { slug: 'banking-credit', label: 'Banking & Credit', description: 'Accounts, credit scores, debt', estimatedHours: '6+' },
  { slug: 'investing', label: 'Investing', description: 'Stocks, funds, thesis, portfolio', estimatedHours: '10+' },
  { slug: 'business', label: 'Business & Side Income', description: 'Earn, price, track profit', estimatedHours: '8+' },
  { slug: 'retirement', label: 'Retirement & Real Estate', description: 'Long horizon planning', estimatedHours: '6+' },
] as const;

const NEW_FI: ImmersionMissionBlueprint[] = [
  { slug: 'net-worth-tracker', number: 6, track: 'Money Foundations', title: 'Build Your Net Worth Tracker', subtitle: 'Assets minus debts — one number that tells the truth', outcome: 'A monthly net worth snapshot you update', evidence: 'Tracker screenshot (redact account numbers)', timeEstimate: '60 min', requiredLevel: 'Budget Builder (Level 2)', futureProof: 'What gets measured gets managed.', tomorrowHook: 'Tomorrow: banking setup mission.', missionFocus: 'List assets (cash, investments) and debts. Calculate net worth. Set monthly update reminder.', buildChecklist: ['List all accounts', 'Calculate net worth', 'Set monthly reminder'], showArtifact: 'Save tracker to portfolio.', reflectPrompt: 'What surprised you about the number?', improveAction: 'Add one goal line for 6 months out.', mentorAction: 'Explain net worth to a sibling.' },
  { slug: 'emergency-fund-plan', number: 7, track: 'Money Foundations', title: 'Build an Emergency Fund Plan', subtitle: '3–6 months of security — your first real safety net', outcome: 'A funded plan with target amount and timeline', evidence: 'Plan doc + first transfer receipt', timeEstimate: '45 min', requiredLevel: 'Saver (Level 3)', futureProof: 'Emergencies happen — buffers prevent panic.', tomorrowHook: 'Tomorrow: banking mission.', missionFocus: 'Calculate 1-month essential expenses. Set 3-month target. Automate first deposit.', buildChecklist: ['Calculate monthly essentials', 'Set target amount', 'Automate first deposit'], showArtifact: 'Save plan to portfolio.', reflectPrompt: 'What would you cut in a crisis?', improveAction: 'Increase auto-transfer by $5.', mentorAction: 'Discuss with a parent where fund should live.' },
  { slug: 'bank-account-setup', number: 8, track: 'Banking & Credit', title: 'Master Your Bank Accounts', subtitle: 'Checking, savings, fees, and features that matter', outcome: 'A documented account map with fee avoidance rules', evidence: 'Account map (no account numbers)', timeEstimate: '45 min', requiredLevel: 'Money Explorer (Level 1)', futureProof: 'Bank fees are silent wealth killers.', tomorrowHook: 'Tomorrow: credit score basics.', missionFocus: 'Document every account type you have or need. List fees, minimums, and one optimization.', buildChecklist: ['Map accounts', 'List fees', 'Find one fee to eliminate'], showArtifact: 'Save account map.', reflectPrompt: 'Which account is for what purpose?', improveAction: 'Enable one alert (low balance or large purchase).', mentorAction: 'Compare notes with a parent.' },
  { slug: 'credit-score-basics', number: 9, track: 'Banking & Credit', title: 'Understand Your Credit Score', subtitle: 'What it is, why it matters, how to build it safely', outcome: 'A credit action plan with 3 healthy habits', evidence: 'Action plan + one resource link', timeEstimate: '60 min', requiredLevel: 'Budget Builder (Level 2)', futureProof: 'Credit unlocks housing, cars, and business — build early, build slow.', tomorrowHook: 'Tomorrow: debt payoff strategy.', missionFocus: 'Research credit score factors. Write 3 habits you will follow (authorized user, on-time payments, low utilization).', buildChecklist: ['List 5 score factors', 'Write 3 habits', 'Find one free education resource'], showArtifact: 'Save action plan.', reflectPrompt: 'What mistake costs teens the most?', improveAction: 'Set payment reminder for one bill.', mentorAction: 'Ask a parent when they learned about credit.' },
  { slug: 'debt-payoff-strategy', number: 10, track: 'Banking & Credit', title: 'Build a Debt Payoff Strategy', subtitle: 'Snowball or avalanche — pick a plan and stick to it', outcome: 'A payoff plan for real or practice debt', evidence: 'Payoff table + first payment log', timeEstimate: '60 min', requiredLevel: 'Saver (Level 3)', futureProof: 'Debt discipline transfers to every financial decision.', tomorrowHook: 'Investing track next.', missionFocus: 'List debts with rates and balances. Choose snowball or avalanche. Schedule payments.', buildChecklist: ['List all debts', 'Choose method', 'Schedule payments'], showArtifact: 'Save payoff table.', reflectPrompt: 'Which method fits your psychology?', improveAction: 'Add $10 to next payment.', mentorAction: 'Explain strategy to a friend.' },
  { slug: 'investment-thesis', number: 11, track: 'Investing', title: 'Write Your Investment Thesis', subtitle: 'Why you buy what you buy — before you buy more', outcome: 'A one-page thesis for one company or fund', evidence: 'Thesis doc + 3 supporting facts you verified', timeEstimate: '90 min', requiredLevel: 'Investor (Level 4)', futureProof: 'Investors without thesis are gamblers.', tomorrowHook: 'Tomorrow: portfolio rebalance.', missionFocus: 'Pick one holding or watchlist item. Write bull case, bear case, and hold period. Verify 3 facts without AI.', buildChecklist: ['Pick investment', 'Write bull/bear case', 'Verify 3 facts manually'], showArtifact: 'Save thesis.', reflectPrompt: 'What would change your mind?', improveAction: 'Set review date in 90 days.', mentorAction: 'Present thesis in 2 minutes.' },
  { slug: 'portfolio-rebalance', number: 12, track: 'Investing', title: 'Rebalance Your Portfolio', subtitle: 'Allocation, risk, and when to adjust', outcome: 'Target allocation + rebalance plan', evidence: 'Before/after allocation chart', timeEstimate: '75 min', requiredLevel: 'Wealth Planner (Level 5)', futureProof: 'Rebalancing is discipline — not timing the market.', tomorrowHook: 'Side income mission.', missionFocus: 'Define target % for stocks/bonds/cash (or practice portfolio). Compare to current. Plan one rebalance step.', buildChecklist: ['Set target allocation', 'Compare current', 'Plan one trade or transfer'], showArtifact: 'Save allocation chart.', reflectPrompt: 'Does allocation match your time horizon?', improveAction: 'Automate next contribution.', mentorAction: 'Discuss risk with a parent.' },
  { slug: 'side-income-plan', number: 13, track: 'Business & Side Income', title: 'Build a Side Income Plan', subtitle: 'Earn $50–$500/month with a skill you have', outcome: 'A 30-day side income experiment plan', evidence: 'Plan + one customer conversation note', timeEstimate: '90 min', requiredLevel: 'Wealth Strategist (Level 6)', futureProof: 'Income diversification beats single-paycheck fragility.', tomorrowHook: 'Tax basics next.', missionFocus: 'List 3 skills. Pick one offer. Price it. Identify 5 potential customers. Talk to one.', buildChecklist: ['Define offer', 'Set price', 'Talk to one prospect'], showArtifact: 'Save plan + conversation notes.', reflectPrompt: 'What objection did you hear?', improveAction: 'Adjust offer based on feedback.', mentorAction: 'Help a peer price their first offer.' },
  { slug: 'tax-basics-teens', number: 14, track: 'Business & Side Income', title: 'Learn Tax Basics for Earners', subtitle: 'W-2, 1099, deductions — what teens actually need', outcome: 'A tax checklist for your income situation', evidence: 'Checklist + one question for a parent or CPA', timeEstimate: '60 min', requiredLevel: 'Wealth Strategist (Level 6)', futureProof: 'Tax surprises destroy side hustles — learn early.', tomorrowHook: 'Retirement projection mission.', missionFocus: 'Research your situation: allowance, job, side gig. List forms you might receive. Write 5 questions for an adult.', buildChecklist: ['Identify income types', 'List possible forms', 'Write 5 questions'], showArtifact: 'Save checklist.', reflectPrompt: 'What is still confusing?', improveAction: 'Schedule tax conversation with parent.', mentorAction: 'Share checklist with a working friend.' },
  { slug: 'retirement-projection', number: 15, track: 'Retirement & Real Estate', title: 'Build a Retirement Projection', subtitle: 'Compound interest visualized — start at 16, not 36', outcome: 'A projection chart with monthly contribution scenarios', evidence: 'Chart + reflection on $100/month habit', timeEstimate: '60 min', requiredLevel: 'Wealth Planner (Level 5)', futureProof: 'Time is the asset — teens have more of it than anyone.', tomorrowHook: 'Explore real estate basics mission.', missionFocus: 'Use compound calculator. Model $50, $100, $200/month from now to 65. Pick one habit to start.', buildChecklist: ['Run 3 scenarios', 'Pick monthly amount', 'Set up auto-invest or savings'], showArtifact: 'Save chart screenshot.', reflectPrompt: 'What would you trade today for future you?', improveAction: 'Increase contribution by $5.', mentorAction: 'Show a parent your chart — ask what they wish they started.' },
];

export function expandFiMissions(existing: WorldMission[]): WorldMission[] {
  const built = NEW_FI.map((bp) => buildImmersionMission(bp));
  return chainMissions([...existing, ...built]);
}

export const FI_IMMERSION: WorldImmersionMeta = {
  slug: 'financial-independence',
  displayName: 'Financial Independence',
  missionTarget: 15,
  estimatedHours: '40+',
  tracks: [...FI_TRACKS],
  experiences: [
    { slug: 'net-worth-dashboard', title: 'Net Worth Dashboard', description: 'Monthly snapshot tracker', category: 'tracker', estimatedMinutes: 20, portfolioSection: 'projects' },
    { slug: 'budget-calculator', title: 'Budget Calculator', description: 'Rolling monthly budget', category: 'tool', estimatedMinutes: 30, href: '/financial-independence/portfolio' },
    { slug: 'investment-journal', title: 'Investment Journal', description: 'Thesis + decision log', category: 'journal', estimatedMinutes: 25, portfolioSection: 'projects' },
  ],
};
