import type { WorldMission } from '../../../components/world/WorldMissionRunner';
import type { WorldImmersionMeta, ImmersionMissionBlueprint } from '../types';
import { buildImmersionMission, chainMissions } from '../mission-builder';

export const PS_TRACKS = [
  { slug: 'conversation', label: 'Conversation', description: 'Everyday confidence in dialogue', estimatedHours: '6+' },
  { slug: 'storytelling', label: 'Storytelling', description: 'Structure, emotion, memorable arcs', estimatedHours: '8+' },
  { slug: 'presentations', label: 'Presentations', description: 'Slides, demos, recorded talks', estimatedHours: '10+' },
  { slug: 'leadership', label: 'Leadership Communication', description: 'Facilitate, persuade, lead rooms', estimatedHours: '8+' },
  { slug: 'performance', label: 'Performance', description: 'Debate, podcast, interview, teach', estimatedHours: '8+' },
] as const;

const NEW_PS: ImmersionMissionBlueprint[] = [
  { slug: 'daily-conversation-challenge', number: 6, track: 'Conversation', title: '7-Day Conversation Challenge', subtitle: 'One intentional conversation daily — strangers, peers, adults', outcome: 'A log of 7 conversations with one skill practiced each day', evidence: 'Conversation log + best moment story', timeEstimate: '7×15 min', requiredLevel: 'Speaker (Level 2)', futureProof: 'Confidence is reps — not talent.', tomorrowHook: 'Tomorrow: active listening mission.', missionFocus: 'Each day: one conversation with a goal (ask, listen, clarify). Log one sentence per day.', buildChecklist: ['Complete 7 days', 'Note hardest day', 'Write best moment'], showArtifact: 'Save log to portfolio.', reflectPrompt: 'Which skill improved most?', improveAction: 'Repeat hardest scenario once.', mentorAction: 'Debrief with a parent.' },
  { slug: 'active-listening-lab', number: 7, track: 'Conversation', title: 'Active Listening Lab', subtitle: 'Repeat back, ask follow-ups, avoid interrupting', outcome: '3 practiced conversations using listening techniques', evidence: 'Reflection on one conversation you improved', timeEstimate: '45 min', requiredLevel: 'Speaker (Level 2)', futureProof: 'Leaders listen first — audiences trust listeners.', tomorrowHook: 'Storytelling track.', missionFocus: 'Use repeat-back and one follow-up question in 3 conversations. Note reactions.', buildChecklist: ['Practice repeat-back 3 times', 'Ask 3 follow-ups', 'Write reactions'], showArtifact: 'Save reflection.', reflectPrompt: 'When did you want to interrupt?', improveAction: 'Practice one silence pause.', mentorAction: 'Teach technique to a friend.' },
  { slug: 'story-structure-workshop', number: 8, track: 'Storytelling', title: 'Story Structure Workshop', subtitle: 'Hook, struggle, turn, lesson — every great talk uses this', outcome: 'One story outlined in 4 beats + 2-minute delivery', evidence: 'Outline + recording or live delivery notes', timeEstimate: '75 min', requiredLevel: 'Storyteller (Level 3)', futureProof: 'Stories change minds — structure makes them land.', tomorrowHook: 'Personal story mission.', missionFocus: 'Pick true story. Map hook/struggle/turn/lesson. Deliver in 2 minutes to one person.', buildChecklist: ['Write 4 beats', 'Practice twice', 'Deliver once'], showArtifact: 'Save outline + feedback notes.', reflectPrompt: 'Which beat was weakest?', improveAction: 'Strengthen hook with specific detail.', mentorAction: 'Coach a peer on their outline.' },
  { slug: 'personal-origin-story', number: 9, track: 'Storytelling', title: 'Craft Your Origin Story', subtitle: 'Who you are, where you are going — in 3 minutes', outcome: 'A polished origin story for interviews and introductions', evidence: 'Script + one delivery recording or audience feedback', timeEstimate: '90 min', requiredLevel: 'Storyteller (Level 3)', futureProof: 'People hire and follow humans — not résumés.', tomorrowHook: '10-minute talk mission.', missionFocus: 'Write origin story: past, pivot, future. Cut to 3 minutes. Record or present.', buildChecklist: ['Draft script', 'Cut to 3 min', 'Deliver to audience of 1+'], showArtifact: 'Save script + feedback.', reflectPrompt: 'What felt inauthentic?', improveAction: 'Remove one cliché sentence.', mentorAction: 'Use story in a real introduction this week.' },
  { slug: 'ten-minute-talk', number: 10, track: 'Presentations', title: 'Deliver a 10-Minute Talk', subtitle: 'Double your first talk — same clarity, more depth', outcome: 'A 10-minute talk with outline, rehearsal log, and delivery', evidence: 'Outline + audience feedback form', timeEstimate: '2–3 hours', requiredLevel: 'Presenter (Level 4)', futureProof: 'Ten minutes is the unit of conference talks, pitches, and classes.', tomorrowHook: 'Recorded presentation mission.', missionFocus: 'Choose topic you care about. Build 10-min outline (3 sections). Rehearse with timer. Deliver.', buildChecklist: ['Build outline', 'Rehearse 3 times', 'Deliver to 3+ people'], showArtifact: 'Save outline + feedback.', reflectPrompt: 'Where did you rush?', improveAction: 'Cut 20% of content.', mentorAction: 'Host mini talk for 2 friends.' },
  { slug: 'recorded-presentation', number: 11, track: 'Presentations', title: 'Record a Polished Presentation', subtitle: 'Camera, lighting, slides — ship a video talk', outcome: 'A recorded 5–10 minute presentation uploaded or shared', evidence: 'Video link or file + self-review notes', timeEstimate: '2 hours', requiredLevel: 'Presenter (Level 4)', futureProof: 'Remote work runs on recorded communication.', tomorrowHook: 'Town hall mission.', missionFocus: 'Record presentation with slides or single camera. Watch once. Fix audio or pacing issue. Share link.', buildChecklist: ['Record draft', 'Self-review', 'Fix one issue and re-record OR publish draft'], showArtifact: 'Link in portfolio.', reflectPrompt: 'What would you fix with one more hour?', improveAction: 'Improve thumbnail or title.', mentorAction: 'Swap videos with a peer for feedback.' },
  { slug: 'town-hall-talk', number: 12, track: 'Leadership Communication', title: 'Speak at a Town Hall or Meeting', subtitle: 'Public comment, club report, or class presentation', outcome: 'One real speaking slot in a group decision context', evidence: 'Agenda item + 3-sentence impact reflection', timeEstimate: '90 min', requiredLevel: 'Leader (Level 5)', futureProof: 'Civic and organizational voice starts at the mic.', tomorrowHook: 'Panel discussion prep.', missionFocus: 'Get on agenda: school board comment, club update, or class Q&A. Prepare 2 minutes. Deliver.', buildChecklist: ['Secure speaking slot', 'Prepare remarks', 'Deliver and log reaction'], showArtifact: 'Save agenda proof + reflection.', reflectPrompt: 'Who did you represent?', improveAction: 'Follow up with one stakeholder.', mentorAction: 'Encourage someone else to speak next time.' },
  { slug: 'panel-discussion', number: 13, track: 'Leadership Communication', title: 'Participate in a Panel Discussion', subtitle: 'Prepare soundbites, handoffs, and disagreement with grace', outcome: 'Panel prep doc + participation in mock or real panel', evidence: 'Prep doc + one quote you landed', timeEstimate: '75 min', requiredLevel: 'Leader (Level 5)', futureProof: 'Panels are how experts appear — preparation is the secret.', tomorrowHook: 'Debate mission.', missionFocus: 'Define 3 soundbites. Practice handoffs. Run mock panel with 2 friends or join real panel.', buildChecklist: ['Write 3 soundbites', 'Practice handoffs', 'Participate in panel'], showArtifact: 'Save prep doc.', reflectPrompt: 'When did you defer too much?', improveAction: 'Add one contrarian soundbite.', mentorAction: 'Moderate a 3-person mock panel.' },
  { slug: 'debate-round', number: 14, track: 'Performance', title: 'Complete a Debate Round', subtitle: 'Claim, evidence, rebuttal — structured disagreement', outcome: 'One debate with prep brief and rebuttal notes', evidence: 'Prep brief + outcome reflection', timeEstimate: '90 min', requiredLevel: 'Leader (Level 5)', futureProof: 'Debate trains thinking under pressure — not winning arguments.', tomorrowHook: 'Podcast guest prep.', missionFocus: 'Pick resolution. Research both sides. Write opening, 2 evidence points, rebuttal. Debate with peer.', buildChecklist: ['Research both sides', 'Write opening', 'Complete one round'], showArtifact: 'Save brief.', reflectPrompt: 'Strongest counter you faced?', improveAction: 'Steel-man opposing view in writing.', mentorAction: 'Judge a peer debate.' },
  { slug: 'podcast-guest-prep', number: 15, track: 'Performance', title: 'Prepare as a Podcast Guest', subtitle: 'Talking points, stories, and bridge phrases', outcome: 'Guest prep sheet + mock interview recorded', evidence: 'Prep sheet + 5-minute mock recording', timeEstimate: '60 min', requiredLevel: 'Mentor (Level 7)', futureProof: 'Podcasts are the new resume — guest skills transfer everywhere.', tomorrowHook: 'Teach-back mission or mentor a new speaker.', missionFocus: 'Write 5 talking points, 2 stories, 3 bridge phrases. Record mock interview with friend.', buildChecklist: ['Write talking points', 'Record mock interview', 'Review pacing'], showArtifact: 'Save prep + recording link.', reflectPrompt: 'Where did you ramble?', improveAction: 'Cut one talking point.', mentorAction: 'Interview a peer for their mock podcast.' },
];

export function expandPsMissions(existing: WorldMission[]): WorldMission[] {
  return chainMissions([...existing, ...NEW_PS.map((bp) => buildImmersionMission(bp))]);
}

export const PS_IMMERSION: WorldImmersionMeta = {
  slug: 'public-speaking',
  displayName: 'Public Speaking',
  missionTarget: 15,
  estimatedHours: '40+',
  tracks: [...PS_TRACKS],
  experiences: [
    { slug: 'speaking-portfolio', title: 'Speaking Portfolio', description: 'Talks, recordings, reflections', category: 'journal', estimatedMinutes: 20, href: '/public-speaking/portfolio' },
    { slug: 'rehearsal-timer', title: 'Rehearsal Timer', description: 'Timed practice log', category: 'tracker', estimatedMinutes: 15 },
    { slug: 'feedback-wall', title: 'Feedback Wall', description: 'Peer notes from Speaker Circle', category: 'pathway', estimatedMinutes: 30, href: '/community/public-speaking' },
  ],
};
