import fs from 'node:fs';
import path from 'node:path';
import { getFullBlueprint } from './blueprints/index.js';
import { componentFolder, slugToConst, slugToPascal, worldLibBasename } from './naming.js';
import {
  ensureDir,
  getRepoRoot,
  marketingRoot,
  platformRoot,
  writeFileIfChanged,
} from './paths.js';
import type { FullWorldBlueprint, WorldFactoryManifest } from './types.js';

export type GenerateWorldResult = {
  slug: string;
  displayName: string;
  filesWritten: string[];
  filesSkipped: string[];
  corePromiseAppended: boolean;
  worldLibCreated: boolean;
};

const MANIFEST_PATH = () =>
  path.join(platformRoot(), 'lib/generated/world-factory-manifest.json');
const ROUTES_PATH = () =>
  path.join(platformRoot(), 'lib/generated/world-factory-routes.ts');
const EXPLORE_PATH = () =>
  path.join(platformRoot(), 'lib/generated/world-factory-explore.ts');

export function loadManifest(): WorldFactoryManifest {
  const file = MANIFEST_PATH();
  if (!fs.existsSync(file)) {
    return { generated_at: new Date().toISOString(), domains: [] };
  }
  return JSON.parse(fs.readFileSync(file, 'utf8')) as WorldFactoryManifest;
}

export function saveManifestSlugs(slugs: string[]): void {
  const unique = [...new Set(slugs)].sort();
  const manifest: WorldFactoryManifest = {
    generated_at: new Date().toISOString(),
    domains: unique,
  };
  ensureDir(path.dirname(MANIFEST_PATH()));
  fs.writeFileSync(MANIFEST_PATH(), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
}

function track(
  filePath: string,
  content: string,
  written: string[],
  skipped: string[],
): void {
  if (writeFileIfChanged(filePath, content)) written.push(filePath);
  else skipped.push(filePath);
}

function relImportDepth(fromDir: string, toFile: string): string {
  const rel = path.relative(fromDir, toFile).replace(/\\/g, '/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

function libImport(fromAppFile: string, slug: string): string {
  const lib = path.join(platformRoot(), `lib/${worldLibBasename(slug)}.ts`);
  const noExt = relImportDepth(path.dirname(fromAppFile), lib).replace(/\.ts$/, '');
  return noExt;
}

function metaImport(fromAppFile: string, slug: string): string {
  const meta = path.join(platformRoot(), `lib/${worldLibBasename(slug)}-meta.ts`);
  const noExt = relImportDepth(path.dirname(fromAppFile), meta).replace(/\.ts$/, '');
  return noExt;
}

function componentImport(fromAppFile: string, slug: string, component: string): string {
  const comp = path.join(platformRoot(), `components/${componentFolder(slug)}/${component}.tsx`);
  const noExt = relImportDepth(path.dirname(fromAppFile), comp).replace(/\.tsx$/, '');
  return noExt;
}

function missionGetterName(slug: string): string {
  return `get${slugToPascal(slug)}Mission`;
}

function generateWorldMeta(bp: FullWorldBlueprint, written: string[], skipped: string[]): void {
  const c = slugToConst(bp.slug);
  const file = path.join(platformRoot(), `lib/${worldLibBasename(bp.slug)}-meta.ts`);
  const playground = bp.playgroundLabs
    .map(
      (lab) =>
        `  { slug: '${lab.slug}', title: '${lab.title}', description: 'Practice ${lab.title.toLowerCase()} — unlocks at academy level ${lab.unlockLevel}.', unlockLevel: ${lab.unlockLevel} },`,
    )
    .join('\n');
  const portfolio = bp.portfolioSections
    .map(
      (s) =>
        `  { slug: '${s.slug}', title: '${s.title}', description: '${s.description.replace(/'/g, "\\'")}' },`,
    )
    .join('\n');
  const glossary = bp.glossaryTerms
    .map((g) => `  { term: '${g.term}', definition: '${g.definition.replace(/'/g, "\\'")}' },`)
    .join('\n');
  const careers = bp.careerPaths
    .map(
      (c) =>
        `  { title: '${c.title}', connection: '${c.description.replace(/'/g, "\\'")}' },`,
    )
    .join('\n');

  const content = `/** ${bp.displayName} World meta — generated by @foundry/world-factory (PASS-024) */

export const ${c}_PLAYGROUND_LABS = [
${playground}
];

export const ${c}_PORTFOLIO_SECTIONS = [
${portfolio}
];

export const ${c}_PARENT_VIEW = {
  headline: '${bp.parentHeadline.replace(/'/g, "\\'")}',
  oneLiner: '${bp.parentOneLiner.replace(/'/g, "\\'")}',
  sections: [
    { title: 'Why this matters now', body: '${bp.parentOneLiner.replace(/'/g, "\\'")}' },
    { title: 'Skills that transfer', body: '${bp.frame} — ${bp.outcomeStatement}. Real missions, not worksheets.' },
    { title: 'What your child is building', body: 'Five missions culminating in ${bp.outcomeStatement.toLowerCase()} — documented in ${bp.portfolioLabel}.' },
    { title: 'How progress is measured', body: 'Evidence documents · Reflections · Portfolio artifacts — not test scores.' },
  ],
};

export const ${c}_CAREERS = [
${careers}
];

export const ${c}_GLOSSARY = [
${glossary}
];
`;
  track(file, content, written, skipped);
}

function generateCivicWorldLib(bp: FullWorldBlueprint, written: string[], skipped: string[]): boolean {
  const file = path.join(platformRoot(), `lib/${worldLibBasename(bp.slug)}.ts`);
  if (fs.existsSync(file)) return false;

  const c = slugToConst(bp.slug);
  const getter = missionGetterName(bp.slug);
  const phases = ['Mission', 'Build', 'Show', 'Reflect', 'Improve', 'Mentor'] as const;

  const missions = bp.missions
    .map((m, idx) => {
      const next = bp.missions[idx + 1];
      const steps = phases
        .map(
          (phase, i) =>
            `      { phase: '${phase}', title: '${phase} step ${i + 1}', body: '${phase} for ${m.title} — document evidence and reflection.' },`,
        )
        .join('\n');
      return `  {
    slug: '${m.slug}',
    number: ${m.number},
    title: '${m.title}',
    subtitle: '${m.title} — civic action with documented evidence',
    outcome: 'Completed ${m.title.toLowerCase()} with reflection and portfolio artifact',
    evidence: 'Notes, photo, or summary proving you completed this civic mission',
    timeEstimate: '45–90 min',
    requiredLevel: 'Level ${m.number}',
    futureProof: 'Citizenship through action builds agency that transfers to every domain.',
    tomorrowHook: '${next ? `Tomorrow: Mission ${next.number} — ${next.title}.` : 'Tomorrow: lead others in civic conversation.'}',
    ${next ? `nextMissionSlug: '${next.slug}',` : ''}
    steps: [
${steps}
    ],
  }`;
    })
    .join(',\n');

  const levelRows = bp.missions.map(
    (m, i) =>
      `  { slug: 'level-${m.number}', level: ${i + 1}, title: 'Level ${i + 1}', tagline: '${m.title}', unlocks: ['Mission ${m.number}: ${m.title}'] }`,
  );
  for (let level = bp.missions.length + 1; level <= 7; level++) {
    levelRows.push(
      `  { slug: 'level-${level}', level: ${level}, title: 'Level ${level}', tagline: 'Deepen civic practice', unlocks: ['${bp.communityName} mentorship'] }`,
    );
  }
  const levels = levelRows.join(',\n');

  const content = `/** ${bp.displayName} World — Life Leverage (PASS-024 factory) */

import type { WorldMission } from '../components/world/WorldMissionRunner';

export const ${c}_LOOP = [
  { step: 'Mission', description: 'Pick a civic action worth pursuing' },
  { step: 'Build', description: 'Research, prepare, or organize your participation' },
  { step: 'Show', description: 'Attend, volunteer, or lead — document what happened' },
  { step: 'Reflect', description: 'Write what you learned about your community' },
  { step: 'Improve', description: 'Plan the next civic step with more impact' },
  { step: 'Mentor', description: 'Invite someone to participate with you' },
] as const;

export const ${c}_ACADEMY_LEVELS = [
${levels}
];

export const ${c}_MISSIONS: WorldMission[] = [
${missions}
];

export const ${c}_PORTFOLIO_KEY = '${bp.portfolioKey}';
export const ${c}_PORTFOLIO_LABEL = '${bp.portfolioLabel}';

export const ${c}_COMMUNITY = {
  name: '${bp.communityName}',
  features: [
    { title: 'Local action threads', description: 'Share meeting notes and volunteer opportunities' },
    { title: 'Ballot research', description: 'Structured research before every election' },
    { title: 'Project showcases', description: 'Community projects with evidence and outcomes' },
    { title: 'Mentorship', description: 'Experienced members guide first-time participants' },
  ],
};

export const ${c}_CORE_PROMISE = '${bp.corePromise.replace(/'/g, "\\'")}';

export function ${getter}(slug: string): WorldMission | undefined {
  return ${c}_MISSIONS.find((m) => m.slug === slug);
}
`;
  track(file, content, written, skipped);
  return true;
}

function appendCorePromise(bp: FullWorldBlueprint, written: string[], skipped: string[]): boolean {
  const file = path.join(platformRoot(), `lib/${worldLibBasename(bp.slug)}.ts`);
  if (!fs.existsSync(file)) return false;
  const c = slugToConst(bp.slug);
  const marker = `${c}_CORE_PROMISE`;
  const existing = fs.readFileSync(file, 'utf8');
  if (existing.includes(marker)) return false;

  const append = `\nexport const ${marker} = '${bp.corePromise.replace(/'/g, "\\'")}';\n`;
  fs.writeFileSync(file, existing.replace(/\s*$/, '') + append, 'utf8');
  written.push(file);
  return true;
}

function generateLayout(bp: FullWorldBlueprint, written: string[], skipped: string[]): void {
  const pascal = slugToPascal(bp.slug);
  const layoutFile = path.join(platformRoot(), `app/${bp.slug}/layout.tsx`);
  const content = `import { ConsumerNav } from '../../components/ConsumerNav';
import { ${pascal}SubNav } from '../../components/${componentFolder(bp.slug)}/${pascal}SubNav';
import { ValidationPageTracker } from '../../components/ValidationPageTracker';

export default function ${pascal}Layout({ children }: { children: React.ReactNode }) {
  return (
    <main style={{ minHeight: '100vh', backgroundColor: '#08080A', color: '#E8E8EC', padding: '2rem', maxWidth: 960, margin: '0 auto' }}>
      <ValidationPageTracker page="/${bp.slug}" />
      <ConsumerNav />
      <${pascal}SubNav />
      {children}
    </main>
  );
}
`;
  track(layoutFile, content, written, skipped);
}

function generateHubPage(bp: FullWorldBlueprint, written: string[], skipped: string[]): void {
  const c = slugToConst(bp.slug);
  const pascal = slugToPascal(bp.slug);
  const hubFile = path.join(platformRoot(), `app/${bp.slug}/page.tsx`);
  const lib = libImport(hubFile, bp.slug);
  const kindLabel = bp.kind === 'passion' ? `${bp.frame} · Passion Trinity` : `${bp.frame} · Life Leverage`;
  const passionNext =
    bp.kind === 'passion' && bp.nextWorldSlug
      ? `
      <section style={{ marginTop: 24, padding: 24, background: '#111114', borderRadius: 8, border: '1px solid ${bp.borderColor}' }}>
        <p style={{ color: '#6B6B70', fontSize: 11, letterSpacing: '0.1em', textTransform: 'uppercase', margin: 0 }}>Next recommended world</p>
        <p style={{ color: '#E8E8EC', fontSize: 16, marginTop: 12 }}>
          Continue the Passion Trinity with the next world — start Mission 1 when you are ready.
        </p>
        <Link href="/${bp.nextWorldSlug}/missions" style={{ display: 'inline-block', marginTop: 16, padding: '12px 20px', background: '#0F0F12', border: '1px solid ${bp.borderColor}', borderRadius: 6, color: '${bp.accentColor}', fontSize: 14, textDecoration: 'none' }}>
          Explore next world →
        </Link>
      </section>`
      : '';

  const content = `import Link from 'next/link';
import { ${c}_COMMUNITY, ${c}_CORE_PROMISE, ${c}_LOOP, ${c}_MISSIONS } from '${lib}';

export const metadata = {
  title: '${bp.displayName} World | Foundry',
  description: ${c}_CORE_PROMISE,
};

export default function ${pascal}WorldPage() {
  return (
    <section style={{ marginTop: 16 }}>
      <section style={{ padding: 32, background: '#0F0F12', border: '1px solid ${bp.borderColor}', borderRadius: 8 }}>
        <p style={{ color: '${bp.accentColor}', fontSize: 11, letterSpacing: '0.12em', textTransform: 'uppercase', margin: 0 }}>
          ${kindLabel}
        </p>
        <h1 style={{ fontWeight: 300, fontSize: '2.5rem', marginTop: 12 }}>${bp.displayName} World</h1>
        <p style={{ color: '#8A8A8E', fontSize: 16, marginTop: 16, lineHeight: 1.7, maxWidth: 640 }}>{${c}_CORE_PROMISE}</p>
        <p style={{ color: '${bp.accentColor}', fontSize: 14, marginTop: 16 }}>Outcome: ${bp.outcomeStatement}</p>
        <div style={{ marginTop: 28, display: 'flex', gap: 12, flexWrap: 'wrap' }}>
          <Link href="/${bp.slug}/missions/${bp.mission1Slug}" style={{ padding: '14px 24px', background: '${bp.borderColor}', borderRadius: 6, color: '#E8E8EC', fontSize: 14, textDecoration: 'none' }}>
            Start Mission 1 →
          </Link>
          <Link href="/${bp.slug}/parents" style={{ padding: '14px 24px', border: '1px solid #1A1A1E', borderRadius: 6, color: '#8A8A8E', fontSize: 14, textDecoration: 'none' }}>
            For Parents
          </Link>
          <Link href="/${bp.slug}/community" style={{ padding: '14px 24px', border: '1px solid #1A1A1E', borderRadius: 6, color: '#8A8A8E', fontSize: 14, textDecoration: 'none' }}>
            ${bp.communityName}
          </Link>
        </div>
      </section>

      <section style={{ marginTop: 24, padding: 24, background: '#111114', borderRadius: 8 }}>
        <h2 style={{ fontSize: 14, color: '${bp.accentColor}', margin: 0 }}>How Foundry works</h2>
        <p style={{ color: '#8A8A8E', fontSize: 13, marginTop: 12 }}>
          {${c}_LOOP.map((item, i) => (
            <span key={item.step}>{i > 0 ? ' → ' : ''}{item.step}</span>
          ))}
        </p>
      </section>

      <section style={{ marginTop: 24, padding: 24, background: '#0F0F12', borderRadius: 8 }}>
        <h2 style={{ fontSize: 14, color: '${bp.accentColor}', margin: 0 }}>Missions</h2>
        {${c}_MISSIONS.map((m) => (
          <Link key={m.slug} href={\`/${bp.slug}/missions/\${m.slug}\`} style={{ display: 'block', padding: '14px 0', borderBottom: '1px solid #1A1A1E', textDecoration: 'none', color: '#E8E8EC', fontSize: 14 }}>
            Mission {m.number}: {m.title}
          </Link>
        ))}
      </section>

      <section style={{ marginTop: 24, padding: 24, background: '#111114', borderRadius: 8 }}>
        <h2 style={{ fontSize: 14, color: '${bp.accentColor}', margin: 0 }}>{${c}_COMMUNITY.name}</h2>
        {${c}_COMMUNITY.features.map((f) => (
          <p key={f.title} style={{ color: '#8A8A8E', fontSize: 13, marginTop: 12 }}>
            <strong style={{ color: '#E8E8EC', fontWeight: 400 }}>{f.title}</strong> — {f.description}
          </p>
        ))}
      </section>
${passionNext}

      <p style={{ marginTop: 24, fontSize: 12, color: '#4A4A4E' }}>
        <Link href="/explore/${bp.slug}" style={{ color: '#6B6B70' }}>Explore path</Link>
        {' · '}
        <Link href="/verticals/${bp.slug}" style={{ color: '#6B6B70' }}>Operator proof</Link>
      </p>
    </section>
  );
}
`;
  track(hubFile, content, written, skipped);
}

function generateSubPages(bp: FullWorldBlueprint, written: string[], skipped: string[]): void {
  const c = slugToConst(bp.slug);
  const pascal = slugToPascal(bp.slug);
  const getter = missionGetterName(bp.slug);
  const base = path.join(platformRoot(), `app/${bp.slug}`);

  const missionsList = path.join(base, 'missions/page.tsx');
  const missionsListLib = libImport(missionsList, bp.slug);
  track(
    missionsList,
    `import Link from 'next/link';
import { ${c}_MISSIONS } from '${missionsListLib}';

export default function ${pascal}MissionsPage() {
  return (
    <section style={{ marginTop: 16 }}>
      <h1 style={{ fontWeight: 300, fontSize: '2rem', margin: 0 }}>Missions</h1>
      <p style={{ color: '#8A8A8E', fontSize: 14, marginTop: 12 }}>${bp.frame} — one mission at a time.</p>
      {${c}_MISSIONS.map((m) => (
        <Link key={m.slug} href={\`/${bp.slug}/missions/\${m.slug}\`} style={{ display: 'block', padding: 24, marginTop: 12, background: m.number === 1 ? '#0F0F12' : '#111114', border: m.number === 1 ? '1px solid ${bp.borderColor}' : '1px solid #1A1A1E', borderRadius: 8, textDecoration: 'none', color: 'inherit' }}>
          <p style={{ color: '${bp.accentColor}', fontSize: 11, margin: 0 }}>Mission {m.number}</p>
          <h2 style={{ fontSize: 18, fontWeight: 400, marginTop: 8, color: '#E8E8EC' }}>{m.title}</h2>
          <p style={{ color: '#6B6B70', fontSize: 12, marginTop: 8 }}>{m.timeEstimate}</p>
        </Link>
      ))}
    </section>
  );
}
`,
    written,
    skipped,
  );

  const missionDetail = path.join(base, 'missions/[slug]/page.tsx');
  const missionLib = libImport(missionDetail, bp.slug);
  track(
    missionDetail,
    `import Link from 'next/link';
import { notFound } from 'next/navigation';
import { WorldMissionRunner } from '../../../../components/world/WorldMissionRunner';
import { ${c}_MISSIONS, ${c}_PORTFOLIO_KEY, ${c}_PORTFOLIO_LABEL, ${getter} } from '${missionLib}';

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return ${c}_MISSIONS.map((m) => ({ slug: m.slug }));
}

export default async function ${pascal}MissionPage({ params }: Props) {
  const { slug } = await params;
  const mission = ${getter}(slug);
  if (!mission) notFound();

  return (
    <section style={{ marginTop: 16 }}>
      <Link href="/${bp.slug}/missions" style={{ color: '#6B6B70', fontSize: 13, textDecoration: 'none' }}>← All missions</Link>
      <p style={{ color: '${bp.accentColor}', fontSize: 11, letterSpacing: '0.1em', textTransform: 'uppercase', marginTop: 16 }}>Mission {mission.number}</p>
      <h1 style={{ fontWeight: 300, fontSize: '2rem', marginTop: 8 }}>{mission.title}</h1>
      <p style={{ color: '#8A8A8E', fontSize: 14, marginTop: 12 }}>{mission.subtitle}</p>
      <section style={{ marginTop: 20, padding: 16, background: '#1A160F', borderRadius: 8, border: '1px solid ${bp.borderColor}' }}>
        <p style={{ color: '${bp.accentColor}', fontSize: 13, margin: 0 }}><strong style={{ fontWeight: 400 }}>Future-proof: </strong>{mission.futureProof}</p>
      </section>
      <WorldMissionRunner mission={mission} portfolioKey={${c}_PORTFOLIO_KEY} basePath="/${bp.slug}" pathSlug="${bp.slug}" portfolioLabel={${c}_PORTFOLIO_LABEL} />
    </section>
  );
}
`,
    written,
    skipped,
  );

  const academy = path.join(base, 'academy/page.tsx');
  const academyLib = libImport(academy, bp.slug);
  track(
    academy,
    `import Link from 'next/link';
import { ${c}_ACADEMY_LEVELS } from '${academyLib}';

export default function ${pascal}AcademyPage() {
  return (
    <section style={{ marginTop: 16 }}>
      <h1 style={{ fontWeight: 300, fontSize: '2rem', margin: 0 }}>Academy</h1>
      {${c}_ACADEMY_LEVELS.map((level) => (
        <article key={level.slug} style={{ padding: 24, marginTop: 12, background: '#111114', borderRadius: 8 }}>
          <p style={{ color: '${bp.accentColor}', fontSize: 11, margin: 0 }}>Level {level.level}</p>
          <h2 style={{ fontSize: 18, fontWeight: 400, marginTop: 8 }}>{level.title}</h2>
          <p style={{ color: '#8A8A8E', fontSize: 13, marginTop: 8 }}>{level.tagline}</p>
          {level.level === 1 && (
            <Link href="/${bp.slug}/missions/${bp.mission1Slug}" style={{ display: 'inline-block', marginTop: 16, color: '${bp.accentColor}', fontSize: 14 }}>Start Mission 1 →</Link>
          )}
        </article>
      ))}
    </section>
  );
}
`,
    written,
    skipped,
  );

  const parents = path.join(base, 'parents/page.tsx');
  const parentsMeta = metaImport(parents, bp.slug);
  track(
    parents,
    `import Link from 'next/link';
import { ${c}_PARENT_VIEW } from '${parentsMeta}';

export default function ${pascal}ParentsPage() {
  return (
    <section style={{ marginTop: 16 }}>
      <h1 style={{ fontWeight: 300, fontSize: '2rem', margin: 0 }}>{${c}_PARENT_VIEW.headline}</h1>
      <p style={{ color: '#E8E8EC', fontSize: 16, marginTop: 16, lineHeight: 1.6 }}>{${c}_PARENT_VIEW.oneLiner}</p>
      {${c}_PARENT_VIEW.sections.map((s) => (
        <article key={s.title} style={{ padding: 24, marginTop: 12, background: '#0F0F12', borderRadius: 8 }}>
          <h2 style={{ fontSize: 15, color: '${bp.accentColor}', margin: 0 }}>{s.title}</h2>
          <p style={{ color: '#8A8A8E', fontSize: 14, marginTop: 12, lineHeight: 1.7 }}>{s.body}</p>
        </article>
      ))}
      <Link href="/${bp.slug}/missions/${bp.mission1Slug}" style={{ display: 'inline-block', marginTop: 24, color: '${bp.accentColor}', fontSize: 14 }}>See Mission 1 →</Link>
    </section>
  );
}
`,
    written,
    skipped,
  );

  const glossary = path.join(base, 'glossary/page.tsx');
  const glossaryMeta = metaImport(glossary, bp.slug);
  track(
    glossary,
    `import { ${c}_GLOSSARY } from '${glossaryMeta}';

export default function ${pascal}GlossaryPage() {
  return (
    <section style={{ marginTop: 16 }}>
      <h1 style={{ fontWeight: 300, fontSize: '2rem', margin: 0 }}>Glossary</h1>
      <dl style={{ marginTop: 24 }}>
        {${c}_GLOSSARY.map((item) => (
          <div key={item.term} style={{ padding: '16px 0', borderBottom: '1px solid #1A1A1E' }}>
            <dt style={{ color: '${bp.accentColor}', fontSize: 14 }}>{item.term}</dt>
            <dd style={{ color: '#8A8A8E', fontSize: 13, margin: '8px 0 0' }}>{item.definition}</dd>
          </div>
        ))}
      </dl>
    </section>
  );
}
`,
    written,
    skipped,
  );

  const careers = path.join(base, 'careers/page.tsx');
  const careersMeta = metaImport(careers, bp.slug);
  track(
    careers,
    `import { ${c}_CAREERS } from '${careersMeta}';

export default function ${pascal}CareersPage() {
  return (
    <section style={{ marginTop: 16 }}>
      <h1 style={{ fontWeight: 300, fontSize: '2rem', margin: 0 }}>What careers use this?</h1>
      {${c}_CAREERS.map((c) => (
        <article key={c.title} style={{ padding: 20, marginTop: 10, background: '#0F0F12', borderRadius: 8 }}>
          <h2 style={{ fontSize: 15, fontWeight: 400, margin: 0 }}>{c.title}</h2>
          <p style={{ color: '#8A8A8E', fontSize: 13, marginTop: 8 }}>{c.connection}</p>
        </article>
      ))}
    </section>
  );
}
`,
    written,
    skipped,
  );

  const playground = path.join(base, 'playground/page.tsx');
  const playgroundMeta = metaImport(playground, bp.slug);
  track(
    playground,
    `import { ${c}_PLAYGROUND_LABS } from '${playgroundMeta}';

export default function ${pascal}PlaygroundPage() {
  return (
    <section style={{ marginTop: 16 }}>
      <h1 style={{ fontWeight: 300, fontSize: '2rem', margin: 0 }}>Playground</h1>
      {${c}_PLAYGROUND_LABS.map((lab) => (
        <article key={lab.slug} style={{ padding: 24, marginTop: 12, background: '#0F0F12', borderRadius: 8 }}>
          <h2 style={{ fontSize: 16, fontWeight: 400, color: '#E8E8EC', margin: 0 }}>{lab.title}</h2>
          <p style={{ color: '#8A8A8E', fontSize: 13, marginTop: 8 }}>{lab.description}</p>
        </article>
      ))}
    </section>
  );
}
`,
    written,
    skipped,
  );

  const portfolio = path.join(base, 'portfolio/page.tsx');
  const portfolioComp = componentImport(portfolio, bp.slug, `${pascal}PortfolioView`);
  track(
    portfolio,
    `import { ${pascal}PortfolioView } from '${portfolioComp}';

export const metadata = { title: '${bp.portfolioLabel} | ${bp.displayName} World' };

export default function ${pascal}PortfolioPage() {
  return (
    <section style={{ marginTop: 16 }}>
      <h1 style={{ fontWeight: 300, fontSize: '2rem', margin: 0 }}>${bp.portfolioLabel}</h1>
      <${pascal}PortfolioView />
    </section>
  );
}
`,
    written,
    skipped,
  );

  const community = path.join(base, 'community/page.tsx');
  const communityLib = libImport(community, bp.slug);
  track(
    community,
    `import Link from 'next/link';
import { ${c}_COMMUNITY } from '${communityLib}';

export default function ${pascal}CommunityPage() {
  return (
    <section style={{ marginTop: 16 }}>
      <h1 style={{ fontWeight: 300, fontSize: '2rem', margin: 0 }}>{${c}_COMMUNITY.name}</h1>
      <p style={{ color: '#8A8A8E', fontSize: 14, marginTop: 12, lineHeight: 1.7 }}>
        Shared mastery — members, projects, and evidence. Not just social.
      </p>
      {${c}_COMMUNITY.features.map((f) => (
        <article key={f.title} style={{ padding: 20, marginTop: 12, background: '#0F0F12', borderRadius: 8, border: '1px solid #1A1A1E' }}>
          <h2 style={{ fontSize: 15, color: '${bp.accentColor}', margin: 0 }}>{f.title}</h2>
          <p style={{ color: '#8A8A8E', fontSize: 13, marginTop: 8 }}>{f.description}</p>
        </article>
      ))}
      <Link href="/${bp.slug}/missions/${bp.mission1Slug}" style={{ display: 'inline-block', marginTop: 24, color: '${bp.accentColor}', fontSize: 14 }}>Start with Mission 1 →</Link>
    </section>
  );
}
`,
    written,
    skipped,
  );
}

function generateComponents(bp: FullWorldBlueprint, written: string[], skipped: string[]): void {
  const pascal = slugToPascal(bp.slug);
  const c = slugToConst(bp.slug);
  const folder = path.join(platformRoot(), `components/${componentFolder(bp.slug)}`);
  const subNavFile = path.join(folder, `${pascal}SubNav.tsx`);

  const links = [
    `{ href: '/${bp.slug}', label: 'World', exact: true }`,
    `{ href: '/${bp.slug}/missions', label: 'Missions' }`,
    `{ href: '/${bp.slug}/academy', label: 'Academy' }`,
    `{ href: '/${bp.slug}/playground', label: 'Playground' }`,
    `{ href: '/${bp.slug}/portfolio', label: 'Portfolio' }`,
    `{ href: '/${bp.slug}/parents', label: 'For Parents' }`,
    `{ href: '/${bp.slug}/glossary', label: 'Glossary' }`,
    `{ href: '/${bp.slug}/careers', label: 'Careers' }`,
    `{ href: '/${bp.slug}/community', label: 'Community' }`,
  ].join(',\n  ');

  track(
    subNavFile,
    `'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

const LINKS = [
  ${links},
] as const;

export function ${pascal}SubNav() {
  const pathname = usePathname() ?? '';
  return (
    <nav style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 12, paddingBottom: 12, borderBottom: '1px solid #1A1A1E' }} aria-label="${bp.displayName} world">
      {LINKS.map(({ href, label, ...rest }) => {
        const exact = 'exact' in rest && rest.exact;
        const active = exact ? pathname === href : pathname === href || pathname.startsWith(\`\${href}/\`);
        return (
          <Link key={href} href={href} style={{ padding: '6px 12px', fontSize: 12, borderRadius: 6, textDecoration: 'none', color: active ? '#E8E8EC' : '#6B6B70', background: active ? '${bp.borderColor}' : 'transparent', border: \`1px solid \${active ? '${bp.borderColor}' : 'transparent'}\` }}>
            {label}
          </Link>
        );
      })}
    </nav>
  );
}
`,
    written,
    skipped,
  );

  const portfolioFile = path.join(folder, `${pascal}PortfolioView.tsx`);
  const libFromComp = relImportDepth(
    folder,
    path.join(platformRoot(), `lib/${worldLibBasename(bp.slug)}.ts`),
  ).replace(/\.ts$/, '');
  const metaFromComp = relImportDepth(
    folder,
    path.join(platformRoot(), `lib/${worldLibBasename(bp.slug)}-meta.ts`),
  ).replace(/\.ts$/, '');
  const runnerFromComp = relImportDepth(
    folder,
    path.join(platformRoot(), 'components/world/WorldMissionRunner.tsx'),
  ).replace(/\.tsx$/, '');

  track(
    portfolioFile,
    `'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { getWorldPortfolio, type PortfolioEntry } from '${runnerFromComp}';
import { ${c}_MISSIONS, ${c}_PORTFOLIO_KEY } from '${libFromComp}';
import { ${c}_PORTFOLIO_SECTIONS } from '${metaFromComp}';

export function ${pascal}PortfolioView() {
  const [entries, setEntries] = useState<PortfolioEntry[]>([]);
  useEffect(() => {
    setEntries(getWorldPortfolio(${c}_PORTFOLIO_KEY));
  }, []);

  return (
    <div>
      <p style={{ color: '#8A8A8E', fontSize: 14, lineHeight: 1.7 }}>
        Mission evidence and reflections — proof of your ${bp.displayName.toLowerCase()} journey.
      </p>
      <div style={{ marginTop: 24, display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 12 }}>
        {${c}_PORTFOLIO_SECTIONS.map((section) => (
          <div key={section.slug} style={{ padding: 16, background: '#111114', borderRadius: 8, border: '1px solid ${bp.borderColor}' }}>
            <p style={{ color: '#E8E8EC', fontSize: 14, margin: 0 }}>{section.title}</p>
            <p style={{ color: '#6B6B70', fontSize: 12, marginTop: 8 }}>{section.description}</p>
            <p style={{ color: '${bp.accentColor}', fontSize: 20, fontWeight: 300, marginTop: 12 }}>{section.slug === '${bp.portfolioSections[0]?.slug ?? 'entries'}' ? entries.length : '—'}</p>
          </div>
        ))}
      </div>
      {entries.length === 0 ? (
        <p style={{ color: '#6B6B70', fontSize: 14, marginTop: 24 }}>
          No missions yet.{' '}
          <Link href="/${bp.slug}/missions/${bp.mission1Slug}" style={{ color: '${bp.accentColor}' }}>Start Mission 1 →</Link>
        </p>
      ) : (
        entries.map((e) => (
          <div key={e.missionSlug} style={{ padding: 16, marginTop: 12, background: '#0F0F12', borderRadius: 8 }}>
            <p style={{ color: '#E8E8EC', fontSize: 14, margin: 0 }}>{e.missionTitle}</p>
            <p style={{ color: '#8A8A8E', fontSize: 13, marginTop: 8 }}>{e.reflection}</p>
          </div>
        ))
      )}
    </div>
  );
}
`,
    written,
    skipped,
  );
}

function generateVerticalPage(bp: FullWorldBlueprint, written: string[], skipped: string[]): void {
  const pascal = slugToPascal(bp.slug);
  const file = path.join(platformRoot(), `app/verticals/${bp.slug}/page.tsx`);
  const content = `import Link from 'next/link';

export const metadata = {
  title: '${bp.displayName} — Operator Proof',
  description: 'Factory-generated operator proof for ${bp.displayName} World.',
};

export default function ${pascal}VerticalPage() {
  return (
    <main style={{ minHeight: '100vh', backgroundColor: '#08080A', color: '#E8E8EC', padding: '2rem', maxWidth: 900, margin: '0 auto' }}>
      <Link href="/verticals" style={{ color: '#6B6B70', fontSize: 13 }}>← Vertical Domains</Link>
      <p style={{ color: '${bp.accentColor}', fontSize: 11, letterSpacing: '0.15em', textTransform: 'uppercase', marginTop: 16 }}>
        ${bp.slug}.foundryos.com · PASS-024 factory proof
      </p>
      <h1 style={{ fontWeight: 300, fontSize: '2rem', marginTop: 8 }}>${bp.displayName}</h1>
      <p style={{ color: '#8A8A8E', fontSize: 13, marginTop: 8 }}>${bp.frame} · ${bp.outcomeStatement}</p>
      <p style={{ color: '#6B9B6B', fontSize: 12, marginTop: 8 }}>
        Consumer world:{' '}
        <Link href="/${bp.slug}" style={{ color: '#6B9B6B' }}>/${bp.slug}</Link>
      </p>

      <section style={{ marginTop: 32, padding: 24, background: '#0F0F12', borderRadius: 8, border: '1px solid ${bp.borderColor}' }}>
        <h2 style={{ fontSize: 14, color: '${bp.accentColor}', margin: 0 }}>Factory layers</h2>
        <ul style={{ color: '#8A8A8E', fontSize: 13, marginTop: 16, lineHeight: 1.9 }}>
          <li>World hub + 5 missions</li>
          <li>Academy · Portfolio · Parents · Glossary · Careers · Playground · Community</li>
          <li>marketing/domains/${bp.slug}/ launch pack</li>
          <li>Explore catalog registration (live)</li>
        </ul>
      </section>

      <section style={{ marginTop: 24, padding: 20, background: '#111114', borderRadius: 8 }}>
        <p style={{ color: '#6B6B70', fontSize: 11, margin: 0, textTransform: 'uppercase' }}>Core promise</p>
        <p style={{ color: '#E8E8EC', fontSize: 14, marginTop: 12, lineHeight: 1.7 }}>${bp.corePromise}</p>
      </section>
    </main>
  );
}
`;
  track(file, content, written, skipped);
}

function generateMarketingPack(bp: FullWorldBlueprint, written: string[], skipped: string[]): void {
  const dir = path.join(marketingRoot(), 'domains', bp.slug);
  const seoTopics = [
    `What Is ${bp.displayName}?`,
    `Beginner Guide to ${bp.displayName}`,
    `Road to ${bp.outcomeStatement}`,
    `${bp.displayName} Projects`,
    `Common ${bp.displayName} Mistakes`,
  ];

  const files: Record<string, string> = {
    'README.md': `# ${bp.displayName} — Marketing Domain Pack

Frame: **${bp.frame}** · Outcome: **${bp.outcomeStatement}**

Generated by \`npm run build:world -- ${bp.slug}\` (PASS-024).

Consumer world: \`/${bp.slug}\`
Registry: \`apps/platform/lib/${worldLibBasename(bp.slug)}.ts\`
`,
    'seo-map.md': `# ${bp.displayName} — SEO Cluster Map

| Page | Intent | Status |
|------|--------|--------|
${seoTopics.map((t) => `| ${t} | informational | draft |`).join('\n')}

Publish when content_score >= 70.
`,
    'youtube-topics.md': `# ${bp.displayName} — YouTube Topics

${bp.plannedProjects.map((p) => `- ${p} (tutorial / vlog)`).join('\n')}
- ${bp.outcomeStatement} — full journey overview
`,
    'tiktok-topics.md': `# ${bp.displayName} — TikTok Topics

${bp.missions.map((m) => `- Mission ${m.number}: ${m.title} in 60 seconds`).join('\n')}
- Before/after portfolio artifact
`,
    'reddit-topics.md': `# ${bp.displayName} — Reddit Topics

- r/${bp.slug.replace(/-/g, '')} — weekly mission thread
- AMA: how I became ${bp.outcomeStatement.toLowerCase()}
- ${bp.communityName} invite post
`,
    'lead-magnets.md': `# ${bp.displayName} — Lead Magnets

- ${bp.displayName} Mission 1 checklist (PDF)
- ${bp.portfolioLabel} starter template
- Parent one-pager: ${bp.parentHeadline}
`,
    'affiliate-opportunities.md': `# ${bp.displayName} — Affiliate Opportunities

- Starter kits aligned with Mission 1
- Books and tools for ${bp.frame.toLowerCase()}
- Event tickets (local meetups, classes)
`,
    'LAUNCH_CHECKLIST.md': `# ${bp.displayName} — Launch Checklist

## Platform (World Factory)
- [x] Consumer routes scaffolded (\`/${bp.slug}\`)
- [x] 5 missions with WorldMissionRunner
- [x] Portfolio + localStorage key (\`${bp.portfolioKey}\`)
- [x] Parent · Glossary · Careers · Playground · Community pages
- [x] Operator proof (\`/verticals/${bp.slug}\`)
- [ ] Content score >= 70 before SEO publish

## Marketing
- [ ] SEO cluster reviewed
- [ ] 30-day content calendar customized
- [ ] YouTube / TikTok / Reddit topics scheduled

## Growth
- [ ] Explore path live at \`/explore/${bp.slug}\`
- [ ] Tier 2 hook: ${bp.portfolioLabel}
`,
    'content-calendar-30d.md': `# ${bp.displayName} — 30 Day Content Calendar

| Day | Channel | Topic |
|-----|---------|-------|
| 1 | SEO | What Is ${bp.displayName}? |
| 3 | Social | Outcome: ${bp.outcomeStatement} |
| 5 | SEO | Beginner Guide to ${bp.displayName} |
| 7 | Email | Welcome — ${bp.corePromise.slice(0, 60)}… |
| 10 | Social | First project: ${bp.plannedProjects[0] ?? bp.missions[0].title} |
| 14 | SEO | Road to ${bp.outcomeStatement} |
| 17 | Social | ${bp.communityName} invite |
| 21 | Email | Mission 1 nudge |
| 25 | SEO | Common ${bp.displayName} Mistakes |
| 30 | Social | Mastery milestone template |

Generated from blueprint — customize before publish.
`,
  };

  for (const [name, content] of Object.entries(files)) {
    track(path.join(dir, name), content, written, skipped);
  }
}

export function regenerateFactoryRegistry(slugs: string[]): void {
  const blueprints = slugs
    .map((s) => getFullBlueprint(s))
    .filter((b): b is FullWorldBlueprint => Boolean(b));

  const routes = blueprints.map((b) => `  '/${b.slug}',`).join('\n');
  const routesContent = `/** Auto-generated by @foundry/world-factory — do not edit */

export const FACTORY_CONSUMER_ROUTES = [
${routes}
] as const;

export type FactoryConsumerRoute = (typeof FACTORY_CONSUMER_ROUTES)[number];
`;
  writeFileIfChanged(ROUTES_PATH(), routesContent);

  const exploreEntries = blueprints
    .map((b) => {
      const categories = b.exploreCategories.map((c) => `'${c}'`).join(', ');
      return `  {
    slug: '${b.slug}',
    name: '${b.displayName}',
    outcome: '${b.outcomeStatement}',
    status: 'live' as const,
    tier: '${b.exploreTier}' as const,
    launch_rank: ${b.exploreLaunchRank},
    section_id: '${b.exploreSectionId}',
    categories: [${categories}] as const,
    live_href: '/${b.slug}',
    planned_projects: ${JSON.stringify(b.plannedProjects)},
    become: '${b.exploreBecome.replace(/'/g, "\\'")}',
  },`;
    })
    .join('\n');

  const exploreContent = `/** Auto-generated by @foundry/world-factory — do not edit */
import type { ExplorePath } from '../explore-catalog';

export const FACTORY_EXPLORE_PATHS: ExplorePath[] = [
${exploreEntries}
];
`;
  writeFileIfChanged(EXPLORE_PATH(), exploreContent);
}

export function generateWorld(slug: string): GenerateWorldResult {
  const bp = getFullBlueprint(slug);
  if (!bp) {
    throw new Error(`Unknown world slug: ${slug}`);
  }

  const written: string[] = [];
  const skipped: string[] = [];

  const worldLibCreated = bp.slug === 'civic-engagement' ? generateCivicWorldLib(bp, written, skipped) : false;
  const corePromiseAppended = appendCorePromise(bp, written, skipped);

  generateWorldMeta(bp, written, skipped);
  generateLayout(bp, written, skipped);
  generateHubPage(bp, written, skipped);
  generateSubPages(bp, written, skipped);
  generateComponents(bp, written, skipped);
  generateVerticalPage(bp, written, skipped);
  generateMarketingPack(bp, written, skipped);

  const manifest = loadManifest();
  const slugs = [...new Set([...manifest.domains, slug])];
  saveManifestSlugs(slugs);
  regenerateFactoryRegistry(slugs);

  return {
    slug,
    displayName: bp.displayName,
    filesWritten: written.map((f) => path.relative(getRepoRoot(), f)),
    filesSkipped: skipped.map((f) => path.relative(getRepoRoot(), f)),
    corePromiseAppended,
    worldLibCreated,
  };
}
