import type { CSSProperties } from "react";
import { InventoryOperatingDashboard } from "../../components/inventory/InventoryOperatingDashboard";
import { inventorySummary, inventoryValuationDoctrine } from "../../lib/company-inventory";
import { operatingInventory, portfolioOperatingSummary, portfolioQueues } from "../../lib/inventory-operations";

const money=(value:number)=>value>=1_000_000?`$${(value/1_000_000).toFixed(value%1_000_000===0?0:1)}M`:value>=1_000?`$${Math.round(value/1_000)}K`:`$${value.toLocaleString()}`;
const range=(low:number,high:number)=>`${money(low)}–${money(high)}`;
const card:CSSProperties={border:"1px solid rgba(148,163,184,.28)",borderRadius:18,background:"rgba(15,23,42,.72)",padding:20,boxShadow:"0 10px 30px rgba(2,6,23,.16)"};
const label:CSSProperties={color:"#94a3b8",textTransform:"uppercase",letterSpacing:".08em",fontSize:12,fontWeight:800};

export default function InventoryPage(){
  return <main style={{minHeight:"100vh",background:"linear-gradient(180deg,#020617 0%,#0f172a 45%,#111827 100%)",color:"#e5e7eb",padding:"42px 22px 80px"}}><div style={{maxWidth:1440,margin:"0 auto"}}>
    <header style={{marginBottom:30}}><div style={{...label,color:"#60a5fa"}}>Company Foundry · Portfolio Command</div><h1 style={{fontSize:"clamp(2.2rem,5vw,4.5rem)",lineHeight:1,margin:"10px 0 16px",letterSpacing:"-.04em"}}>Product & IP Inventory</h1><p style={{maxWidth:980,fontSize:18,lineHeight:1.65,color:"#cbd5e1",margin:0}}>This is now an operating portfolio, not a static list. It separates what should be sold now, finished for revenue, incubated, published, or held—and keeps valuation, readiness, external proof, and build work visible at the same time.</p></header>

    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(205px,1fr))",gap:12,marginBottom:18}}>{[["Portfolio assets",inventorySummary.productCount.toString()],["Average readiness",`${inventorySummary.weightedReadiness}%`],["Sell / pilot now",portfolioOperatingSummary.sellNow.toString()],["Finish → sell",portfolioOperatingSummary.finishAndSell.toString()],["Publishing track",portfolioOperatingSummary.publish.toString()],["Hold / blockers",portfolioOperatingSummary.hold.toString()]].map(([name,value])=><div key={name} style={card}><div style={label}>{name}</div><div style={{fontSize:28,fontWeight:900,marginTop:8,letterSpacing:"-.03em"}}>{value}</div></div>)}</section>

    <section style={{...card,marginBottom:18}}><div style={{...label,color:"#86efac"}}>What should we work on first?</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(235px,1fr))",gap:12,marginTop:12}}>{portfolioOperatingSummary.topPriority.map((item,index)=><div key={item.id} style={{padding:14,borderRadius:14,background:"rgba(2,6,23,.5)"}}><div style={{color:"#64748b",fontSize:11,fontWeight:800}}>#{index+1} · SCORE {item.priorityScore}</div><strong style={{display:"block",fontSize:17,margin:"5px 0"}}>{item.name}</strong><div style={{color:item.priorityBand==="sell-now"?"#86efac":"#93c5fd",fontSize:11,fontWeight:900}}>{item.priorityLabel}</div><p style={{color:"#cbd5e1",fontSize:13,lineHeight:1.5,marginBottom:0}}>{item.executiveAction}</p></div>)}</div></section>

    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12,marginBottom:18}}>
      <div style={{...card,borderColor:"rgba(34,197,94,.35)"}}><div style={{...label,color:"#86efac"}}>Sell / pilot now</div><p style={{color:"#cbd5e1",lineHeight:1.55}}>Near-market assets where the next major proof should be a paying customer, not more feature expansion.</p>{portfolioQueues.sellNow.map(x=><div key={x.id} style={{marginTop:7}}><strong>{x.name}</strong> · {x.readiness}%</div>)}</div>
      <div style={{...card,borderColor:"rgba(96,165,250,.35)"}}><div style={{...label,color:"#93c5fd"}}>Finish → sell</div><p style={{color:"#cbd5e1",lineHeight:1.55}}>Products worth funding only through the smallest remaining commercial blocker before testing price and demand.</p>{portfolioQueues.finishAndSell.map(x=><div key={x.id} style={{marginTop:7}}><strong>{x.name}</strong> · {x.readiness}%</div>)}</div>
      <div style={{...card,borderColor:"rgba(251,191,36,.35)"}}><div style={{...label,color:"#fbbf24"}}>Portfolio discipline</div><p style={{color:"#fde68a",lineHeight:1.55}}>Incubated and held assets are option value, not permission to consume cash. A product moves forward because evidence improves—not because it is interesting.</p><strong>{portfolioOperatingSummary.incubate} incubating · {portfolioOperatingSummary.hold} held</strong></div>
    </section>

    <section style={{...card,marginBottom:18,borderColor:"rgba(251,191,36,.35)",background:"rgba(120,53,15,.15)"}}><div style={{...label,color:"#fbbf24"}}>Valuation doctrine</div><p style={{margin:"8px 0 14px",lineHeight:1.6,color:"#fde68a"}}>{inventoryValuationDoctrine.warning}</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}>{inventoryValuationDoctrine.layers.map(item=><div key={item.id} style={{padding:13,borderRadius:12,background:"rgba(2,6,23,.42)"}}><strong>{item.label}</strong><p style={{color:"#d1d5db",lineHeight:1.5,marginBottom:0}}>{item.definition}</p></div>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10,marginTop:12}}>{[["Revenue scenarios",range(inventorySummary.annualRevenueLow,inventorySummary.annualRevenueHigh)],["Replacement value",range(inventorySummary.replacementValueLow,inventorySummary.replacementValueHigh)],["Risk-adjusted IP",range(inventorySummary.riskAdjustedIpValueLow,inventorySummary.riskAdjustedIpValueHigh)],["Commercial potential",range(inventorySummary.commercialPotentialLow,inventorySummary.commercialPotentialHigh)]].map(([k,v])=><div key={k}><div style={label}>{k}</div><strong style={{fontSize:20}}>{v}</strong></div>)}</div></section>

    <InventoryOperatingDashboard items={operatingInventory}/>

    <section style={{...card,marginTop:24}}><div style={{...label,color:"#60a5fa"}}>Management rule</div><h2 style={{margin:"8px 0",fontSize:30}}>The inventory decides where attention goes.</h2><p style={{color:"#cbd5e1",lineHeight:1.65,maxWidth:1050,marginBottom:0}}>Priority score is a management aid, not a valuation or investment guarantee. It combines readiness, evidence quality, strategic disposition, conservative revenue scenario, and commercial potential. A high score earns focused validation. Actual customers, retention, margins, legal ownership, and production evidence must eventually replace estimates.</p></section>
  </div></main>;
}
