import fs from 'fs';
import path from 'path';
import type { LaunchDefinition, LaunchManifest, LaunchRegistryEntry } from './types';
import { getLaunchDefinition } from './definitions/ai-builder';

const SEO_PAGE_TYPES = [
  'What Is',
  'Beginner Guide',
  'Road to Expert',
  'Projects',
  'Common Mistakes',
  'Best Resources',
];

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFileIfMissing(filePath: string, content: string): boolean {
  if (fs.existsSync(filePath)) return false;
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content, 'utf8');
  return true;
}

function slugToConst(slug: string): string {
  return slug.replace(/-/g, '_').toUpperCase();
}

function generateBlueprintTs(def: LaunchDefinition): string {
  const c = slugToConst(def.slug);
  return `import type { DomainBlueprint } from './types';

export const ${c}_DOMAIN_SLUG = '${def.slug}';

export const ${c}_DOMAIN_BLUEPRINT: DomainBlueprint = ${JSON.stringify(def.blueprint, null, 2)};
`;
}

function generateLaunchBrief(def: LaunchDefinition): string {
  const bp = def.blueprint;
  return `# ${def.display_name} — Launch Brief

> Generated by Launch Factory · \`npm run launch:domain ${def.slug}\`

## Pass Gate

${def.notes ?? 'Does this create users, revenue, and retention?'}

## Outcome

**${bp.outcome.display_name}**

## Why Care

${bp.care_reason}

## First Project

${def.blueprint.projects[0]?.display_name}: ${def.first_project_action.text}

## Target User

${def.growth.target_user}

## Traffic Sources

${def.growth.traffic_sources.map((s) => `- ${s}`).join('\n')}

## Opportunity Score

${def.growth.opportunity_score}/70

## Do NOT Build

News site · Commentary · Predictions app. Build transformation domain.
`;
}

function generateLaunchChecklist(def: LaunchDefinition): string {
  return `# ${def.display_name} — Launch Checklist

## Platform (Domain Factory)
- [ ] Domain Blueprint registered
- [ ] Transformation path live
- [ ] First project assigned
- [ ] Collection scaffold (PKA)
- [ ] Community instance
- [ ] Evidence action wired
- [ ] Reputation + Mastery chain
- [ ] **Active Domain** — full HPI stack operational

## SEO Factory
${def.seo_pages.map((p) => `- [ ] ${p.title}`).join('\n')}

## Marketing
- [ ] Launch brief reviewed
- [ ] 30-day content calendar
- [ ] Email sequence (3 emails)
- [ ] Social calendar (2 weeks)
- [ ] SEO cluster map published

## Growth
- [ ] Target user validated
- [ ] Tier 2 hook: ${def.growth.tier_2_hook}
- [ ] Tier 3 hook: ${def.growth.tier_3_hook}
- [ ] KPIs tracked in Growth OS

## Success (not architecture)

- [ ] Real user completes first project
- [ ] Evidence submitted
- [ ] User knows what to do next
`;
}

function generateContentCalendar(def: LaunchDefinition): string {
  return `# ${def.display_name} — 30 Day Content Calendar

| Day | Channel | Topic |
|-----|---------|-------|
| 1 | SEO | ${def.seo_pages[0]?.title ?? 'What Is'} |
| 3 | Social | Outcome: ${def.blueprint.outcome.display_name} |
| 5 | SEO | ${def.seo_pages[1]?.title ?? 'Beginner Guide'} |
| 7 | Email | Welcome — why become an ${def.display_name}? |
| 10 | Social | First project: ${def.blueprint.projects[0]?.display_name} |
| 14 | SEO | ${def.seo_pages[2]?.title ?? 'Road to Expert'} |
| 17 | Social | Community invite: ${def.blueprint.community.display_name} |
| 21 | Email | Project nudge — ship your first evidence |
| 25 | SEO | ${def.seo_pages[4]?.title ?? 'Common Mistakes'} |
| 30 | Social | Mastery milestone celebration template |

Generated from blueprint — customize before publish.
`;
}

function generateEmailSequence(def: LaunchDefinition): string {
  return `# ${def.display_name} — Email Sequence

## Email 1 — Welcome (Day 0)
Subject: What are you becoming?
Body: ${def.blueprint.outcome.display_name}. Not another tutorial — a path with projects, evidence, and community.

## Email 2 — First Project (Day 3)
Subject: Your first project: ${def.blueprint.projects[0]?.display_name}
Body: ${def.first_project_action.text}. Submit evidence when done — Foundry remembers.

## Email 3 — Community (Day 7)
Subject: Join ${def.blueprint.community.display_name}
Body: ${def.growth.tier_3_hook}
`;
}

function generateSocialCalendar(def: LaunchDefinition): string {
  return `# ${def.display_name} — Social Calendar (14 days)

| Day | Platform | Post |
|-----|----------|------|
| 1 | X | "I'm becoming an ${def.display_name}" — identity hook |
| 2 | Reddit | Answer beginner question + link to Beginner Guide |
| 4 | X | Project prompt: ${def.first_project_action.text} |
| 7 | YouTube | Short: Road to ${def.display_name} overview |
| 10 | X | User story template (evidence-backed) |
| 14 | All | Community launch: ${def.blueprint.community.display_name} |
`;
}

function generateSeoClusterMap(def: LaunchDefinition) {
  return {
    domain: def.slug,
    vertical: def.vertical_slug,
    page_types: SEO_PAGE_TYPES,
    pages: def.seo_pages,
    cluster_formula: '25 domains × 500 entities × 20 pages = 250k indexed pages',
    publish_gate: 'content_score >= 70',
  };
}

function generateGrowthPlan(def: LaunchDefinition) {
  return {
    domain: def.slug,
    target_user: def.growth.target_user,
    traffic_sources: def.growth.traffic_sources,
    opportunity_score: def.growth.opportunity_score,
    monetization: {
      tier_2: { price: '$4/mo', hook: def.growth.tier_2_hook },
      tier_3: { price: '$18/mo', hook: def.growth.tier_3_hook },
    },
    kpis: def.growth.kpis,
    pass_gate: 'Users · Revenue · Retention — not another system',
  };
}

function generateMonetizationPlan(def: LaunchDefinition): string {
  return `# ${def.display_name} — Monetization Plan

| Tier | Price | Hook |
|------|-------|------|
| Free | $0 | Paths, browse, first project |
| Personal | $4/mo | ${def.growth.tier_2_hook} |
| Social | $18/mo | ${def.growth.tier_3_hook} |

Early validation target: 10 paid users before scaling SEO.
`;
}

function updateLaunchRegistry(root: string, slug: string, displayName: string, launchedAt: string) {
  const registryPath = path.join(root, 'marketing/launches/registry.json');
  let registry: { launches: LaunchRegistryEntry[]; bourbon_proof_started_at?: string } = {
    launches: [],
    bourbon_proof_started_at: '2026-06-11',
  };
  if (fs.existsSync(registryPath)) {
    registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
  }

  const bourbon = registry.launches.find((l) => l.slug === 'bourbon');
  if (!bourbon) {
    registry.launches.push({
      slug: 'bourbon',
      display_name: 'Bourbon',
      blueprint_started_at: registry.bourbon_proof_started_at ?? '2026-06-11',
      launched_at: '2026-06-11',
      active_at: '2026-06-11',
      days_blueprint_to_launch: 0,
      days_launch_to_active: 0,
      status: 'active',
    });
  }

  const existing = registry.launches.find((l) => l.slug === slug);
  const blueprintStarted = new Date().toISOString();
  if (existing) {
    existing.launched_at = launchedAt;
    existing.status = 'scaffolded';
  } else {
    registry.launches.push({
      slug,
      display_name: displayName,
      blueprint_started_at: blueprintStarted,
      launched_at: launchedAt,
      active_at: null,
      days_blueprint_to_launch: null,
      days_launch_to_active: null,
      status: 'scaffolded',
    });
  }

  ensureDir(path.dirname(registryPath));
  fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2), 'utf8');
}

export type ManufactureLaunchResult = {
  slug: string;
  manifest: LaunchManifest;
  files_created: string[];
  files_skipped: string[];
};

export function manufactureLaunch(root: string, slug: string): ManufactureLaunchResult {
  const def = getLaunchDefinition(slug);
  if (!def) {
    throw new Error(`Unknown domain "${slug}". Available: ai-builder (more coming via Launch Factory)`);
  }

  const launchedAt = new Date().toISOString();
  const marketingDir = path.join(root, 'marketing/launches', slug);
  const blueprintPath = path.join(root, 'packages/domain-blueprint/src', `${slug}-blueprint.ts`);

  const files_created: string[] = [];
  const files_skipped: string[] = [];

  const writes: [string, string][] = [
    [path.join(marketingDir, 'LAUNCH_BRIEF.md'), generateLaunchBrief(def)],
    [path.join(marketingDir, 'LAUNCH_CHECKLIST.md'), generateLaunchChecklist(def)],
    [path.join(marketingDir, 'content-calendar-30d.md'), generateContentCalendar(def)],
    [path.join(marketingDir, 'email-sequence.md'), generateEmailSequence(def)],
    [path.join(marketingDir, 'social-calendar.md'), generateSocialCalendar(def)],
    [path.join(marketingDir, 'monetization-plan.md'), generateMonetizationPlan(def)],
    [path.join(marketingDir, 'seo-cluster-map.json'), JSON.stringify(generateSeoClusterMap(def), null, 2)],
    [path.join(marketingDir, 'growth-plan.json'), JSON.stringify(generateGrowthPlan(def), null, 2)],
    [blueprintPath, generateBlueprintTs(def)],
  ];

  for (const [filePath, content] of writes) {
    if (writeFileIfMissing(filePath, content)) files_created.push(path.relative(root, filePath));
    else files_skipped.push(path.relative(root, filePath));
  }

  const manifest: LaunchManifest = {
    slug: def.slug,
    display_name: def.display_name,
    launched_at: launchedAt,
    status: 'scaffolded',
    assets: {
      platform: [
        'Domain Blueprint',
        'Transformation Paths',
        'Projects',
        'Collections',
        'Communities',
        'Roles',
        'Mastery Ladder',
      ],
      seo: def.seo_pages.map((p) => p.title),
      marketing: [
        'Launch Brief',
        'Launch Checklist',
        '30 Day Content Calendar',
        'Email Sequence',
        'Social Calendar',
        'SEO Cluster Map',
      ],
      growth: ['Target User', 'Traffic Sources', 'Opportunity Score', 'Monetization Plan', 'KPIs'],
    },
    blueprint_path: path.relative(root, blueprintPath),
    marketing_path: path.relative(root, marketingDir),
  };

  const manifestPath = path.join(marketingDir, 'launch.json');
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf8');
  files_created.push(path.relative(root, manifestPath));

  updateLaunchRegistry(root, def.slug, def.display_name, launchedAt);

  return { slug, manifest, files_created, files_skipped };
}

export function getLaunchRegistry(root: string): LaunchRegistryEntry[] {
  const registryPath = path.join(root, 'marketing/launches/registry.json');
  if (!fs.existsSync(registryPath)) {
    return [
      {
        slug: 'bourbon',
        display_name: 'Bourbon',
        blueprint_started_at: '2026-06-11',
        launched_at: '2026-06-11',
        active_at: '2026-06-11',
        days_blueprint_to_launch: 0,
        days_launch_to_active: 0,
        status: 'active',
      },
    ];
  }
  const data = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
  return data.launches ?? [];
}

export function computeLaunchVelocity(entries: LaunchRegistryEntry[]): {
  avg_days_blueprint_to_active: number | null;
  active_count: number;
  scaffolded_count: number;
  target_days_q4: number;
} {
  const active = entries.filter((e) => e.status === 'active' && e.active_at);
  const scaffolded = entries.filter((e) => e.status === 'scaffolded');
  const days = active
    .map((e) => {
      if (!e.blueprint_started_at || !e.active_at) return null;
      const start = new Date(e.blueprint_started_at).getTime();
      const end = new Date(e.active_at).getTime();
      return Math.round((end - start) / (1000 * 60 * 60 * 24));
    })
    .filter((d): d is number => d != null);

  return {
    avg_days_blueprint_to_active: days.length ? Math.round(days.reduce((a, b) => a + b, 0) / days.length) : null,
    active_count: active.length,
    scaffolded_count: scaffolded.length,
    target_days_q4: 7,
  };
}
