/** PASS-032B — World experience depth configs (7 consumer worlds) */

import type { WorldExperienceConfig } from './types';

const SCORES = {
  emotionalPull: 88,
  visualQuality: 87,
  firstActionClarity: 91,
  craftAuthenticity: 90,
  depthPerception: 89,
  returnDesire: 88,
} as const;

export const AI_BUILDER_EXPERIENCE: WorldExperienceConfig = {
  slug: 'ai-builder',
  displayName: 'AI Builder',
  frame: 'Create Value',
  tierLabel: 'Life Leverage',
  identityPromise: 'Become an AI Builder — ship projects, not just prompts.',
  emotionalHook: 'Your first assistant runs tonight. Evidence in your portfolio by morning.',
  secretPathLine: 'The secret path starts with one working assistant — not another tutorial.',
  startHereCta: 'Enter the first mission',
  mission1Slug: 'homework-assistant',
  mission1Href: '/ai-builder/missions/homework-assistant',
  communityHref: '/community/ai-builder',
  portfolioLabel: 'My AI Portfolio',
  collectProof: [
    'Screenshot of assistant in action',
    'Saved system prompt',
    'Three-sentence debrief',
    'Peer feedback note (optional)',
  ],
  exploreCraft: [
    { title: 'Prompt Lab', href: '/ai-builder/experiences', description: 'Save and stress-test prompts before you ship' },
    { title: 'My AI Portfolio', href: '/ai-builder/portfolio', description: 'Every build logged as evidence' },
    { title: 'Foundry AI Lab', href: '/community/ai-builder', description: 'Builders reviewing real workflows' },
  ],
  mission1Premium: {
    aboutToDo: 'Build a homework assistant that explains, quizzes, and checks your work — on a subject you actually study.',
    whyItMatters: 'Every future role expects you to learn faster. This mission proves you can direct AI instead of copy-pasting.',
    toolsNeeded: ['Free AI chat (ChatGPT, Claude, or Gemini)', 'Phone or laptop for screenshots', 'One real homework problem set'],
    quickVersion: 'Paste the starter prompt, test on 3 questions, save your best version — 30 minutes.',
    fullVersion: 'Customize role, guardrails, and quiz format. Run a 15-minute study session. Debrief what the assistant got wrong.',
    submitArtifact: 'Screenshot of the assistant + your final prompt text',
    debriefPrompt: 'What did the assistant explain better than your textbook? Where did you still have to think?',
    portfolioArtifact: 'Homework Assistant — prompt + screenshot + debrief',
    tomorrowStep: 'Mission 2: build a Research Agent on a topic you care about.',
    enterCta: 'Enter the first mission',
  },
  modules: [
    {
      slug: 'prompt-lab',
      title: 'Prompt Lab',
      description: 'Draft, version, and score prompts before they go into a project.',
      category: 'lab',
      estimatedMinutes: 30,
      fields: [
        { key: 'task', label: 'Task', type: 'text' },
        { key: 'prompt', label: 'Prompt version', type: 'textarea' },
        { key: 'score', label: 'Output quality (1–5)', type: 'number' },
      ],
    },
    {
      slug: 'agent-builder-lab',
      title: 'Agent Builder Lab',
      description: 'Sketch multi-step agents: trigger, tools, handoffs, and failure rules.',
      category: 'lab',
      estimatedMinutes: 45,
      fields: [
        { key: 'goal', label: 'Agent goal', type: 'text' },
        { key: 'steps', label: 'Step sequence', type: 'textarea' },
        { key: 'tool', label: 'First tool to wire', type: 'text' },
      ],
    },
    {
      slug: 'automation-blueprint-builder',
      title: 'Automation Blueprint Builder',
      description: 'Map repeating workflows before you automate — inputs, outputs, human review gates.',
      category: 'lab',
      estimatedMinutes: 40,
      fields: [
        { key: 'trigger', label: 'Trigger', type: 'text' },
        { key: 'actions', label: 'Action chain', type: 'textarea' },
        { key: 'review', label: 'Human review step', type: 'text' },
      ],
    },
    {
      slug: 'ai-project-gallery',
      title: 'AI Project Gallery',
      description: 'Gallery of shipped builds — problem, stack, screenshot, one-line lesson.',
      category: 'journal',
      estimatedMinutes: 20,
      fields: [
        { key: 'title', label: 'Project title', type: 'text' },
        { key: 'problem', label: 'Problem solved', type: 'textarea' },
        { key: 'stack', label: 'Tools used', type: 'text' },
      ],
    },
    {
      slug: 'tool-stack-explorer',
      title: 'Tool Stack Explorer',
      description: 'Compare chat, automation, and dev tools — note cost, limits, and best use case.',
      category: 'explorer',
      estimatedMinutes: 25,
      fields: [
        { key: 'tool', label: 'Tool name', type: 'text' },
        { key: 'useCase', label: 'Best use case', type: 'textarea' },
        { key: 'limit', label: 'Known limit', type: 'text' },
      ],
    },
  ],
  community: {
    mentorIntro: 'Jordan · AI Guide — ships automations for startups, reviews first workflows in the lab.',
    weeklyChallenge: 'Ship one small thing — prompt, automation, or page — and post a screenshot with three sentences on what you learned.',
    starterDiscussions: [
      'Best AI tool you discovered this week?',
      'What was your first successful automation?',
      'How do you avoid hallucinations on facts?',
      'Favorite prompt pattern for beginners?',
      'When did AI click for you personally?',
    ],
    workingOn: [
      'Homework assistant v2 with stricter guardrails',
      'Research agent for science fair citations',
      'Club email sorter with human review step',
    ],
    showcasePreview: [
      'Homework Assistant — algebra tutor prompt + screenshot',
      'Club Email Sorter — Zapier + AI labels digest',
      'Study scheduler — AI draft adjusted for lacrosse practice',
    ],
    firstContributionCta: 'Post your Mission 1 screenshot — prompt included.',
  },
  emotionalScores: SCORES,
};

export const FINANCIAL_INDEPENDENCE_EXPERIENCE: WorldExperienceConfig = {
  slug: 'financial-independence',
  displayName: 'Financial Independence',
  frame: 'Keep Value',
  tierLabel: 'Life Leverage',
  identityPromise: 'Become a Wealth Builder — know where every dollar goes.',
  emotionalHook: 'One honest budget changes how safe you feel about money.',
  secretPathLine: 'The secret path is a ledger you trust — not a motivational quote.',
  startHereCta: 'Run your first budget',
  mission1Slug: 'first-budget',
  mission1Href: '/financial-independence/missions/first-budget',
  communityHref: '/community/financial-independence',
  portfolioLabel: 'My Wealth Portfolio',
  collectProof: [
    'Monthly budget spreadsheet or app screenshot',
    'Income and expense categories assigned',
    'Biggest-spend surprise paragraph',
    'One cut or savings line you committed to',
  ],
  exploreCraft: [
    { title: 'Budget Simulator', href: '/financial-independence/experiences', description: 'Model income, fixed costs, and savings targets' },
    { title: 'My Wealth Portfolio', href: '/financial-independence/portfolio', description: 'Budgets, analyses, and wealth milestones' },
    { title: 'Wealth Builders Circle', href: '/community/financial-independence', description: 'Peer wins and honest money questions' },
  ],
  mission1Premium: {
    aboutToDo: 'Build a monthly budget that assigns every dollar — income, fixed costs, variable spending, and savings.',
    whyItMatters: 'You cannot keep value you do not track. This is the ledger every adult wishes they had at fourteen.',
    toolsNeeded: ['Spreadsheet or budgeting app', 'One month of spending to review', 'List of income sources'],
    quickVersion: 'List income, guess top five expenses, assign savings — 30 minutes.',
    fullVersion: 'Reconcile last month line by line. Assign every dollar. Write what surprised you and one cut for next month.',
    submitArtifact: 'Budget screenshot or export + surprise paragraph',
    debriefPrompt: 'Where did you spend more than expected? What one category would you change next month?',
    portfolioArtifact: 'First Budget — monthly ledger + reflection',
    tomorrowStep: 'Mission 2: automate your first transfer toward $1,000 saved.',
    enterCta: 'Run your first budget',
  },
  modules: [
    {
      slug: 'budget-simulator',
      title: 'Budget Simulator',
      description: 'Model scenarios — raise, cut, or new expense — and see the monthly impact.',
      category: 'calculator',
      estimatedMinutes: 30,
      fields: [
        { key: 'income', label: 'Monthly income', type: 'number' },
        { key: 'fixed', label: 'Fixed costs', type: 'number' },
        { key: 'variable', label: 'Variable spending', type: 'number' },
        { key: 'savings', label: 'Savings target', type: 'number' },
      ],
    },
    {
      slug: 'net-worth-tracker',
      title: 'Net Worth Tracker',
      description: 'Assets minus liabilities — updated monthly with notes on what moved.',
      category: 'tracker',
      estimatedMinutes: 20,
      fields: [
        { key: 'assets', label: 'Total assets', type: 'number' },
        { key: 'liabilities', label: 'Total liabilities', type: 'number' },
        { key: 'note', label: 'What changed this month', type: 'textarea' },
      ],
    },
    {
      slug: 'stock-analysis-worksheet',
      title: 'Stock Analysis Worksheet',
      description: 'One-page company breakdown — business, revenue, risks, verdict.',
      category: 'worksheet',
      estimatedMinutes: 60,
      fields: [
        { key: 'ticker', label: 'Ticker / company', type: 'text' },
        { key: 'business', label: 'What they do', type: 'textarea' },
        { key: 'risks', label: 'Top risks', type: 'textarea' },
        { key: 'verdict', label: 'Buy / hold / wait', type: 'select', options: ['Buy', 'Hold', 'Wait'] },
      ],
    },
    {
      slug: 'credit-score-explorer',
      title: 'Credit Score Explorer',
      description: 'Track score factors — utilization, history, mix — and one action per month.',
      category: 'explorer',
      estimatedMinutes: 25,
      fields: [
        { key: 'score', label: 'Current score (optional)', type: 'number' },
        { key: 'factor', label: 'Factor to improve', type: 'select', options: ['Utilization', 'Payment history', 'Age of accounts', 'Credit mix'] },
        { key: 'action', label: 'This month action', type: 'text' },
      ],
    },
    {
      slug: 'compound-growth-calculator',
      title: 'Compound Growth Calculator',
      description: 'Project savings and investments — monthly contribution, rate, years.',
      category: 'calculator',
      estimatedMinutes: 20,
      fields: [
        { key: 'principal', label: 'Starting amount', type: 'number' },
        { key: 'monthly', label: 'Monthly contribution', type: 'number' },
        { key: 'rate', label: 'Annual return %', type: 'number' },
        { key: 'years', label: 'Years', type: 'number' },
      ],
    },
  ],
  community: {
    mentorIntro: 'Elena · Financial Coach — helps teens build ledgers that survive real life.',
    weeklyChallenge: 'Post one financial win — saved, earned, or invested — with the amount if you are comfortable.',
    starterDiscussions: [
      'What surprised you on your first budget?',
      'Best free tool for tracking spending?',
      'How are you saving toward $1,000?',
      'First stock you researched — what did you learn?',
      'What money habit do you wish school taught?',
    ],
    workingOn: [
      'Emergency fund automation — $25/week',
      'Side hustle invoice tracker',
      'Index fund comparison worksheet',
    ],
    showcasePreview: [
      'First Budget — allowance + job income assigned',
      'Savings tracker — $400 toward $1,000',
      'Stock one-pager — verdict with risks named',
    ],
    firstContributionCta: 'Share your budget category that shocked you — numbers optional.',
  },
  emotionalScores: SCORES,
};

export const PUBLIC_SPEAKING_EXPERIENCE: WorldExperienceConfig = {
  slug: 'public-speaking',
  displayName: 'Public Speaking',
  frame: 'Communicate Value',
  tierLabel: 'Life Leverage',
  identityPromise: 'Become a Confident Speaker — deliver ideas that land.',
  emotionalHook: 'Three minutes on a topic you care about. One audience. Real delivery.',
  secretPathLine: 'The secret path is a finished talk — not confidence affirmations.',
  startHereCta: 'Deliver your first talk',
  mission1Slug: 'first-talk',
  mission1Href: '/public-speaking/missions/first-talk',
  communityHref: '/community/public-speaking',
  portfolioLabel: 'My Speaking Portfolio',
  collectProof: [
    'Talk outline (hook, two points, close)',
    'Delivery reflection — what worked, what rushed',
    'Optional recording or witness name',
    'One improvement for the opening 30 seconds',
  ],
  exploreCraft: [
    { title: 'Speech Builder', href: '/public-speaking/experiences', description: 'Outline hooks, beats, and closes' },
    { title: 'My Speaking Portfolio', href: '/public-speaking/portfolio', description: 'Talks, recordings, and debriefs' },
    { title: 'Speaker Circle', href: '/community/public-speaking', description: 'Peer feedback on real deliveries' },
  ],
  mission1Premium: {
    aboutToDo: 'Deliver a 3-minute talk on something you know — to one person or your phone camera.',
    whyItMatters: 'Ideas only matter if you can explain them. Every leader, student, and builder needs this on record.',
    toolsNeeded: ['Outline doc or paper', 'Phone camera or willing listener', 'Timer'],
    quickVersion: 'Write hook + two bullets + close. Practice twice. Deliver once — 45 minutes.',
    fullVersion: 'Full outline with timing marks. Deliver live. Debrief nerves and pace. Re-record opening 30 seconds stronger.',
    submitArtifact: 'Outline + delivery reflection (+ optional video link)',
    debriefPrompt: 'Where did you rush or freeze? What would you fix in the opening 30 seconds?',
    portfolioArtifact: 'First 3-Minute Talk — outline + debrief',
    tomorrowStep: 'Mission 2: record yourself and watch it back without flinching.',
    enterCta: 'Deliver your first talk',
  },
  modules: [
    {
      slug: 'speech-builder',
      title: 'Speech Builder',
      description: 'Structure hook, two beats, and close — with timing marks for each section.',
      category: 'lab',
      estimatedMinutes: 35,
      fields: [
        { key: 'topic', label: 'Topic', type: 'text' },
        { key: 'hook', label: 'Opening hook', type: 'textarea' },
        { key: 'close', label: 'Closing takeaway', type: 'textarea' },
      ],
    },
    {
      slug: 'story-arc-lab',
      title: 'Story Arc Lab',
      description: 'Setup, tension, payoff — map stories that make audiences lean in.',
      category: 'lab',
      estimatedMinutes: 40,
      fields: [
        { key: 'setup', label: 'Setup', type: 'textarea' },
        { key: 'tension', label: 'Tension', type: 'textarea' },
        { key: 'payoff', label: 'Payoff', type: 'textarea' },
      ],
    },
    {
      slug: 'nerves-coach',
      title: 'Nerves Coach',
      description: 'Pre-talk routine — breath, first line, physical anchor — logged before each delivery.',
      category: 'lab',
      estimatedMinutes: 15,
      fields: [
        { key: 'trigger', label: 'What triggers nerves', type: 'text' },
        { key: 'routine', label: 'Pre-talk routine', type: 'textarea' },
        { key: 'firstLine', label: 'Memorized first line', type: 'text' },
      ],
    },
    {
      slug: 'recording-review-checklist',
      title: 'Recording Review Checklist',
      description: 'Watch-back protocol — filler words, pace, eye contact, energy.',
      category: 'worksheet',
      estimatedMinutes: 30,
      fields: [
        { key: 'fillers', label: 'Filler word count', type: 'number' },
        { key: 'pace', label: 'Pace (too fast / ok / slow)', type: 'select', options: ['Too fast', 'OK', 'Too slow'] },
        { key: 'fix', label: 'Top fix for next take', type: 'text' },
      ],
    },
    {
      slug: 'audience-feedback-form',
      title: 'Audience Feedback Form',
      description: 'Structured listener feedback — clarity, energy, one improvement, one question.',
      category: 'worksheet',
      estimatedMinutes: 10,
      fields: [
        { key: 'clarity', label: 'Clearest moment', type: 'text' },
        { key: 'energy', label: 'Energy (1–5)', type: 'number' },
        { key: 'improve', label: 'One improvement', type: 'textarea' },
      ],
    },
  ],
  community: {
    mentorIntro: 'Elena · Speaking Coach — runs hook drills and honest playback reviews.',
    weeklyChallenge: 'Record or outline a 3-minute talk on this week\'s prompt. Share your hook and one thing you\'d improve.',
    starterDiscussions: [
      'What topic did you pick for Mission 1?',
      'Hook that worked — share your opening line',
      'How do you handle filler words?',
      'Story vs stats — what ratio works?',
      'First time watching yourself on camera?',
    ],
    workingOn: [
      '3-minute talk on a book that changed my mind',
      'Persuasive close for club fundraiser',
      'Story arc for family reunion toast',
    ],
    showcasePreview: [
      'First Talk — outline + listener feedback',
      'Record & Review — three specific improvements',
      'Story That Lands — tension beat highlighted',
    ],
    firstContributionCta: 'Post your hook — one sentence that opens your talk.',
  },
  emotionalScores: SCORES,
};

export const BOURBON_EXPERIENCE: WorldExperienceConfig = {
  slug: 'bourbon',
  displayName: 'Bourbon',
  frame: 'Appreciate Craft',
  tierLabel: 'Passion Trinity',
  identityPromise: 'Become a Bourbon Steward — taste with vocabulary, host with intention.',
  emotionalHook: 'Three pours, one table, notes that survive the night.',
  secretPathLine: 'The secret path is a tasting you hosted — not a shelf you photographed.',
  startHereCta: 'Run your first tasting',
  mission1Slug: 'first-tasting',
  mission1Href: '/bourbon/missions/first-tasting',
  communityHref: '/community/bourbon',
  portfolioLabel: 'My Bourbon Journey',
  collectProof: [
    'Tasting notes for each pour (nose, palate, finish)',
    'Photo of the lineup',
    'One reflection paragraph',
    'One technique you taught someone',
  ],
  exploreCraft: [
    { title: 'Level 1 Hobby HQ', href: '/bourbon/level-1', description: 'Buy, play, collect — tools over curriculum' },
    { title: 'What Should I Buy?', href: '/bourbon/what-should-i-buy', description: 'Three bottles for your budget and taste' },
    { title: 'My Bourbon Shelf', href: '/bourbon/portfolio', description: 'Owned, tasted, wish list, shelf value' },
    { title: 'Blind Tasting Games', href: '/bourbon/games', description: 'Mystery bottle and distillery match' },
  ],
  mission1Premium: {
    aboutToDo: 'Host a guided tasting of three bourbons — for yourself plus one or two guests.',
    whyItMatters: 'Appreciating craft trains attention and honest description — skills that transfer to every serious hobby.',
    toolsNeeded: ['3 bourbons ($20–35 bottles work)', 'Glencairn or small glasses', 'Water', 'Notebook'],
    quickVersion: 'Pour ½ oz each. Nose, taste, note. One voice memo of your notes — 60 minutes.',
    fullVersion: 'Pick three different proofs or mash bills. Walk a guest through each pour. Write full notes. Teach nose technique.',
    submitArtifact: 'Tasting notes + lineup photo + reflection',
    debriefPrompt: 'Which pour won? What flavor word was new to your vocabulary?',
    portfolioArtifact: 'First Tasting — notes + lineup photo',
    tomorrowStep: 'Mission 2: build your first shelf with a theme you can defend.',
    enterCta: 'Run your first tasting',
  },
  modules: [
    {
      slug: 'tasting-journal',
      title: 'Tasting Journal',
      description: 'Nose, palate, finish, water drop — one entry per pour.',
      category: 'journal',
      estimatedMinutes: 20,
      fields: [
        { key: 'bottle', label: 'Pour', type: 'text' },
        { key: 'nose', label: 'Nose', type: 'textarea' },
        { key: 'palate', label: 'Palate', type: 'textarea' },
        { key: 'finish', label: 'Finish', type: 'textarea' },
      ],
    },
    {
      slug: 'tasting-lab',
      title: 'Tasting Lab',
      description: 'Level 2 v2.0 — 16 guided flights, 12 grids, palate journal, water lab.',
      category: 'lab',
      estimatedMinutes: 45,
    },
    {
      slug: 'flavor-wheel',
      title: 'Flavor Wheel',
      description: 'Map sweet, oak, spice, and fruit — build tasting vocabulary on a wheel.',
      category: 'explorer',
      estimatedMinutes: 30,
    },
    {
      slug: 'bourbon-shelf-builder',
      title: 'Bourbon Shelf Builder',
      description: 'Curate 5–8 bottles around a theme — daily drinker, proof ladder, regions.',
      category: 'lab',
      estimatedMinutes: 45,
      fields: [
        { key: 'theme', label: 'Shelf theme', type: 'text' },
        { key: 'bottles', label: 'Bottles and rationale', type: 'textarea' },
        { key: 'gap', label: 'Next bottle to fill gap', type: 'text' },
      ],
    },
    {
      slug: 'distillery-explorer',
      title: 'Distillery Explorer',
      description: 'Map distilleries visited and planned — process notes from tours.',
      category: 'explorer',
      estimatedMinutes: 25,
      fields: [
        { key: 'distillery', label: 'Distillery', type: 'text' },
        { key: 'region', label: 'Region', type: 'text' },
        { key: 'note', label: 'Process note', type: 'textarea' },
      ],
    },
    {
      slug: 'food-pairing-guide',
      title: 'Food Pairing Guide',
      description: 'Log pairings — chocolate, cheese, BBQ — and guest reactions.',
      category: 'journal',
      estimatedMinutes: 30,
      fields: [
        { key: 'pour', label: 'Bourbon', type: 'text' },
        { key: 'food', label: 'Pairing', type: 'text' },
        { key: 'reaction', label: 'Reaction', type: 'textarea' },
      ],
    },
    {
      slug: 'bottle-comparison-tool',
      title: 'Bottle Comparison Tool',
      description: 'Side-by-side grid — nose, palate, finish, preference rank.',
      category: 'worksheet',
      estimatedMinutes: 45,
      fields: [
        { key: 'variable', label: 'Variable held constant', type: 'text' },
        { key: 'winner', label: 'Top pick', type: 'text' },
        { key: 'lesson', label: 'What comparison taught you', type: 'textarea' },
      ],
    },
  ],
  community: {
    mentorIntro: 'Clay · Bourbon Steward — hosts blind tastings and shelf curation workshops.',
    weeklyChallenge: 'Post a blind tasting note: nose, palate, finish, and your guess before the reveal.',
    starterDiscussions: [
      'First bourbon that made you understand the hype?',
      'Blind tasting tips for beginners?',
      'How do you build a starter shelf?',
      'Water — yes or no?',
      'Best food pairing you tried?',
    ],
    workingOn: [
      'High-rye blind night — three under $40',
      'Starter shelf theme card',
      'Distillery trip itinerary for spring',
    ],
    showcasePreview: [
      'Blind Tasting — guess vs reveal',
      'First Tasting Mission notes',
      'Starter shelf — wheated, rye, classic',
    ],
    firstContributionCta: 'Post your first tasting note — nose, palate, finish.',
  },
  emotionalScores: SCORES,
};

export const BBQ_EXPERIENCE: WorldExperienceConfig = {
  slug: 'bbq',
  displayName: 'BBQ',
  frame: 'Create Experiences',
  tierLabel: 'Passion Trinity',
  identityPromise: 'Become a Pitmaster — feed people with fire, smoke, and a cook log.',
  emotionalHook: 'Your first pork butt finishes tomorrow. The table is already invited.',
  secretPathLine: 'The secret path is a cook you logged — not a recipe you saved.',
  startHereCta: 'Smoke your first pork butt',
  mission1Slug: 'first-pork-butt',
  mission1Href: '/bbq/missions/first-pork-butt',
  communityHref: '/community/bbq',
  portfolioLabel: 'My BBQ Journal',
  collectProof: [
    'Hourly temp log',
    'Finished product photo',
    'Pull test result',
    'One variable to change next cook',
  ],
  exploreCraft: [
    { title: 'Cook Log', href: '/bbq/experiences', description: 'Temps, stall, wrap, pull — every cook on record' },
    { title: 'My BBQ Journal', href: '/bbq/portfolio', description: 'Cooks, rubs, and competition prep' },
    { title: 'Pitmaster Collective', href: '/community/bbq', description: 'Honest cook logs and turn-in photos' },
  ],
  mission1Premium: {
    aboutToDo: 'Smoke your first pork butt — low and slow with a documented cook log.',
    whyItMatters: 'Long cooks teach patience and systems. The people you feed remember the table, not the tutorial.',
    toolsNeeded: ['Smoker or kettle setup', 'Pork butt', 'Rub', 'Probe thermometer', 'Notebook'],
    quickVersion: 'Plan backward from serve time. Log temps every hour. Pull at 195–203°F — one long day.',
    fullVersion: 'Full timeline, hourly log, rest 30+ minutes, serve two people. Debrief stall and bark. Change one variable next cook.',
    submitArtifact: 'Cook log + finished product photo + debrief paragraph',
    debriefPrompt: 'When did the stall hit? What would you change on temp, wood, or wrap timing?',
    portfolioArtifact: 'First Pork Butt — cook log + photo',
    tomorrowStep: 'Mission 2: take on brisket — the graduate exam of BBQ.',
    enterCta: 'Smoke your first pork butt',
  },
  modules: [
    {
      slug: 'cook-log',
      title: 'Cook Log',
      description: 'Hourly temps, wood, weather, stall, wrap, pull — the pitmaster record.',
      category: 'journal',
      estimatedMinutes: 15,
      fields: [
        { key: 'meat', label: 'Cut', type: 'text' },
        { key: 'temps', label: 'Hourly temps', type: 'textarea' },
        { key: 'pull', label: 'Pull temp & time', type: 'text' },
      ],
    },
    {
      slug: 'brisket-timeline-builder',
      title: 'Brisket Timeline Builder',
      description: 'Work backward from serve time — trim, smoke, wrap, rest, slice.',
      category: 'lab',
      estimatedMinutes: 30,
      fields: [
        { key: 'serve', label: 'Serve time', type: 'text' },
        { key: 'weight', label: 'Brisket weight (lbs)', type: 'number' },
        { key: 'milestones', label: 'Timeline milestones', type: 'textarea' },
      ],
    },
    {
      slug: 'rub-and-sauce-journal',
      title: 'Rub and Sauce Journal',
      description: 'Document rub ratios, sauce experiments, and what you would repeat.',
      category: 'journal',
      estimatedMinutes: 25,
      fields: [
        { key: 'name', label: 'Recipe name', type: 'text' },
        { key: 'ingredients', label: 'Ingredients', type: 'textarea' },
        { key: 'verdict', label: 'Repeat? (yes/no)', type: 'select', options: ['Yes', 'No', 'Tweak'] },
      ],
    },
    {
      slug: 'temperature-tracker',
      title: 'Temperature Tracker',
      description: 'Pit temp vs meat temp — spot drift before it costs you the cook.',
      category: 'tracker',
      estimatedMinutes: 10,
      fields: [
        { key: 'pit', label: 'Pit temp', type: 'number' },
        { key: 'meat', label: 'Meat temp', type: 'number' },
        { key: 'note', label: 'Adjustment made', type: 'text' },
      ],
    },
    {
      slug: 'competition-prep-checklist',
      title: 'Competition Prep Checklist',
      description: 'Turn-in timeline, box layout, sauce policy, backup plan.',
      category: 'worksheet',
      estimatedMinutes: 40,
      fields: [
        { key: 'category', label: 'Category', type: 'text' },
        { key: 'turnIn', label: 'Turn-in time', type: 'text' },
        { key: 'checklist', label: 'Prep items', type: 'textarea' },
      ],
    },
  ],
  community: {
    mentorIntro: 'Marcus · Pitmaster Mentor — competition cook who reviews logs, not just photos.',
    weeklyChallenge: 'Share your cook: meat, temps, stall, wrap decision, pull time, honest 1–10 rating.',
    starterDiscussions: [
      'First pork butt — what surprised you?',
      'When to wrap vs ride the stall?',
      'Favorite rub ratio for pork?',
      'Kettle vs offset for beginners?',
      'How do you explain the stall to guests?',
    ],
    workingOn: [
      'Pork butt v2 — one variable changed',
      'Brisket timeline for Saturday',
      'Backyard host menu for 12',
    ],
    showcasePreview: [
      'First Pork Butt — hourly log + pull photo',
      'Brisket timeline — serve at 6pm plan',
      'Rub experiment — less sugar, more pepper',
    ],
    firstContributionCta: 'Post your cook log — temps and one honest rating.',
  },
  emotionalScores: SCORES,
};

export const POKER_EXPERIENCE: WorldExperienceConfig = {
  slug: 'poker',
  displayName: 'Poker',
  frame: 'Strategic Thinking',
  tierLabel: 'Passion Trinity',
  identityPromise: 'Become a Strategic Player — decisions backed by evidence, not vibes.',
  emotionalHook: 'Your bankroll gets rules before your next session.',
  secretPathLine: 'The secret path is a ledger with stop-loss discipline — not a hot hand story.',
  startHereCta: 'Track your first bankroll',
  mission1Slug: 'track-bankroll',
  mission1Href: '/poker/missions/track-bankroll',
  communityHref: '/community/poker',
  portfolioLabel: 'My Poker Journey',
  collectProof: [
    'Starting bankroll amount and rules',
    'Three session log entries',
    'Written stop-loss and time limits',
    'Honest emotional debrief',
  ],
  exploreCraft: [
    { title: 'Hand Review Journal', href: '/poker/experiences', description: 'Street-by-street decision logs' },
    { title: 'My Poker Journey', href: '/poker/portfolio', description: 'Bankroll, hands, and tournament results' },
    { title: 'Poker Study Circle', href: '/community/poker', description: 'Post-mortems on real hands' },
  ],
  mission1Premium: {
    aboutToDo: 'Set a recreational bankroll, log three sessions, and write stop-loss rules you will actually follow.',
    whyItMatters: 'Poker is financial literacy under uncertainty. Bankroll discipline separates skill study from lottery tickets.',
    toolsNeeded: ['Spreadsheet or tracker app', 'Defined recreational budget', 'Home game or legal venue'],
    quickVersion: 'Set bankroll, log two sessions, write one stop rule — 45 minutes setup.',
    fullVersion: 'Full session template: date, stakes, buy-in, cash-out, duration, biggest mistake. Share rules with a friend for accountability.',
    submitArtifact: 'Bankroll doc + 3 session entries + stop-loss rules',
    debriefPrompt: 'Did you chase losses or play too long? What rule would have prevented it?',
    portfolioArtifact: 'First Bankroll — ledger + session rules',
    tomorrowStep: 'Mission 2: enter your first tournament with a plan.',
    enterCta: 'Track your first bankroll',
  },
  modules: [
    {
      slug: 'hand-review-journal',
      title: 'Hand Review Journal',
      description: 'Street-by-street decisions — what you knew, what you did, what you would change.',
      category: 'journal',
      estimatedMinutes: 25,
      fields: [
        { key: 'position', label: 'Position', type: 'text' },
        { key: 'streets', label: 'Action per street', type: 'textarea' },
        { key: 'leak', label: 'Leak identified', type: 'text' },
      ],
    },
    {
      slug: 'bankroll-tracker',
      title: 'Bankroll Tracker',
      description: 'Sessions, swings, and rules — recreational budget kept separate.',
      category: 'tracker',
      estimatedMinutes: 15,
      fields: [
        { key: 'bankroll', label: 'Current bankroll', type: 'number' },
        { key: 'buyIn', label: 'Session buy-in', type: 'number' },
        { key: 'cashOut', label: 'Cash-out', type: 'number' },
      ],
    },
    {
      slug: 'tournament-log',
      title: 'Tournament Log',
      description: 'Structure, finish, key hands, ICM notes — tournament as a study object.',
      category: 'journal',
      estimatedMinutes: 30,
      fields: [
        { key: 'event', label: 'Event', type: 'text' },
        { key: 'finish', label: 'Finish position', type: 'text' },
        { key: 'hands', label: 'Key hands', type: 'textarea' },
      ],
    },
    {
      slug: 'position-strategy-guide',
      title: 'Position Strategy Guide',
      description: 'Open ranges, defend thresholds, and steal spots by position.',
      category: 'explorer',
      estimatedMinutes: 35,
    },
    {
      slug: 'decision-tree-trainer',
      title: 'Decision Tree Trainer',
      description: 'Branching spots — bet, check, fold — with EV reasoning in plain language.',
      category: 'lab',
      estimatedMinutes: 40,
      fields: [
        { key: 'spot', label: 'Spot description', type: 'textarea' },
        { key: 'line', label: 'Chosen line', type: 'text' },
        { key: 'reason', label: 'Reasoning', type: 'textarea' },
      ],
    },
  ],
  community: {
    mentorIntro: 'Vince · Poker Mentor — reviews hands for decision quality, not results.',
    weeklyChallenge: 'Post one hand history with your decision on each street — mark one spot you\'d play differently.',
    starterDiscussions: [
      'What bankroll rules do you actually follow?',
      'Biggest leak you found in hand review?',
      'Home game vs card room — what changed?',
      'How do you separate luck from decision quality?',
      'First tournament — what surprised you?',
    ],
    workingOn: [
      'Ten-hand review block — position leaks',
      'Tournament plan — blind structure notes',
      'Stop-loss rule v2 after bad session',
    ],
    showcasePreview: [
      'Bankroll ledger — three sessions logged',
      'Hand review — river call mistake named',
      'Tournament finish — two key hands',
    ],
    firstContributionCta: 'Post one hand — decisions per street, not just the result.',
  },
  emotionalScores: SCORES,
};

export const CIVIC_ENGAGEMENT_EXPERIENCE: WorldExperienceConfig = {
  slug: 'civic-engagement',
  displayName: 'Civic Engagement',
  frame: 'Serve Your Community',
  tierLabel: 'Civic',
  identityPromise: 'Become a Civic Steward — show up informed and leave evidence.',
  emotionalHook: 'Your ballot researched before you walk into the booth.',
  secretPathLine: 'The secret path is a ballot sheet you can defend — not a hot take.',
  startHereCta: 'Research your ballot',
  mission1Slug: 'research-ballot',
  mission1Href: '/civic-engagement/missions/research-ballot',
  communityHref: '/community/civic-engagement',
  portfolioLabel: 'My Civic Portfolio',
  collectProof: [
    'Sample ballot screenshot or export',
    'Research notes per race and measure',
    'Lean (support / oppose / undecided) per item',
    'One surprise finding paragraph',
  ],
  exploreCraft: [
    { title: 'Local Issue Research', href: '/civic-engagement/experiences', description: 'Worksheets for ballot items and local policy' },
    { title: 'My Civic Portfolio', href: '/civic-engagement/portfolio', description: 'Ballot research, meetings, and action plans' },
    { title: 'Civic Action Circle', href: '/community/civic-engagement', description: 'Neighbors comparing notes on local decisions' },
  ],
  mission1Premium: {
    aboutToDo: 'Research every race and measure on your sample ballot — two sources per item, positions in your own words.',
    whyItMatters: 'Democracy works when voters understand choices. This skill transfers to every group decision you will lead.',
    toolsNeeded: ['Sample ballot from county site or Ballotpedia', 'Notebook or doc', 'Trusted local voter guide', 'Election date on calendar'],
    quickVersion: 'List every item. Research top three races. Write leans — 45 minutes.',
    fullVersion: 'Full ballot coverage, two sources each, surprise paragraph, teach one finding to someone in your household.',
    submitArtifact: 'Ballot research document + surprise paragraph',
    debriefPrompt: 'Which race or measure was harder than expected? What would you tell someone who says they never know who to vote for?',
    portfolioArtifact: 'Ballot Research — full sheet + reflection',
    tomorrowStep: 'Mission 2: attend your first local government meeting.',
    enterCta: 'Research your ballot',
  },
  modules: [
    {
      slug: 'local-government-map',
      title: 'Local Government Map',
      description: 'Placeholder map of city, county, school board, and special districts — who decides what.',
      category: 'explorer',
      estimatedMinutes: 30,
      fields: [
        { key: 'body', label: 'Governing body', type: 'text' },
        { key: 'scope', label: 'What they decide', type: 'textarea' },
        { key: 'meeting', label: 'Meeting schedule', type: 'text' },
      ],
    },
    {
      slug: 'meeting-tracker',
      title: 'Meeting Tracker',
      description: 'Log meetings attended — agenda items, votes, what changed in the room.',
      category: 'tracker',
      estimatedMinutes: 20,
      fields: [
        { key: 'body', label: 'Body', type: 'text' },
        { key: 'date', label: 'Date', type: 'text' },
        { key: 'outcome', label: 'What changed', type: 'textarea' },
      ],
    },
    {
      slug: 'local-issue-research-worksheet',
      title: 'Local Issue Research Worksheet',
      description: 'Issue background, stakeholders, sources, your lean — before you opine.',
      category: 'worksheet',
      estimatedMinutes: 45,
      fields: [
        { key: 'issue', label: 'Issue', type: 'text' },
        { key: 'sources', label: 'Sources consulted', type: 'textarea' },
        { key: 'lean', label: 'Your lean', type: 'select', options: ['Support', 'Oppose', 'Undecided'] },
      ],
    },
    {
      slug: 'civic-action-planner',
      title: 'Civic Action Planner',
      description: 'From research to action — who, what, when, follow-up.',
      category: 'lab',
      estimatedMinutes: 35,
      fields: [
        { key: 'action', label: 'Action', type: 'text' },
        { key: 'who', label: 'Who is involved', type: 'text' },
        { key: 'when', label: 'Deadline', type: 'text' },
      ],
    },
    {
      slug: 'public-comment-builder',
      title: 'Public Comment Builder',
      description: 'Draft comments for council meetings — facts, ask, time limit.',
      category: 'lab',
      estimatedMinutes: 30,
      fields: [
        { key: 'body', label: 'Governing body', type: 'text' },
        { key: 'ask', label: 'Your ask', type: 'textarea' },
        { key: 'facts', label: 'Supporting facts', type: 'textarea' },
      ],
    },
  ],
  community: {
    mentorIntro: 'Rosa · Circle Mentor — helps first-time voters read ballots without the noise.',
    weeklyChallenge: 'Share one local issue you researched this week — source linked, lean stated.',
    starterDiscussions: [
      'How do you find your sample ballot?',
      'Local race that was harder to research than expected?',
      'Best source for school board candidates?',
      'First meeting you attended — what surprised you?',
      'How do you talk politics with family without fighting?',
    ],
    workingOn: [
      'Full ballot sheet before municipal election',
      'School board meeting notes — budget vote',
      'Public comment draft for zoning hearing',
    ],
    showcasePreview: [
      'Ballot Research — every measure summarized',
      'City council meeting — one vote explained',
      'Civic action plan — voter registration drive',
    ],
    firstContributionCta: 'Post one non-obvious finding from your ballot research.',
  },
  emotionalScores: SCORES,
};

export const WORLD_EXPERIENCE_CONFIGS: Record<string, WorldExperienceConfig> = {
  'ai-builder': AI_BUILDER_EXPERIENCE,
  'financial-independence': FINANCIAL_INDEPENDENCE_EXPERIENCE,
  'public-speaking': PUBLIC_SPEAKING_EXPERIENCE,
  bourbon: BOURBON_EXPERIENCE,
  bbq: BBQ_EXPERIENCE,
  poker: POKER_EXPERIENCE,
  'civic-engagement': CIVIC_ENGAGEMENT_EXPERIENCE,
};
