import type { WorldLoreBundle } from '../types';
import { BOURBON_LEGENDS } from './bourbon/legends';
import { BOURBON_DEBATES, BOURBON_LEGENDARY_OBJECTS } from './bourbon/debates-objects';
import { BOURBON_UNIVERSE_MAP, BOURBON_FOUNDRY_ORIGINALS } from './bourbon/universe';

export const BOURBON_LORE: WorldLoreBundle = {
  world_slug: 'bourbon',
  world_name: 'Bourbon',
  tagline: 'Mythology, not curriculum — the stories that make you come back.',
  heroes: [
    {
      id: 'pappy',
      name: 'Pappy Van Winkle',
      tagline: 'The patient steward who became a legend after he was gone.',
      obsession: 'Age over hype — Julian Van Winkle Sr. believed time in the barrel was the product, not marketing.',
      failure: 'Sold the family distillery in 1972. The brand nearly disappeared with Stitzel-Weller.',
      breakthrough: 'His grandson rebuilt Old Rip and Pappy from sourced and aged stock — scarcity became religion.',
      whyMatters: 'Pappy is not about one bottle — it is about patience, family legacy, and what happens when supply meets mythology.',
    },
    {
      id: 'bill-samuels',
      name: 'Bill Samuels Sr.',
      tagline: 'The man who burned the recipe.',
      obsession: 'Bourbon your wife would drink — wheat instead of rye, softness over burn.',
      failure: 'Literally burned the family bourbon recipe. Started over with red winter wheat.',
      breakthrough: "Maker's Mark and the red wax dip — hospitality as product design.",
      whyMatters: 'He proved bourbon could be engineered for approachability without apologizing for quality.',
    },
    {
      id: 'jimmy-russell',
      name: 'Jimmy Russell',
      tagline: 'Six decades on the same hill — Wild Turkey as a life sentence.',
      obsession: '101 proof as a statement. High rye, high character, no apologies.',
      failure: 'Survived industry consolidation, flavorless decades, and bourbon being "grandpa\'s drink."',
      breakthrough: 'Kept Wild Turkey bold when the market wanted mild — Russell\'s Reserve as legacy line.',
      whyMatters: 'Jimmy is proof that consistency over 60 years beats trend-chasing.',
    },
    {
      id: 'parker-beam',
      name: 'Parker Beam',
      tagline: 'The master distiller who turned Heaven Hill into a hunter\'s paradise.',
      obsession: "Innovation within tradition — limited releases, finished whiskies, Booker's uncut.",
      failure: 'ALS ended his career in the barrel room he loved.',
      breakthrough: "Parker's Heritage Collection — annual love letters to the craft.",
      whyMatters: 'He showed that a value distillery could also be a treasure distillery.',
    },
  ],
  rivalries: [
    {
      id: 'bt-vs-hh',
      title: 'Buffalo Trace vs Heaven Hill',
      sideA: { label: 'Buffalo Trace', argument: 'Romance, allocation hype, campus depth, Eagle Rare at MSRP when you find it.' },
      sideB: { label: 'Heaven Hill', argument: 'Value king — Evan Williams BiB, Elijah Craig, the bourbon working people actually drink.' },
      foundryTake: 'You need both on the shelf. Trace for story; Heaven Hill for honesty.',
      href: '/bourbon/wars/buffalo-trace-vs-heaven-hill',
    },
    {
      id: 'wheat-vs-rye',
      title: 'Wheated vs High-Rye',
      sideA: { label: 'Wheated', argument: 'Soft, sweet, crowd-pleasing — Maker\'s, Larceny, Weller family.' },
      sideB: { label: 'High-Rye', argument: 'Spice, fruit, backbone — Wild Turkey, Four Roses, Bulleit.' },
      foundryTake: 'Your Bourbon DNA probably leans one way. Taste both blind before you declare loyalty.',
      href: '/bourbon/pour-guide',
    },
    {
      id: 'ky-vs-world',
      title: 'Kentucky vs Everyone Else',
      sideA: { label: 'Kentucky', argument: 'Limestone, rickhouses, 95% of production, the Trail, the mythology.' },
      sideB: { label: 'Everywhere else', argument: 'Texas heat, Indiana sourcing mastery, New York craft — bourbon is American, not just Bluegrass.' },
      foundryTake: 'Kentucky is the cathedral. Other states are the frontier. Both are legitimate.',
      href: '/bourbon/map',
    },
  ],
  mysteries: [
    {
      id: 'stitzel-weller',
      question: 'What happened to Stitzel-Weller?',
      tease: 'The distillery that made Pappy — then went quiet.',
      answer: 'Sold and repurposed. Some liquid lived on through Sazerac and Van Winkle sourcing. The campus still stands — a pilgrimage site for hunters who will never taste 1970s juice again.',
      rabbitHoleHref: '/bourbon/stories/pappy-van-winkle',
    },
    {
      id: 'pappy-price',
      question: 'Why is Pappy so expensive?',
      tease: 'It is not just age — it is supply, speculation, and status.',
      answer: 'Tiny allocation, global demand, secondary market frenzy, and the story Julian rebuilt. MSRP is fiction; street price is emotion.',
      rabbitHoleHref: '/bourbon/myths',
    },
    {
      id: 'overrated-bottle',
      question: 'What is the most overrated bottle?',
      tease: 'The answer depends on who you ask — and what they paid.',
      answer: 'Any bottle bought for status instead of taste. Hype bottles at secondary markup often lose to $30 shelf staples blind.',
      rabbitHoleHref: '/bourbon/games',
    },
  ],
  pilgrimages: [
    { id: 'trail', title: 'Kentucky Bourbon Trail', description: 'Buffalo Trace, Maker\'s, Woodford — walk the rickhouses where angel\'s share is a smell, not a metaphor.', href: '/bourbon/map', legendaryObjectId: 'first-distillery' },
    { id: 'bardstown', title: 'Bardstown — Bourbon Capital', description: 'Heaven Hill, 1792, festival week — the town breathes whiskey.', href: '/bourbon/map' },
    { id: 'first-host', title: 'Host your first tasting', description: 'Three pours, three friends, hidden labels — your living room becomes a distillery.', href: '/bourbon/missions/first-tasting', legendaryObjectId: 'first-blind-win' },
    { id: 'producer-deep', title: 'Explore all 12 Producer Atlas houses', description: 'Know the house before the hype — 8/12 is a rite of passage.', href: '/bourbon/producers' },
  ],
  controversies: [
    { id: 'age-overrated', debate: 'Is age overrated?', campA: 'Yes — 15 years can be woody and tired; 6–10 is the sweet spot for many palates.', campB: 'No — age is the only transparent metric on the label; older often means rarer and more complex.', whyItEndures: 'Every shelf talk eventually hits this wall.' },
    { id: 'allocated-worth', debate: 'Is allocated bourbon worth the hunt?', campA: 'No — opportunity cost and secondary insanity; great bourbon exists at $40.', campB: 'Yes — scarcity forces discovery and rewards patience.', whyItEndures: 'Allocation is bourbon\'s lottery — people love lotteries.' },
    { id: 'proof-king', debate: 'Is proof king?', campA: 'Higher proof = more flavor if you add water intentionally.', campB: 'Lower proof = more approachable; heat masks nuance for many drinkers.', whyItEndures: 'Barrel proof culture vs daily sipper culture — both camps have evidence.' },
  ],
  secrets: [
    { id: 'dsp', headline: 'The DSP number tells you who actually distilled it.', body: 'Many brands source from MGP or Heaven Hill. The Distilled Spirits Plant ID on the label reveals the campus — not the marketing story.', whyFeelsSecret: 'Labels are designed to imply heritage; DSP is the truth in small print.' },
    { id: 'barrel-entry', headline: 'Barrel entry proof shapes the entire aging journey.', body: 'Entered at 125 proof max — but distillers choose lower (100–115) for softer aging. Same mash, different entry, different ten-year outcome.', whyFeelsSecret: 'You cannot taste entry proof directly — but you taste its consequences.' },
    { id: 'rickhouse-floor', headline: 'Rickhouse floor position changes flavor.', body: 'Top floors: hotter, more angel\'s share, faster interaction. Bottom: cooler, slower, sometimes more elegant.', whyFeelsSecret: 'Single barrels from different floors can taste like different whiskies.' },
    { id: 'non-chill', headline: 'Non-chill filtered bourbon can taste fuller.', body: 'Chill filtration removes fatty acids that cloud when cold — and some mouthfeel with them. Craft brands often skip it.', whyFeelsSecret: 'Most shelf staples are chill-filtered; you only notice when you compare.' },
  ],
  timeline: [
    { year: '1700s', title: 'Frontier distilling', body: 'Corn-abundant settlers in Kentucky and surrounds begin consistent sour-mash production.' },
    { year: '1785', title: 'Bourbon County named', body: 'Virginia (later Kentucky) honors the French House of Bourbon — the name that would label a category.' },
    { year: '1821', title: 'First advertised "bourbon"', body: 'Commercial distilling scales; the word appears in print.' },
    { year: '1920', title: 'Prohibition', body: 'Most distilleries die. Six medicinal permit holders survive. Inventory ages in silence.', monthDay: '01-17' },
    { year: '1933', title: 'Repeal', body: 'Industry rebuilds — consolidation begins.' },
    { year: '1964', title: 'America\'s Native Spirit', body: 'Congress declares bourbon a distinctive product of the United States — legal protection.', monthDay: '05-04' },
    { year: '1990s', title: 'Premium revival', body: "Single barrel, small batch, Booker's — bourbon stops being only a mixer." },
    { year: '2010s', title: 'Craft explosion', body: 'Micro-distilleries, finished whiskies, cocktail culture returns.' },
    { year: '2020s', title: 'Allocation craze', body: 'Secondary markets, Pappy lines, bourbon as asset class — hype meets hobby.' },
  ],
  whyMatters: [
    { topic: 'Barrel char', notThis: 'Char #4 creates vanilla compounds.', insteadThis: 'This is why two bourbons from similar grain can taste completely different.', body: 'Char caramelizes wood sugars. More char = more extract — but also risk of tannin overload on young whiskey. Char is the hidden variable behind "same mash, different house."' },
    { topic: 'Mash bill', notThis: '51% corn is the legal minimum.', insteadThis: 'The rye vs wheat choice is the personality fork in bourbon.', body: 'Rye adds spice and fruit. Wheat adds softness. Corn is the baseline sweetness. Everything else is accent.' },
    { topic: 'Proof', notThis: 'Proof is twice the ABV.', insteadThis: 'Proof decides whether flavor or heat wins first impression.', body: 'Barrel proof is honesty at full volume. 80 proof is conversation. Neither is wrong — mode matters.' },
    { topic: 'Glassware', notThis: 'Use a Glencairn for tasting.', insteadThis: 'Glass shape decides how much aroma reaches your nose before alcohol burn hits.', body: 'Tulip concentrates vapor; wide rocks glass disperses it. Same pour, different story.' },
  ],
  experienceBeyond: [
    { id: 'glassware', factor: 'Glassware shape', why: 'Aroma concentration — tulip (Glencairn) directs volatile compounds to your nose; wide rocks glass lets them escape.', tip: 'Use a tulip for learning; rocks glass for casual sipping. Wine glass works in a pinch.' },
    { id: 'breathing', factor: 'Letting it breathe', why: 'High-proof pours "open" with 30–60 seconds of air — ethanol volatilizes first, then esters and oak.', tip: 'Not wine decanting — just pause after pouring. Swirl once. Nose again.' },
    { id: 'water', factor: 'Water drops', why: 'Water breaks hydrogen bonds in ethanol, releasing aromatic molecules and reducing burn.', tip: 'Add by the drop on 100+ proof. Stop when burn drops but flavor rises.' },
    { id: 'volume', factor: 'Pour size', why: 'More than ½ oz overwhelms nose and palate — you are evaluating, not finishing.', tip: 'Tasting pours are small. Refill if you want more after notes.' },
    { id: 'temperature', factor: 'Room & hand temperature', why: 'Cold numbs aroma; warm hands on a copita change the pour over minutes.', tip: 'Taste at room temp first. Ice is a later experiment, not the first impression.' },
    { id: 'environment', factor: 'Environment & palate fatigue', why: 'Perfume, BBQ smoke, coffee, and the third pour of the night all lie to your nose.', tip: 'Neutral air for serious notes. Clean glass. Max 4–5 pours per session.' },
    { id: 'mindset', factor: 'Context & company', why: 'Bourbon tastes different alone vs with friends vs after a hard day — context is real data.', tip: 'Same bottle, two nights — compare notes. Foundry remembers both.' },
    { id: 'ice', factor: 'Ice size & melt rate', why: 'Large cube = slow dilution. Crushed = fast chill and water — julep by design.', tip: 'Match ice to intent: large cube for rocks sipping; crushed for cocktails.' },
  ],
  legends: BOURBON_LEGENDS,
  debates: BOURBON_DEBATES,
  legendaryObjects: BOURBON_LEGENDARY_OBJECTS,
  universeMap: BOURBON_UNIVERSE_MAP,
  foundryOriginals: BOURBON_FOUNDRY_ORIGINALS,
};
