import type { FoundryProject } from '../types';

export const BOURBON_PROJECTS: FoundryProject[] = [
  {
    slug: 'blind-tasting-night',
    display_name: 'Blind Tasting Night',
    tagline: 'Host a structured blind tasting with friends',
    vertical_slug: 'bourbon',
    category: 'host',
    description: 'Transform tasting knowledge into a shared experience',
    path_slug: 'road-to-bourbon-steward',
    estimated_days: 14,
    status: 'active',
    steps: [
      { slug: 'select-bottles', title: 'Select 4–6 bottles', description: 'Cover styles and proofs', sort_order: 1 },
      { slug: 'prepare-sheets', title: 'Prepare tasting sheets', description: 'Nose, palate, finish framework', sort_order: 2 },
      { slug: 'host-event', title: 'Host the tasting', description: 'Blind pour, reveal, discuss', sort_order: 3 },
      { slug: 'document-notes', title: 'Document group notes', description: 'Publish tasting notes to community', sort_order: 4 },
    ],
  },
  {
    slug: 'build-bourbon-shelf',
    display_name: 'Build a Bourbon Shelf',
    tagline: 'Curate and display your collection',
    vertical_slug: 'bourbon',
    category: 'build',
    description: 'Physical collection becomes visible expertise',
    path_slug: 'road-to-bourbon-collector',
    estimated_days: 30,
    status: 'active',
    steps: [
      { slug: 'plan-shelf', title: 'Plan your shelf', description: 'Space, lighting, organization', sort_order: 1 },
      { slug: 'catalog-bottles', title: 'Catalog every bottle', description: 'Add to Foundry collection', sort_order: 2 },
      { slug: 'photograph-shelf', title: 'Photograph and share', description: 'Optional public shelf', sort_order: 3 },
    ],
  },
  {
    slug: 'visit-10-distilleries',
    display_name: 'Visit 10 Distilleries',
    tagline: 'Experience bourbon where it is made',
    vertical_slug: 'bourbon',
    category: 'explore',
    description: 'Distillery visits deepen historian-level context',
    path_slug: 'road-to-bourbon-historian',
    estimated_days: 365,
    status: 'active',
    steps: [
      { slug: 'plan-trail', title: 'Plan Kentucky trail', description: 'Map distilleries and tours', sort_order: 1 },
      { slug: 'visit-five', title: 'Visit 5 distilleries', description: 'Document each visit', sort_order: 2 },
      { slug: 'visit-ten', title: 'Complete 10 visits', description: 'Publish travel guide', sort_order: 3 },
    ],
  },
  {
    slug: 'host-bourbon-club',
    display_name: 'Host a Bourbon Club',
    tagline: 'Create a local tasting community',
    vertical_slug: 'bourbon',
    category: 'host',
    description: 'Central Arkansas Bourbon Society starts here',
    path_slug: 'road-to-bourbon-steward',
    estimated_days: 60,
    status: 'active',
    steps: [
      { slug: 'recruit-members', title: 'Recruit 5 members', description: 'Friends who want to learn', sort_order: 1 },
      { slug: 'schedule-monthly', title: 'Schedule monthly tastings', description: 'Recurring club rhythm', sort_order: 2 },
      { slug: 'run-three-events', title: 'Run 3 club events', description: 'Blind tastings, rankings, challenges', sort_order: 3 },
    ],
  },
];
