import path from 'path';
import type { MarketingBlueprint, MarketingManifest, MrrMilestone } from './types';
import { MARKETING_ARTIFACTS } from './types';
import {
  marketingRoot,
  milestonesPath,
  worldMarketingDir,
  writeFileForce,
  writeFileTracked,
} from './paths';

function seoTop100(bp: MarketingBlueprint): string {
  const base = [
    `What Is ${bp.display_name}?`,
    `Beginner Guide to ${bp.display_name}`,
    `Road to ${bp.outcome_statement}`,
    `${bp.display_name} for Students`,
    `${bp.display_name} for Parents`,
    `${bp.display_name} for Educators`,
    `${bp.display_name} Projects`,
    `Common ${bp.display_name} Mistakes`,
    `Best ${bp.display_name} Resources`,
    `${bp.display_name} Portfolio Examples`,
    ...bp.seo_pages.map((p) => p.title),
    ...bp.missions.map((m) => `${m.title} — Step by Step`),
    ...bp.projects.map((p) => `How to ${p}`),
    ...bp.projects.map((p) => `${p} Checklist`),
    `${bp.community_name} — Join the Community`,
    `${bp.tier_2_hook.split('—')[0]?.trim()} Guide`,
    `Is ${bp.display_name} Worth Learning?`,
    `${bp.display_name} vs Courses`,
    `${bp.display_name} for Career Changers`,
    `${bp.display_name} for Homeschool`,
  ];

  const modifiers = [
    'for beginners',
    'for teens',
    'for adults',
    'without experience',
    'in 30 days',
    'step by step',
    'free guide',
    'checklist',
    'worksheet',
    'template',
  ];

  const rows: string[] = [];
  for (const topic of base) {
    rows.push(`| ${rows.length + 1} | ${topic} | informational | draft |`);
    if (rows.length >= 100) break;
  }
  for (const topic of base.slice(0, 15)) {
    for (const mod of modifiers) {
      if (rows.length >= 100) break;
      rows.push(`| ${rows.length + 1} | ${topic} ${mod} | long-tail | draft |`);
    }
  }

  return `# ${bp.display_name} — Top 100 SEO Targets

> Generated by \`npm run build:marketing -- ${bp.slug}\` (PASS-031)

Publish when content_score >= 70.

| # | Target | Intent | Status |
|---|--------|--------|--------|
${rows.slice(0, 100).join('\n')}
`;
}

function seoClusterJson(bp: MarketingBlueprint): string {
  const pages = bp.seo_pages.map((p, i) => ({
    slug: p.slug,
    title: p.title,
    intent: p.intent,
    priority: i + 1,
    status: 'draft',
  }));
  return JSON.stringify(
    {
      domain: bp.slug,
      display_name: bp.display_name,
      cluster_size: pages.length,
      pages,
      publish_gate: { min_content_score: 70 },
    },
    null,
    2,
  );
}

function youtubeTopics(bp: MarketingBlueprint): string {
  const missionTopics = bp.missions.map((m) => `- Mission ${m.title}: full walkthrough`);
  const projectTopics = bp.projects.map((p) => `- Build: ${p} (screen + voiceover)`);
  const outcomeTopics = [
    `- ${bp.outcome_statement} — 12-week journey overview`,
    `- Parent guide: ${bp.parent_headline}`,
    `- Why ${bp.frame} matters in 2026`,
    `- ${bp.community_name} tour`,
    `- Portfolio review: what good looks like`,
  ];
  const filler = [
    `- Day in the life of a ${bp.display_name} learner`,
    `- Common mistakes (and how Foundry fixes them)`,
    `- Free vs Build vs Mastery — honest comparison`,
    `- Educator classroom setup for ${bp.display_name}`,
    `- Student showcase reaction`,
  ];
  const all = [...missionTopics, ...projectTopics, ...outcomeTopics, ...filler];
  while (all.length < 50) {
    all.push(`- FAQ: ${bp.display_name} question ${all.length + 1}`);
  }
  return `# ${bp.display_name} — Top 50 YouTube Topics

${all.slice(0, 50).join('\n')}
`;
}

function tiktokTopics(bp: MarketingBlueprint): string {
  const hooks = bp.missions.map(
    (m) => `- POV: you just finished "${m.title}" — here's what changed`,
  );
  const short = [
    `- ${bp.outcome_statement} in 60 seconds`,
    `- Parent tip: ${bp.parent_headline.slice(0, 50)}…`,
    `- Before/after portfolio artifact`,
    `- "What I wish I knew" — ${bp.display_name}`,
    `- Mission 1 in one minute`,
    `- Free tier vs Build — what's actually included`,
    `- Community challenge teaser`,
    `- Student reaction to first win`,
    `- Educator: assign this instead of a worksheet`,
    `- Career changer pivot story template`,
  ];
  const all = [...hooks, ...short];
  while (all.length < 50) {
    all.push(`- Hook ${all.length + 1}: ${bp.display_name} transformation clip`);
  }
  return `# ${bp.display_name} — Top 50 TikTok Ideas

${all.slice(0, 50).join('\n')}
`;
}

function leadMagnets(bp: MarketingBlueprint): string {
  const magnets = [
    `${bp.display_name} Mission 1 Checklist (PDF)`,
    `${bp.portfolio_label} Starter Template`,
    `Parent One-Pager: ${bp.parent_headline}`,
    `Educator Assignment Pack — ${bp.display_name}`,
    `12-Week ${bp.outcome_statement} Roadmap`,
    ...bp.missions.map((m) => `${m.title} Worksheet`),
    ...bp.projects.map((p) => `${p} Quick-Start Guide`),
    `${bp.display_name} Glossary (printable)`,
    `Future-Proof Assessment — ${bp.frame} edition`,
    `Community Invite: ${bp.community_name}`,
  ];
  return `# ${bp.display_name} — Top 25 Lead Magnets

| # | Magnet | Audience | CTA |
|---|--------|----------|-----|
${magnets
  .slice(0, 25)
  .map((m, i) => {
    const aud = m.includes('Parent')
      ? 'parents'
      : m.includes('Educator')
        ? 'educators'
        : 'learners';
    return `| ${i + 1} | ${m} | ${aud} | Start Mission 1 |`;
  })
  .join('\n')}
`;
}

function emailSequence(bp: MarketingBlueprint): string {
  return `# ${bp.display_name} — Email Nurture Sequence

| Day | Subject | Body focus |
|-----|---------|------------|
| 0 | Welcome — ${bp.outcome_statement} | ${bp.care_reason.slice(0, 80)}… |
| 2 | Your first mission: ${bp.missions[0]?.title ?? 'Mission 1'} | Step-by-step, link to /${bp.slug} |
| 5 | ${bp.parent_headline} | Parent/educator angle |
| 8 | Portfolio proof: ${bp.portfolio_label} | Show artifact examples |
| 12 | Community invite: ${bp.community_name} | Social proof + challenge |
| 16 | Mission 3 nudge | Mid-path momentum |
| 21 | Upgrade moment: ${bp.tier_2_hook} | Build tier value |
| 28 | Mastery preview: ${bp.tier_3_hook} | Community + mentor |
| 35 | Case study template | User story placeholder |
| 45 | Re-engage: what's blocking you? | Survey link |
`;
}

function parentMessaging(bp: MarketingBlueprint): string {
  return `# ${bp.display_name} — Parent Messaging

## Headline

${bp.parent_headline}

## Core promise

${bp.care_reason}

## What your child builds

${bp.projects.map((p) => `- ${p}`).join('\n')}

## Proof points

- Portfolio: **${bp.portfolio_label}**
- Community: **${bp.community_name}**
- Path: **${bp.outcome_statement}**

## Objection handlers

| Objection | Response |
|-----------|----------|
| "Another subscription?" | Free tier proves value first. Build ($4) only when they want sync + portfolio. |
| "Is this safe?" | No open chat with strangers on day 1 — structured missions + moderated community. |
| "Will they finish?" | 5-mission path with visible progress — not infinite content. |

## CTAs

- Start free: \`/${bp.slug}\`
- Parent guide lead magnet
- Schedule 15-min walkthrough (PASS-030 learning lane)
`;
}

function educatorMessaging(bp: MarketingBlueprint): string {
  return `# ${bp.display_name} — Educator Messaging

## Positioning

Foundry is a **road to mastery**, not a worksheet warehouse. Assign missions, not videos.

## Classroom use

| Week | Mission | Deliverable |
|------|---------|-------------|
${bp.missions
  .slice(0, 5)
  .map((m, i) => `| ${i + 1} | ${m.title} | Portfolio artifact |`)
  .join('\n')}

## Tier recommendation

- Free: whole class explores Mission 1
- Build: students who want portfolio sync
- Mastery: club / honors cohort with ${bp.community_name}

## Email snippet

> Assign **${bp.missions[0]?.title ?? 'Mission 1'}** this week. Students submit portfolio artifacts instead of fill-in-the-blank. Foundry tracks progress — you track transformation.
`;
}

function socialCalendar(bp: MarketingBlueprint): string {
  return `# ${bp.display_name} — Social Calendar (90 days)

| Week | Mon | Wed | Fri |
|------|-----|-----|-----|
| 1 | SEO: What Is ${bp.display_name}? | TikTok: Mission 1 hook | YouTube: Outcome overview |
| 2 | Parent tip | TikTok: portfolio before/after | Email: welcome sequence |
| 3 | Educator assign | TikTok: community teaser | SEO: beginner guide |
| 4 | Mission 2 promo | TikTok: student reaction | YouTube: ${bp.projects[0] ?? 'first project'} |
| 5–12 | Rotate SEO / TikTok / YouTube from topic lists | | |

Customize before publish. 80% effort on primary worlds: ai-builder, financial-independence, public-speaking.
`;
}

function contentCalendar30(bp: MarketingBlueprint): string {
  return `# ${bp.display_name} — 30 Day Content Calendar

| Day | Channel | Topic |
|-----|---------|-------|
| 1 | SEO | What Is ${bp.display_name}? |
| 3 | TikTok | ${bp.outcome_statement} in 60s |
| 5 | YouTube | Mission 1 walkthrough |
| 7 | Email | Welcome — ${bp.care_reason.slice(0, 40)}… |
| 10 | Facebook | Parent headline share |
| 14 | SEO | ${bp.seo_pages[1]?.title ?? 'Beginner guide'} |
| 17 | TikTok | Portfolio artifact reveal |
| 21 | Email | Mission 2 nudge |
| 25 | SEO | Common mistakes |
| 30 | YouTube | 30-day transformation recap |

Generated from blueprint — customize before publish.
`;
}

function partnershipTargets(bp: MarketingBlueprint): string {
  return `# ${bp.display_name} — Partnership Targets

## Priority (Life Leverage)

| Partner type | Examples | Offer |
|--------------|----------|-------|
| Homeschool co-ops | Local groups, HSLDA-adjacent lists | Free class pilot + educator pack |
| Parent influencers | Family finance, teen skills | Affiliate + lead magnet |
| Career bootcamps | Adjacent to ${bp.frame} | Cross-promo Mission 1 |
| Libraries / makerspaces | Teen programs | Workshop + Foundry kiosk |
| Educator PD | District tech coaches | Assignment pack |

## Traffic sources to pursue

${bp.traffic_sources.map((s) => `- ${s}`).join('\n')}

## Affiliate angles

- Tools for Mission 1
- Books aligned with ${bp.outcome_statement}
- Events: ${bp.community_name} meetups
`;
}

function launchChecklist(bp: MarketingBlueprint): string {
  return `# ${bp.display_name} — Marketing Launch Checklist

## Factory output (PASS-031)
- [ ] \`npm run build:marketing -- ${bp.slug}\` — all artifacts present
- [ ] SEO cluster reviewed — top 10 prioritized
- [ ] Lead magnets designed (top 3)
- [ ] Email sequence loaded in ESP
- [ ] Social calendar scheduled (30 days)

## Platform
- [ ] Consumer world live at \`/${bp.slug}\`
- [ ] Explore path at \`/explore/${bp.slug}\`
- [ ] Revenue events verified (PASS-029A)
- [ ] Community seeded (PASS-028A)

## Learning lane (PASS-030)
- [ ] 3–5 testers from target segment invited
- [ ] Return rate + mission completion tracked
- [ ] No ads until MRR milestone hit

## Publish gate
- [ ] content_score >= 70 before bulk SEO publish
`;
}

function growthPlanJson(bp: MarketingBlueprint): string {
  return JSON.stringify(
    {
      slug: bp.slug,
      display_name: bp.display_name,
      priority_tier: bp.priority_tier,
      target_audiences: bp.target_audiences,
      traffic_sources: bp.traffic_sources,
      tier_hooks: { build: bp.tier_2_hook, mastery: bp.tier_3_hook },
      primary_cta: `/${bp.slug}`,
      effort_allocation_pct: bp.priority_tier === 'primary' ? 27 : bp.priority_tier === 'expansion' ? 10 : 5,
    },
    null,
    2,
  );
}

export function ensureMarketingScaffold(written: string[], skipped: string[]): void {
  const dirs = [
    'channels/seo',
    'channels/youtube',
    'channels/tiktok',
    'channels/facebook',
    'channels/homeschool',
    'channels/parents',
    'channels/educators',
    'lead-magnets',
    'email-sequences',
    'launch-calendars',
    'affiliates',
    'partnerships',
    'influencers',
    'milestones',
    'worlds',
  ];
  for (const d of dirs) {
    const readme = `# ${d.split('/').pop()}

Channel scaffold — PASS-031 Marketing Factory.

World-specific assets live in \`marketing/worlds/{slug}/\`.
`;
    writeFileTracked(path.join(marketingRoot(), d, 'README.md'), readme, written, skipped);
  }
}

export function manufactureMarketingPack(
  bp: MarketingBlueprint,
  opts: { force?: boolean } = {},
): { written: string[]; skipped: string[]; manifest: MarketingManifest } {
  const written: string[] = [];
  const skipped: string[] = [];
  const dir = worldMarketingDir(bp.slug);
  const write = opts.force ? writeFileForce : writeFileTracked;

  const files: Record<string, string> = {
    'README.md': `# ${bp.display_name} — Marketing World Pack

> **PASS-031 Marketing Factory** · \`npm run build:marketing -- ${bp.slug}\`

| Field | Value |
|-------|-------|
| Frame | ${bp.frame} |
| Outcome | ${bp.outcome_statement} |
| Priority | ${bp.priority_tier} |
| Consumer | \`/${bp.slug}\` |

## Artifacts

${MARKETING_ARTIFACTS.map((a) => `- ${a}`).join('\n')}

80% marketing effort → ai-builder, financial-independence, public-speaking.
`,
    'seo-map.md': `# ${bp.display_name} — SEO Map\n\nSee \`seo-top-100.md\` and \`seo-cluster-map.json\`.`,
    'seo-top-100.md': seoTop100(bp),
    'seo-cluster-map.json': seoClusterJson(bp),
    'youtube-topics.md': youtubeTopics(bp),
    'tiktok-topics.md': tiktokTopics(bp),
    'lead-magnets.md': leadMagnets(bp),
    'email-sequence.md': emailSequence(bp),
    'parent-messaging.md': parentMessaging(bp),
    'educator-messaging.md': educatorMessaging(bp),
    'social-calendar.md': socialCalendar(bp),
    'content-calendar-30d.md': contentCalendar30(bp),
    'partnership-targets.md': partnershipTargets(bp),
    'LAUNCH_CHECKLIST.md': launchChecklist(bp),
    'growth-plan.json': growthPlanJson(bp),
  };

  for (const [name, content] of Object.entries(files)) {
    write(path.join(dir, name), content, written, skipped);
  }

  const manifest: MarketingManifest = {
    slug: bp.slug,
    display_name: bp.display_name,
    generated_at: new Date().toISOString(),
    pass: 'PASS-031',
    priority_tier: bp.priority_tier,
    artifacts: [...MARKETING_ARTIFACTS],
    automation_pct: 95,
  };

  const manifestPath = path.join(dir, 'manifest.json');
  if (opts.force) {
    writeFileForce(manifestPath, JSON.stringify(manifest, null, 2), written);
  } else {
    writeFileTracked(manifestPath, JSON.stringify(manifest, null, 2), written, skipped);
  }

  return { written, skipped, manifest };
}

export const REVENUE_MILESTONES: MrrMilestone[] = [
  {
    period: '2026-07',
    mrr_target_usd: 100,
    mrr_range: '$0 → $100',
    paid_users_target: 25,
    focus: 'First 25 learning lane — prove conversion',
  },
  {
    period: '2026-08',
    mrr_target_usd: 500,
    mrr_range: '$100 → $500',
    paid_users_target: 125,
    focus: 'SEO + lead magnets for AI Builder + FI',
  },
  {
    period: '2026-09',
    mrr_target_usd: 1500,
    mrr_range: '$500 → $1,500',
    paid_users_target: 375,
    focus: 'Public Speaking launch + parent/educator channels',
  },
  {
    period: '2026-10',
    mrr_target_usd: 5000,
    mrr_range: '$1,500 → $5,000',
    paid_users_target: 1250,
    focus: 'Email nurture + partnerships',
  },
  {
    period: '2026-11',
    mrr_target_usd: 7500,
    mrr_range: '$5,000 → $7,500',
    paid_users_target: 1875,
    focus: 'Affiliate + influencer pilots',
  },
  {
    period: '2026-12',
    mrr_target_usd: 9000,
    mrr_range: '$7,500 → $9,000',
    paid_users_target: 2250,
    focus: 'Holiday parent campaigns',
  },
  {
    period: '2027-01',
    mrr_target_usd: 10000,
    mrr_range: '$10,000+',
    paid_users_target: 2500,
    focus: 'Production readiness — January 2027',
  },
];

export function writeRevenueMilestones(written: string[], skipped: string[]): void {
  const content = JSON.stringify(
    {
      pass: 'PASS-031',
      updated_at: new Date().toISOString(),
      note: 'Track MRR not vanity users. Blended ARPU ~$4 Build / $18 Mastery.',
      milestones: REVENUE_MILESTONES,
    },
    null,
    2,
  );
  writeFileForce(milestonesPath(), content, written);
}

// Fix contentCalendar30 reference to corePromise - MarketingBlueprint doesn't have corePromise
// I used optional chaining - need to remove invalid reference
