import type { MasteryPath } from '../types';

export const BOURBON_PATHS: MasteryPath[] = [
  {
    slug: 'road-to-bourbon-enthusiast',
    display_name: 'Road to Bourbon Enthusiast',
    tagline: 'From curious beginner to confident enthusiast',
    vertical_id: 'spirits-beverages',
    vertical_slug: 'bourbon',
    tier: 'enthusiast',
    path_prefix: 'Road to',
    assembled_from: ['academy', 'knowledge', 'reviews'],
    estimated_weeks: 4,
    status: 'active',
    milestones: [
      { slug: 'learn-what-is-bourbon', category: 'learn', title: 'What is bourbon?', description: 'Legal definition and basics', requirement: 'Complete Academy Level 1', academy_lesson_slug: 'what-is-bourbon', sort_order: 1 },
      { slug: 'learn-history', category: 'learn', title: 'Bourbon history', description: 'Origins and evolution', requirement: 'Read encyclopedia history section', encyclopedia_sections: ['history'], sort_order: 2 },
      { slug: 'experience-10-reviews', category: 'experience', title: 'Review 10 bourbons', description: 'Build tasting vocabulary', requirement: 'Publish 10 reviews', target_count: 10, sort_order: 3 },
    ],
  },
  {
    slug: 'road-to-bourbon-collector',
    display_name: 'Road to Bourbon Collector',
    tagline: 'Build a cellar worth sharing',
    vertical_id: 'spirits-beverages',
    vertical_slug: 'bourbon',
    tier: 'collector',
    path_prefix: 'Road to',
    assembled_from: ['academy', 'knowledge', 'collections', 'compare'],
    estimated_weeks: 12,
    status: 'active',
    milestones: [
      { slug: 'learn-mash-bills', category: 'learn', title: 'Mash bills', description: 'Corn, rye, wheat, barley', requirement: 'Complete Academy Level 3', academy_lesson_slug: 'mash-bills', sort_order: 1 },
      { slug: 'collect-shelf', category: 'collect', title: 'Create your shelf', description: 'Own and catalog bottles', requirement: 'Add 25 bottles to collection', target_count: 25, sort_order: 2 },
      { slug: 'compare-rankings', category: 'compare', title: 'Build personal rankings', description: 'Order your favorites', requirement: 'Create ranked collection', sort_order: 3 },
    ],
  },
  {
    slug: 'road-to-bourbon-historian',
    display_name: 'Road to Bourbon Historian',
    tagline: 'Deep context across regions and eras',
    vertical_id: 'spirits-beverages',
    vertical_slug: 'bourbon',
    tier: 'historian',
    path_prefix: 'Road to',
    assembled_from: ['academy', 'knowledge', 'contribute'],
    status: 'active',
    milestones: [
      { slug: 'learn-regions', category: 'learn', title: 'Regional differences', description: 'Kentucky and beyond', requirement: 'Complete Academy Level 4', sort_order: 1 },
      { slug: 'contribute-guide', category: 'contribute', title: 'Write a guide', description: 'Share historical context', requirement: 'Publish 1 editorial guide', sort_order: 2 },
    ],
  },
  {
    slug: 'road-to-bourbon-steward',
    display_name: 'Road to Bourbon Steward',
    tagline: 'Guide others with confidence',
    vertical_id: 'spirits-beverages',
    vertical_slug: 'bourbon',
    tier: 'steward',
    path_prefix: 'Road to',
    assembled_from: ['academy', 'community', 'mentor', 'lead'],
    status: 'draft',
    milestones: [
      { slug: 'mentor-newcomers', category: 'mentor', title: 'Help new members', description: 'Answer questions in club', requirement: '5 helpful contributions', target_count: 5, sort_order: 1 },
      { slug: 'lead-tasting', category: 'lead', title: 'Host a tasting', description: 'Run blind tasting event', requirement: 'Host 1 club event', sort_order: 2 },
    ],
  },
  {
    slug: 'road-to-bourbon-master',
    display_name: 'Road to Bourbon Master',
    tagline: 'Recognized expertise within the community',
    vertical_id: 'spirits-beverages',
    vertical_slug: 'bourbon',
    tier: 'master',
    path_prefix: 'Road to',
    assembled_from: ['academy', 'knowledge', 'collections', 'reviews', 'community', 'projects'],
    estimated_weeks: 52,
    status: 'active',
    milestones: [
      { slug: 'learn-master-class', category: 'learn', title: 'Master class', description: 'Academy Level 7', requirement: 'Complete Academy Level 7', academy_lesson_slug: 'master-class', sort_order: 1 },
      { slug: 'experience-50-reviews', category: 'experience', title: 'Review 50 bourbons', description: 'Deep tasting experience', requirement: '50 published reviews', target_count: 50, sort_order: 2 },
      { slug: 'collect-showcase', category: 'collect', title: 'Curate showcase collection', description: 'Public collection', requirement: 'Public collection with 50+ entities', target_count: 50, sort_order: 3 },
      { slug: 'contribute-guides', category: 'contribute', title: 'Write guides', description: 'Editorial contributions', requirement: '3 published guides', target_count: 3, sort_order: 4 },
      { slug: 'mentor-community', category: 'mentor', title: 'Mentor newcomers', description: 'Club leadership', requirement: '10 mentorship actions', target_count: 10, sort_order: 5 },
      { slug: 'influence-rankings', category: 'influence', title: 'Expert rankings', description: 'Community-recognized lists', requirement: 'Featured ranking list', sort_order: 6 },
    ],
  },
];
